// AUTOGENERATED by scripts/generate-protocols.ts from ddl/GameSessionExService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { GameSessionSearchResultEx } from "./types";
import { GameSessionQuery } from "../game-session-service/types";

export interface SearchSessionsRequest {
  gameSessionQuery: GameSessionQuery;
}
export const SearchSessionsRequest: c.Codec<SearchSessionsRequest> = c.struct({
  gameSessionQuery: GameSessionQuery,
});

export interface SearchSessionsResponse {
  searchResults: GameSessionSearchResultEx[];
}
export const SearchSessionsResponse: c.Codec<SearchSessionsResponse> = c.struct({
  searchResults: c.list(GameSessionSearchResultEx),
});

export const GameSessionExProtocol = defineProtocol({
  id: 123,
  name: "GameSessionExProtocol",
  methods: {
    searchSessions: { id: 1, name: "SearchSessions", request: SearchSessionsRequest, response: SearchSessionsResponse },
  },
});
