// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UserStorageAdmin.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";
import { UserContent, WeightedTag } from "../user-storage/types";

export interface AdminContent {
  userContent: UserContent;
  tags: WeightedTag[];
}
export const AdminContent: c.Codec<AdminContent> = c.struct({
  userContent: UserContent,
  tags: c.list(WeightedTag),
});

export interface BannedUser {
  pid: number;
  reason: string;
  dateBanned: bigint;
  expiration: bigint;
}
export const BannedUser: c.Codec<BannedUser> = c.struct({
  pid: c.u32,
  reason: c.string,
  dateBanned: q.dateTime,
  expiration: q.dateTime,
});
