// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UserStorageAdmin.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { AdminContent, BannedUser } from "./types";
import { ContentProperty, UserContent, UserContentKey, UserContentURL } from "../user-storage/types";

export interface GetContentsToModerateRequest {
  typeId: number;
  offset: number;
  size: number;
}
export const GetContentsToModerateRequest: c.Codec<GetContentsToModerateRequest> = c.struct({
  typeId: c.u32,
  offset: c.u32,
  size: c.u32,
});

export interface GetContentsToModerateResponse {
  contents: UserContent[];
  totalResults: number;
}
export const GetContentsToModerateResponse: c.Codec<GetContentsToModerateResponse> = c.struct({
  contents: c.list(UserContent),
  totalResults: c.u32,
});

export interface FlagContentAsVerifiedRequest {
  contentKey: UserContentKey;
}
export const FlagContentAsVerifiedRequest: c.Codec<FlagContentAsVerifiedRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface FlagContentAsVerifiedResponse {}
export const FlagContentAsVerifiedResponse: c.Codec<FlagContentAsVerifiedResponse> = c.struct({});

export interface BanContentRequest {
  contentKey: UserContentKey;
}
export const BanContentRequest: c.Codec<BanContentRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface BanContentResponse {}
export const BanContentResponse: c.Codec<BanContentResponse> = c.struct({});

export interface BanUserRequest {
  pid: number;
  reason: string;
  banContents: boolean;
  expireDate: bigint;
}
export const BanUserRequest: c.Codec<BanUserRequest> = c.struct({
  pid: c.u32,
  reason: c.string,
  banContents: c.bool,
  expireDate: q.dateTime,
});

export interface BanUserResponse {}
export const BanUserResponse: c.Codec<BanUserResponse> = c.struct({});

export interface BanUserFromContentTypeRequest {
  typeId: number;
  pid: number;
  reason: string;
  banContents: boolean;
  expireDate: bigint;
}
export const BanUserFromContentTypeRequest: c.Codec<BanUserFromContentTypeRequest> = c.struct({
  typeId: c.u32,
  pid: c.u32,
  reason: c.string,
  banContents: c.bool,
  expireDate: q.dateTime,
});

export interface BanUserFromContentTypeResponse {}
export const BanUserFromContentTypeResponse: c.Codec<BanUserFromContentTypeResponse> = c.struct({});

export interface UnbanUserRequest {
  pid: number;
}
export const UnbanUserRequest: c.Codec<UnbanUserRequest> = c.struct({
  pid: c.u32,
});

export interface UnbanUserResponse {}
export const UnbanUserResponse: c.Codec<UnbanUserResponse> = c.struct({});

export interface UnbanUserFromContentTypeRequest {
  typeId: number;
  pid: number;
}
export const UnbanUserFromContentTypeRequest: c.Codec<UnbanUserFromContentTypeRequest> = c.struct({
  typeId: c.u32,
  pid: c.u32,
});

export interface UnbanUserFromContentTypeResponse {}
export const UnbanUserFromContentTypeResponse: c.Codec<UnbanUserFromContentTypeResponse> = c.struct({});

export interface GetContentsToModerateWithThresholdRequest {
  typeId: number;
  threshold: number;
  offset: number;
  size: number;
}
export const GetContentsToModerateWithThresholdRequest: c.Codec<GetContentsToModerateWithThresholdRequest> = c.struct({
  typeId: c.u32,
  threshold: c.u32,
  offset: c.u32,
  size: c.u32,
});

export interface GetContentsToModerateWithThresholdResponse {
  contents: UserContent[];
  totalResults: number;
}
export const GetContentsToModerateWithThresholdResponse: c.Codec<GetContentsToModerateWithThresholdResponse> = c.struct({
  contents: c.list(UserContent),
  totalResults: c.u32,
});

export interface UpdateMetaDataRequest {
  contentKey: UserContentKey;
  properties: ContentProperty[];
}
export const UpdateMetaDataRequest: c.Codec<UpdateMetaDataRequest> = c.struct({
  contentKey: UserContentKey,
  properties: c.list(ContentProperty),
});

export interface UpdateMetaDataResponse {}
export const UpdateMetaDataResponse: c.Codec<UpdateMetaDataResponse> = c.struct({});

export interface UpdateContentDbRequest {
  contentKey: UserContentKey;
  properties: ContentProperty[];
  data: string;
}
export const UpdateContentDbRequest: c.Codec<UpdateContentDbRequest> = c.struct({
  contentKey: UserContentKey,
  properties: c.list(ContentProperty),
  data: c.string,
});

export interface UpdateContentDbResponse {}
export const UpdateContentDbResponse: c.Codec<UpdateContentDbResponse> = c.struct({});

export interface UpdateContentAndGetUploadInfoRequest {
  contentKey: UserContentKey;
  properties: ContentProperty[];
  size: number;
}
export const UpdateContentAndGetUploadInfoRequest: c.Codec<UpdateContentAndGetUploadInfoRequest> = c.struct({
  contentKey: UserContentKey,
  properties: c.list(ContentProperty),
  size: c.u32,
});

export interface UpdateContentAndGetUploadInfoResponse {
  uploadInfo: UserContentURL;
  pendingId: bigint;
  headers: string[];
}
export const UpdateContentAndGetUploadInfoResponse: c.Codec<UpdateContentAndGetUploadInfoResponse> = c.struct({
  uploadInfo: UserContentURL,
  pendingId: c.u64,
  headers: c.list(c.string),
});

export interface DeleteContentRequest {
  contentKey: UserContentKey;
}
export const DeleteContentRequest: c.Codec<DeleteContentRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface DeleteContentResponse {}
export const DeleteContentResponse: c.Codec<DeleteContentResponse> = c.struct({});

export interface BrowseContentsRequest {
  typeId: number;
  offset: number;
  size: number;
}
export const BrowseContentsRequest: c.Codec<BrowseContentsRequest> = c.struct({
  typeId: c.u32,
  offset: c.u32,
  size: c.u32,
});

export interface BrowseContentsResponse {
  contents: AdminContent[];
  totalResults: number;
}
export const BrowseContentsResponse: c.Codec<BrowseContentsResponse> = c.struct({
  contents: c.list(AdminContent),
  totalResults: c.u32,
});

export interface IsUserbannedRequest {
  typeId: number;
  pid: number;
}
export const IsUserbannedRequest: c.Codec<IsUserbannedRequest> = c.struct({
  typeId: c.u32,
  pid: c.u32,
});

export interface IsUserbannedResponse {
  banned: boolean;
  reason: string;
}
export const IsUserbannedResponse: c.Codec<IsUserbannedResponse> = c.struct({
  banned: c.bool,
  reason: c.string,
});

export interface GetBannedUsersRequest {
  typeId: number;
  offset: number;
  size: number;
}
export const GetBannedUsersRequest: c.Codec<GetBannedUsersRequest> = c.struct({
  typeId: c.u32,
  offset: c.u32,
  size: c.u32,
});

export interface GetBannedUsersResponse {
  bannedUsers: BannedUser[];
  totalBannedUsers: number;
}
export const GetBannedUsersResponse: c.Codec<GetBannedUsersResponse> = c.struct({
  bannedUsers: c.list(BannedUser),
  totalBannedUsers: c.u32,
});

export const UserStorageAdminProtocol = defineProtocol({
  id: undefined,
  name: "UserStorageAdminProtocol",
  methods: {
    getContentsToModerate: { id: 1, name: "GetContentsToModerate", request: GetContentsToModerateRequest, response: GetContentsToModerateResponse },
    flagContentAsVerified: { id: 2, name: "FlagContentAsVerified", request: FlagContentAsVerifiedRequest, response: FlagContentAsVerifiedResponse },
    banContent: { id: 3, name: "BanContent", request: BanContentRequest, response: BanContentResponse },
    banUser: { id: 4, name: "BanUser", request: BanUserRequest, response: BanUserResponse },
    banUserFromContentType: { id: 5, name: "BanUserFromContentType", request: BanUserFromContentTypeRequest, response: BanUserFromContentTypeResponse },
    unbanUser: { id: 6, name: "UnbanUser", request: UnbanUserRequest, response: UnbanUserResponse },
    unbanUserFromContentType: { id: 7, name: "UnbanUserFromContentType", request: UnbanUserFromContentTypeRequest, response: UnbanUserFromContentTypeResponse },
    getContentsToModerateWithThreshold: { id: 8, name: "GetContentsToModerateWithThreshold", request: GetContentsToModerateWithThresholdRequest, response: GetContentsToModerateWithThresholdResponse },
    updateMetaData: { id: 9, name: "UpdateMetaData", request: UpdateMetaDataRequest, response: UpdateMetaDataResponse },
    updateContentDb: { id: 10, name: "UpdateContentDB", request: UpdateContentDbRequest, response: UpdateContentDbResponse },
    updateContentAndGetUploadInfo: { id: 11, name: "UpdateContentAndGetUploadInfo", request: UpdateContentAndGetUploadInfoRequest, response: UpdateContentAndGetUploadInfoResponse },
    deleteContent: { id: 12, name: "DeleteContent", request: DeleteContentRequest, response: DeleteContentResponse },
    browseContents: { id: 13, name: "BrowseContents", request: BrowseContentsRequest, response: BrowseContentsResponse },
    isUserbanned: { id: 14, name: "IsUserbanned", request: IsUserbannedRequest, response: IsUserbannedResponse },
    getBannedUsers: { id: 15, name: "GetBannedUsers", request: GetBannedUsersRequest, response: GetBannedUsersResponse },
  },
});
