// AUTOGENERATED by scripts/generate-protocols.ts from ddl/WebNotificationsStorageService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface RegisterUserRequest {}
export const RegisterUserRequest: c.Codec<RegisterUserRequest> = c.struct({});

export interface RegisterUserResponse {}
export const RegisterUserResponse: c.Codec<RegisterUserResponse> = c.struct({});

export interface PollNotificationsRequest {}
export const PollNotificationsRequest: c.Codec<PollNotificationsRequest> = c.struct({});

export interface PollNotificationsResponse {
  listNotifications: string;
  nbNotifications: number;
}
export const PollNotificationsResponse: c.Codec<PollNotificationsResponse> = c.struct({
  listNotifications: c.string,
  nbNotifications: c.i32,
});

export interface UnregisterUserRequest {}
export const UnregisterUserRequest: c.Codec<UnregisterUserRequest> = c.struct({});

export interface UnregisterUserResponse {}
export const UnregisterUserResponse: c.Codec<UnregisterUserResponse> = c.struct({});

export const WebNotificationsStorageProtocol = defineProtocol({
  id: undefined,
  name: "WebNotificationsStorageProtocol",
  methods: {
    registerUser: { id: 1, name: "RegisterUser", request: RegisterUserRequest, response: RegisterUserResponse },
    pollNotifications: { id: 2, name: "PollNotifications", request: PollNotificationsRequest, response: PollNotificationsResponse },
    unregisterUser: { id: 3, name: "UnregisterUser", request: UnregisterUserRequest, response: UnregisterUserResponse },
  },
});
