// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ChallengeHelperService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { FriendChallenge, OnlineChallenge } from "./types";

export interface GenerateMyFriendChallengesRequest {
  friendPids: number[];
}
export const GenerateMyFriendChallengesRequest: c.Codec<GenerateMyFriendChallengesRequest> = c.struct({
  friendPids: c.list(c.u32),
});

export interface GenerateMyFriendChallengesResponse {
  result: FriendChallenge[];
}
export const GenerateMyFriendChallengesResponse: c.Codec<GenerateMyFriendChallengesResponse> = c.struct({
  result: c.list(FriendChallenge),
});

export interface GenerateFriendChallengesRequest {
  targetPid: number;
  friendPids: number[];
}
export const GenerateFriendChallengesRequest: c.Codec<GenerateFriendChallengesRequest> = c.struct({
  targetPid: c.u32,
  friendPids: c.list(c.u32),
});

export interface GenerateFriendChallengesResponse {
  result: FriendChallenge[];
}
export const GenerateFriendChallengesResponse: c.Codec<GenerateFriendChallengesResponse> = c.struct({
  result: c.list(FriendChallenge),
});

export interface GetOnlineChallengesRequest {}
export const GetOnlineChallengesRequest: c.Codec<GetOnlineChallengesRequest> = c.struct({});

export interface GetOnlineChallengesResponse {
  onlineChallenges: OnlineChallenge[];
}
export const GetOnlineChallengesResponse: c.Codec<GetOnlineChallengesResponse> = c.struct({
  onlineChallenges: c.list(OnlineChallenge),
});

export const ChallengeHelperProtocol = defineProtocol({
  id: 105,
  name: "ChallengeHelperProtocol",
  methods: {
    generateMyFriendChallenges: { id: 1, name: "GenerateMyFriendChallenges", request: GenerateMyFriendChallengesRequest, response: GenerateMyFriendChallengesResponse },
    generateFriendChallenges: { id: 2, name: "GenerateFriendChallenges", request: GenerateFriendChallengesRequest, response: GenerateFriendChallengesResponse },
    getOnlineChallenges: { id: 3, name: "GetOnlineChallenges", request: GetOnlineChallengesRequest, response: GetOnlineChallengesResponse },
  },
});
