// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ChallengeHelperService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface FriendChallenge {
  challengeType: number;
  mapId: number;
  friendToBeatPid: number;
  valueOnHand: number;
  valueToBeat: number;
}
export const FriendChallenge: c.Codec<FriendChallenge> = c.struct({
  challengeType: c.u32,
  mapId: c.u32,
  friendToBeatPid: c.u32,
  valueOnHand: c.u32,
  valueToBeat: c.u32,
});

export interface OnlineChallenge {
  challengeId: number;
  staticData: string;
  startTime: bigint;
  endTime: bigint;
  isComplete: boolean;
}
export const OnlineChallenge: c.Codec<OnlineChallenge> = c.struct({
  challengeId: c.u32,
  staticData: c.string,
  startTime: q.dateTime,
  endTime: q.dateTime,
  isComplete: c.bool,
});
