// AUTOGENERATED by scripts/generate-protocols.ts from ddl/trackingextension.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface GetTrackingUserGroupRequest {
  pid: number;
}
export const GetTrackingUserGroupRequest: c.Codec<GetTrackingUserGroupRequest> = c.struct({
  pid: c.u32,
});

export interface GetTrackingUserGroupResponse {
  usergroup: number;
}
export const GetTrackingUserGroupResponse: c.Codec<GetTrackingUserGroupResponse> = c.struct({
  usergroup: c.u32,
});

export interface GetTrackingUserGroupTagsRequest {
  usergroup: number;
}
export const GetTrackingUserGroupTagsRequest: c.Codec<GetTrackingUserGroupTagsRequest> = c.struct({
  usergroup: c.u32,
});

export interface GetTrackingUserGroupTagsResponse {
  tags: string[];
}
export const GetTrackingUserGroupTagsResponse: c.Codec<GetTrackingUserGroupTagsResponse> = c.struct({
  tags: c.list(c.string),
});

export const TrackingExtensionProtocol = defineProtocol({
  id: 1001,
  name: "TrackingExtensionProtocol",
  methods: {
    getTrackingUserGroup: { id: 1, name: "GetTrackingUserGroup", request: GetTrackingUserGroupRequest, response: GetTrackingUserGroupResponse },
    getTrackingUserGroupTags: { id: 2, name: "GetTrackingUserGroupTags", request: GetTrackingUserGroupTagsRequest, response: GetTrackingUserGroupTagsResponse },
  },
});
