// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ClanHelperService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { ClanInfo } from "./types";
import { FriendChallenge } from "../challenge-helper-service/types";

export interface SetClanInfoRequest {
  newInfo: ClanInfo;
}
export const SetClanInfoRequest: c.Codec<SetClanInfoRequest> = c.struct({
  newInfo: ClanInfo,
});

export interface SetClanInfoResponse {}
export const SetClanInfoResponse: c.Codec<SetClanInfoResponse> = c.struct({});

export interface AddPidToClidRequest {
  targetPid: number;
  clid: number;
}
export const AddPidToClidRequest: c.Codec<AddPidToClidRequest> = c.struct({
  targetPid: c.u32,
  clid: c.u32,
});

export interface AddPidToClidResponse {}
export const AddPidToClidResponse: c.Codec<AddPidToClidResponse> = c.struct({});

export interface RemoveMemberByPidRequest {
  targetPid: number;
}
export const RemoveMemberByPidRequest: c.Codec<RemoveMemberByPidRequest> = c.struct({
  targetPid: c.u32,
});

export interface RemoveMemberByPidResponse {}
export const RemoveMemberByPidResponse: c.Codec<RemoveMemberByPidResponse> = c.struct({});

export interface DisbandEntireClidRequest {
  targetClid: number;
}
export const DisbandEntireClidRequest: c.Codec<DisbandEntireClidRequest> = c.struct({
  targetClid: c.u32,
});

export interface DisbandEntireClidResponse {}
export const DisbandEntireClidResponse: c.Codec<DisbandEntireClidResponse> = c.struct({});

export interface GetClanInfoByPidRequest {
  targetPid: number;
}
export const GetClanInfoByPidRequest: c.Codec<GetClanInfoByPidRequest> = c.struct({
  targetPid: c.u32,
});

export interface GetClanInfoByPidResponse {
  clanInfo: ClanInfo;
}
export const GetClanInfoByPidResponse: c.Codec<GetClanInfoByPidResponse> = c.struct({
  clanInfo: ClanInfo,
});

export interface GetClanInfoByClidRequest {
  targetClid: number;
}
export const GetClanInfoByClidRequest: c.Codec<GetClanInfoByClidRequest> = c.struct({
  targetClid: c.u32,
});

export interface GetClanInfoByClidResponse {
  clanInfo: ClanInfo;
}
export const GetClanInfoByClidResponse: c.Codec<GetClanInfoByClidResponse> = c.struct({
  clanInfo: ClanInfo,
});

export interface GetMemberListByPidRequest {
  targetPid: number;
}
export const GetMemberListByPidRequest: c.Codec<GetMemberListByPidRequest> = c.struct({
  targetPid: c.u32,
});

export interface GetMemberListByPidResponse {
  members: number[];
}
export const GetMemberListByPidResponse: c.Codec<GetMemberListByPidResponse> = c.struct({
  members: c.list(c.u32),
});

export interface GetMemberListByClidRequest {
  targetClid: number;
}
export const GetMemberListByClidRequest: c.Codec<GetMemberListByClidRequest> = c.struct({
  targetClid: c.u32,
});

export interface GetMemberListByClidResponse {
  members: number[];
}
export const GetMemberListByClidResponse: c.Codec<GetMemberListByClidResponse> = c.struct({
  members: c.list(c.u32),
});

export interface GenerateClanChallengesRequest {
  targetPid: number;
}
export const GenerateClanChallengesRequest: c.Codec<GenerateClanChallengesRequest> = c.struct({
  targetPid: c.u32,
});

export interface GenerateClanChallengesResponse {
  result: FriendChallenge[];
}
export const GenerateClanChallengesResponse: c.Codec<GenerateClanChallengesResponse> = c.struct({
  result: c.list(FriendChallenge),
});

export const ClanHelperProtocol = defineProtocol({
  id: 106,
  name: "ClanHelperProtocol",
  methods: {
    setClanInfo: { id: 1, name: "SetClanInfo", request: SetClanInfoRequest, response: SetClanInfoResponse },
    addPidToClid: { id: 2, name: "AddPIDToCLID", request: AddPidToClidRequest, response: AddPidToClidResponse },
    removeMemberByPid: { id: 3, name: "RemoveMemberByPID", request: RemoveMemberByPidRequest, response: RemoveMemberByPidResponse },
    disbandEntireClid: { id: 4, name: "DisbandEntireCLID", request: DisbandEntireClidRequest, response: DisbandEntireClidResponse },
    getClanInfoByPid: { id: 5, name: "GetClanInfoByPID", request: GetClanInfoByPidRequest, response: GetClanInfoByPidResponse },
    getClanInfoByClid: { id: 6, name: "GetClanInfoByCLID", request: GetClanInfoByClidRequest, response: GetClanInfoByClidResponse },
    getMemberListByPid: { id: 7, name: "GetMemberListByPID", request: GetMemberListByPidRequest, response: GetMemberListByPidResponse },
    getMemberListByClid: { id: 8, name: "GetMemberListByCLID", request: GetMemberListByClidRequest, response: GetMemberListByClidResponse },
    generateClanChallenges: { id: 9, name: "GenerateClanChallenges", request: GenerateClanChallengesRequest, response: GenerateClanChallengesResponse },
  },
});
