// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ClanHelperService.json. Do not edit.
import * as c from "../../quazal/codec";

export interface ClanInfo {
  clid: number;
  tag: string;
  title: string;
  motto: string;
}
export const ClanInfo: c.Codec<ClanInfo> = c.struct({
  clid: c.u32,
  tag: c.string,
  title: c.string,
  motto: c.string,
});
