// AUTOGENERATED by scripts/generate-protocols.ts from ddl/FriendsService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { FriendData, RelationshipData } from "./types";

export interface AddFriendRequest {
  uiPlayer: number;
  uiDetails: number;
  strMessage: string;
}
export const AddFriendRequest: c.Codec<AddFriendRequest> = c.struct({
  uiPlayer: c.u32,
  uiDetails: c.u32,
  strMessage: c.string,
});

export interface AddFriendResponse {
  returnValue: boolean;
}
export const AddFriendResponse: c.Codec<AddFriendResponse> = c.struct({
  returnValue: c.bool,
});

export interface AddFriendByNameRequest {
  strPlayerName: string;
  uiDetails: number;
  strMessage: string;
}
export const AddFriendByNameRequest: c.Codec<AddFriendByNameRequest> = c.struct({
  strPlayerName: c.string,
  uiDetails: c.u32,
  strMessage: c.string,
});

export interface AddFriendByNameResponse {
  returnValue: boolean;
}
export const AddFriendByNameResponse: c.Codec<AddFriendByNameResponse> = c.struct({
  returnValue: c.bool,
});

export interface AddFriendWithDetailsRequest {
  uiPlayer: number;
  uiDetails: number;
  strMessage: string;
}
export const AddFriendWithDetailsRequest: c.Codec<AddFriendWithDetailsRequest> = c.struct({
  uiPlayer: c.u32,
  uiDetails: c.u32,
  strMessage: c.string,
});

export interface AddFriendWithDetailsResponse {
  relationshipData: RelationshipData;
}
export const AddFriendWithDetailsResponse: c.Codec<AddFriendWithDetailsResponse> = c.struct({
  relationshipData: RelationshipData,
});

export interface AddFriendByNameWithDetailsRequest {
  strPlayerName: string;
  uiDetails: number;
  strMessage: string;
}
export const AddFriendByNameWithDetailsRequest: c.Codec<AddFriendByNameWithDetailsRequest> = c.struct({
  strPlayerName: c.string,
  uiDetails: c.u32,
  strMessage: c.string,
});

export interface AddFriendByNameWithDetailsResponse {
  relationshipData: RelationshipData;
}
export const AddFriendByNameWithDetailsResponse: c.Codec<AddFriendByNameWithDetailsResponse> = c.struct({
  relationshipData: RelationshipData,
});

export interface AcceptFriendshipRequest {
  uiPlayer: number;
}
export const AcceptFriendshipRequest: c.Codec<AcceptFriendshipRequest> = c.struct({
  uiPlayer: c.u32,
});

export interface AcceptFriendshipResponse {
  returnValue: boolean;
}
export const AcceptFriendshipResponse: c.Codec<AcceptFriendshipResponse> = c.struct({
  returnValue: c.bool,
});

export interface DeclineFriendshipRequest {
  uiPlayer: number;
}
export const DeclineFriendshipRequest: c.Codec<DeclineFriendshipRequest> = c.struct({
  uiPlayer: c.u32,
});

export interface DeclineFriendshipResponse {
  returnValue: boolean;
}
export const DeclineFriendshipResponse: c.Codec<DeclineFriendshipResponse> = c.struct({
  returnValue: c.bool,
});

export interface BlackListRequest {
  uiPlayer: number;
  uiDetails: number;
}
export const BlackListRequest: c.Codec<BlackListRequest> = c.struct({
  uiPlayer: c.u32,
  uiDetails: c.u32,
});

export interface BlackListResponse {
  returnValue: boolean;
}
export const BlackListResponse: c.Codec<BlackListResponse> = c.struct({
  returnValue: c.bool,
});

export interface BlackListByNameRequest {
  strPlayerName: string;
  uiDetails: number;
}
export const BlackListByNameRequest: c.Codec<BlackListByNameRequest> = c.struct({
  strPlayerName: c.string,
  uiDetails: c.u32,
});

export interface BlackListByNameResponse {
  returnValue: boolean;
}
export const BlackListByNameResponse: c.Codec<BlackListByNameResponse> = c.struct({
  returnValue: c.bool,
});

export interface ClearRelationshipRequest {
  uiPlayer: number;
}
export const ClearRelationshipRequest: c.Codec<ClearRelationshipRequest> = c.struct({
  uiPlayer: c.u32,
});

export interface ClearRelationshipResponse {
  returnValue: boolean;
}
export const ClearRelationshipResponse: c.Codec<ClearRelationshipResponse> = c.struct({
  returnValue: c.bool,
});

export interface UpdateDetailsRequest {
  uiPlayer: number;
  uiDetails: number;
}
export const UpdateDetailsRequest: c.Codec<UpdateDetailsRequest> = c.struct({
  uiPlayer: c.u32,
  uiDetails: c.u32,
});

export interface UpdateDetailsResponse {
  returnValue: boolean;
}
export const UpdateDetailsResponse: c.Codec<UpdateDetailsResponse> = c.struct({
  returnValue: c.bool,
});

export interface GetListRequest {
  byRelationship: number;
  bReversed: boolean;
}
export const GetListRequest: c.Codec<GetListRequest> = c.struct({
  byRelationship: c.u8,
  bReversed: c.bool,
});

export interface GetListResponse {
  lstFriendsList: number[];
}
export const GetListResponse: c.Codec<GetListResponse> = c.struct({
  lstFriendsList: c.list(c.u32),
});

export interface GetDetailedListRequest {
  byRelationship: number;
  bReversed: boolean;
}
export const GetDetailedListRequest: c.Codec<GetDetailedListRequest> = c.struct({
  byRelationship: c.u8,
  bReversed: c.bool,
});

export interface GetDetailedListResponse {
  lstFriendsList: FriendData[];
}
export const GetDetailedListResponse: c.Codec<GetDetailedListResponse> = c.struct({
  lstFriendsList: c.list(FriendData),
});

export interface GetRelationshipsRequest {
  resultRange: q.ResultRange;
}
export const GetRelationshipsRequest: c.Codec<GetRelationshipsRequest> = c.struct({
  resultRange: q.ResultRange,
});

export interface GetRelationshipsResponse {
  uiTotalCount: number;
  lstRelationshipsList: RelationshipData[];
}
export const GetRelationshipsResponse: c.Codec<GetRelationshipsResponse> = c.struct({
  uiTotalCount: c.u32,
  lstRelationshipsList: c.list(RelationshipData),
});

export const FriendsProtocol = defineProtocol({
  id: 20,
  name: "FriendsProtocol",
  methods: {
    addFriend: { id: 1, name: "AddFriend", request: AddFriendRequest, response: AddFriendResponse },
    addFriendByName: { id: 2, name: "AddFriendByName", request: AddFriendByNameRequest, response: AddFriendByNameResponse },
    addFriendWithDetails: { id: 3, name: "AddFriendWithDetails", request: AddFriendWithDetailsRequest, response: AddFriendWithDetailsResponse },
    addFriendByNameWithDetails: { id: 4, name: "AddFriendByNameWithDetails", request: AddFriendByNameWithDetailsRequest, response: AddFriendByNameWithDetailsResponse },
    acceptFriendship: { id: 5, name: "AcceptFriendship", request: AcceptFriendshipRequest, response: AcceptFriendshipResponse },
    declineFriendship: { id: 6, name: "DeclineFriendship", request: DeclineFriendshipRequest, response: DeclineFriendshipResponse },
    blackList: { id: 7, name: "BlackList", request: BlackListRequest, response: BlackListResponse },
    blackListByName: { id: 8, name: "BlackListByName", request: BlackListByNameRequest, response: BlackListByNameResponse },
    clearRelationship: { id: 9, name: "ClearRelationship", request: ClearRelationshipRequest, response: ClearRelationshipResponse },
    updateDetails: { id: 10, name: "UpdateDetails", request: UpdateDetailsRequest, response: UpdateDetailsResponse },
    getList: { id: 11, name: "GetList", request: GetListRequest, response: GetListResponse },
    getDetailedList: { id: 12, name: "GetDetailedList", request: GetDetailedListRequest, response: GetDetailedListResponse },
    getRelationships: { id: 13, name: "GetRelationships", request: GetRelationshipsRequest, response: GetRelationshipsResponse },
  },
});
