// AUTOGENERATED by scripts/generate-protocols.ts from ddl/FriendsService.json. Do not edit.
import * as c from "../../quazal/codec";

export interface FriendData {
  pid: number;
  strName: string;
  byRelationship: number;
  uiDetails: number;
  strStatus: string;
}
export const FriendData: c.Codec<FriendData> = c.struct({
  pid: c.u32,
  strName: c.string,
  byRelationship: c.u8,
  uiDetails: c.u32,
  strStatus: c.string,
});

export interface RelationshipData {
  pid: number;
  strName: string;
  byRelationship: number;
  uiDetails: number;
  byStatus: number;
}
export const RelationshipData: c.Codec<RelationshipData> = c.struct({
  pid: c.u32,
  strName: c.string,
  byRelationship: c.u8,
  uiDetails: c.u32,
  byStatus: c.u8,
});
