// AUTOGENERATED by scripts/generate-protocols.ts from ddl/LadderHelperService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface GetUnixUtcRequest {}
export const GetUnixUtcRequest: c.Codec<GetUnixUtcRequest> = c.struct({});

export interface GetUnixUtcResponse {
  time: number;
}
export const GetUnixUtcResponse: c.Codec<GetUnixUtcResponse> = c.struct({
  time: c.u32,
});

export interface AreLaddersAvailableInCountryRequest {}
export const AreLaddersAvailableInCountryRequest: c.Codec<AreLaddersAvailableInCountryRequest> = c.struct({});

export interface AreLaddersAvailableInCountryResponse {
  allowed: boolean;
}
export const AreLaddersAvailableInCountryResponse: c.Codec<AreLaddersAvailableInCountryResponse> = c.struct({
  allowed: c.bool,
});

export interface CheckLadderIsRunningRequest {
  startTime: number;
  endTime: number;
}
export const CheckLadderIsRunningRequest: c.Codec<CheckLadderIsRunningRequest> = c.struct({
  startTime: c.u32,
  endTime: c.u32,
});

export interface CheckLadderIsRunningResponse {
  running: boolean;
}
export const CheckLadderIsRunningResponse: c.Codec<CheckLadderIsRunningResponse> = c.struct({
  running: c.bool,
});

export interface ClearLadderLeaderboardRequest {
  statSet: number;
}
export const ClearLadderLeaderboardRequest: c.Codec<ClearLadderLeaderboardRequest> = c.struct({
  statSet: c.i32,
});

export interface ClearLadderLeaderboardResponse {
  success: boolean;
}
export const ClearLadderLeaderboardResponse: c.Codec<ClearLadderLeaderboardResponse> = c.struct({
  success: c.bool,
});

export const LadderHelperProtocol = defineProtocol({
  id: 107,
  name: "LadderHelperProtocol",
  methods: {
    getUnixUtc: { id: 1, name: "GetUnixUTC", request: GetUnixUtcRequest, response: GetUnixUtcResponse },
    areLaddersAvailableInCountry: { id: 2, name: "AreLaddersAvailableInCountry", request: AreLaddersAvailableInCountryRequest, response: AreLaddersAvailableInCountryResponse },
    checkLadderIsRunning: { id: 3, name: "CheckLadderIsRunning", request: CheckLadderIsRunningRequest, response: CheckLadderIsRunningResponse },
    clearLadderLeaderboard: { id: 4, name: "ClearLadderLeaderboard", request: ClearLadderLeaderboardRequest, response: ClearLadderLeaderboardResponse },
  },
});
