// AUTOGENERATED by scripts/generate-protocols.ts from ddl/AccountManagementService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { AccountData, BasicAccountInfo } from "./types";

export interface CreateAccountRequest {
  strPrincipalName: string;
  strKey: string;
  uiGroups: number;
  strEmail: string;
}
export const CreateAccountRequest: c.Codec<CreateAccountRequest> = c.struct({
  strPrincipalName: c.string,
  strKey: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
});

export interface CreateAccountResponse {
  returnValue: number;
}
export const CreateAccountResponse: c.Codec<CreateAccountResponse> = c.struct({
  returnValue: q.qresult,
});

export interface DeleteAccountRequest {
  idPrincipal: number;
}
export const DeleteAccountRequest: c.Codec<DeleteAccountRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface DeleteAccountResponse {}
export const DeleteAccountResponse: c.Codec<DeleteAccountResponse> = c.struct({});

export interface DisableAccountRequest {
  idPrincipal: number;
  dtUntil: bigint;
  strMessage: string;
}
export const DisableAccountRequest: c.Codec<DisableAccountRequest> = c.struct({
  idPrincipal: c.u32,
  dtUntil: q.dateTime,
  strMessage: c.string,
});

export interface DisableAccountResponse {
  returnValue: number;
}
export const DisableAccountResponse: c.Codec<DisableAccountResponse> = c.struct({
  returnValue: q.qresult,
});

export interface ChangePasswordRequest {
  strNewKey: string;
}
export const ChangePasswordRequest: c.Codec<ChangePasswordRequest> = c.struct({
  strNewKey: c.string,
});

export interface ChangePasswordResponse {
  returnValue: boolean;
}
export const ChangePasswordResponse: c.Codec<ChangePasswordResponse> = c.struct({
  returnValue: c.bool,
});

export interface TestCapabilityRequest {
  uiCapability: number;
}
export const TestCapabilityRequest: c.Codec<TestCapabilityRequest> = c.struct({
  uiCapability: c.u32,
});

export interface TestCapabilityResponse {
  returnValue: boolean;
}
export const TestCapabilityResponse: c.Codec<TestCapabilityResponse> = c.struct({
  returnValue: c.bool,
});

export interface GetNameRequest {
  idPrincipal: number;
}
export const GetNameRequest: c.Codec<GetNameRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface GetNameResponse {
  strName: string;
}
export const GetNameResponse: c.Codec<GetNameResponse> = c.struct({
  strName: c.string,
});

export interface GetAccountDataRequest {}
export const GetAccountDataRequest: c.Codec<GetAccountDataRequest> = c.struct({});

export interface GetAccountDataResponse {
  returnValue: number;
  oAccountData: AccountData;
}
export const GetAccountDataResponse: c.Codec<GetAccountDataResponse> = c.struct({
  returnValue: q.qresult,
  oAccountData: AccountData,
});

export interface GetPrivateDataRequest {}
export const GetPrivateDataRequest: c.Codec<GetPrivateDataRequest> = c.struct({});

export interface GetPrivateDataResponse {
  returnValue: boolean;
  oData: q.AnyData;
}
export const GetPrivateDataResponse: c.Codec<GetPrivateDataResponse> = c.struct({
  returnValue: c.bool,
  oData: q.anyData,
});

export interface GetPublicDataRequest {
  idPrincipal: number;
}
export const GetPublicDataRequest: c.Codec<GetPublicDataRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface GetPublicDataResponse {
  returnValue: boolean;
  oData: q.AnyData;
}
export const GetPublicDataResponse: c.Codec<GetPublicDataResponse> = c.struct({
  returnValue: c.bool,
  oData: q.anyData,
});

export interface GetMultiplePublicDataRequest {
  lstPrincipals: number[];
}
export const GetMultiplePublicDataRequest: c.Codec<GetMultiplePublicDataRequest> = c.struct({
  lstPrincipals: c.list(c.u32),
});

export interface GetMultiplePublicDataResponse {
  returnValue: boolean;
  oData: q.AnyData[];
}
export const GetMultiplePublicDataResponse: c.Codec<GetMultiplePublicDataResponse> = c.struct({
  returnValue: c.bool,
  oData: c.list(q.anyData),
});

export interface UpdateAccountNameRequest {
  strName: string;
}
export const UpdateAccountNameRequest: c.Codec<UpdateAccountNameRequest> = c.struct({
  strName: c.string,
});

export interface UpdateAccountNameResponse {
  returnValue: number;
}
export const UpdateAccountNameResponse: c.Codec<UpdateAccountNameResponse> = c.struct({
  returnValue: q.qresult,
});

export interface UpdateAccountEmailRequest {
  strName: string;
}
export const UpdateAccountEmailRequest: c.Codec<UpdateAccountEmailRequest> = c.struct({
  strName: c.string,
});

export interface UpdateAccountEmailResponse {
  returnValue: number;
}
export const UpdateAccountEmailResponse: c.Codec<UpdateAccountEmailResponse> = c.struct({
  returnValue: q.qresult,
});

export interface UpdateCustomDataRequest {
  oPublicData: q.AnyData;
  oPrivateData: q.AnyData;
}
export const UpdateCustomDataRequest: c.Codec<UpdateCustomDataRequest> = c.struct({
  oPublicData: q.anyData,
  oPrivateData: q.anyData,
});

export interface UpdateCustomDataResponse {
  returnValue: number;
}
export const UpdateCustomDataResponse: c.Codec<UpdateCustomDataResponse> = c.struct({
  returnValue: q.qresult,
});

export interface FindByNameRegexRequest {
  uiGroups: number;
  strRegex: string;
  resultRange: q.ResultRange;
}
export const FindByNameRegexRequest: c.Codec<FindByNameRegexRequest> = c.struct({
  uiGroups: c.u32,
  strRegex: c.string,
  resultRange: q.ResultRange,
});

export interface FindByNameRegexResponse {
  plstAccounts: BasicAccountInfo[];
}
export const FindByNameRegexResponse: c.Codec<FindByNameRegexResponse> = c.struct({
  plstAccounts: c.list(BasicAccountInfo),
});

export interface UpdateAccountExpiryDateRequest {
  idPrincipal: number;
  dtExpiry: bigint;
  strExpiredMessage: string;
}
export const UpdateAccountExpiryDateRequest: c.Codec<UpdateAccountExpiryDateRequest> = c.struct({
  idPrincipal: c.u32,
  dtExpiry: q.dateTime,
  strExpiredMessage: c.string,
});

export interface UpdateAccountExpiryDateResponse {}
export const UpdateAccountExpiryDateResponse: c.Codec<UpdateAccountExpiryDateResponse> = c.struct({});

export interface UpdateAccountEffectiveDateRequest {
  idPrincipal: number;
  dtEffectiveFrom: bigint;
  strNotEffectiveMessage: string;
}
export const UpdateAccountEffectiveDateRequest: c.Codec<UpdateAccountEffectiveDateRequest> = c.struct({
  idPrincipal: c.u32,
  dtEffectiveFrom: q.dateTime,
  strNotEffectiveMessage: c.string,
});

export interface UpdateAccountEffectiveDateResponse {}
export const UpdateAccountEffectiveDateResponse: c.Codec<UpdateAccountEffectiveDateResponse> = c.struct({});

export interface UpdateStatusRequest {
  strStatus: string;
}
export const UpdateStatusRequest: c.Codec<UpdateStatusRequest> = c.struct({
  strStatus: c.string,
});

export interface UpdateStatusResponse {}
export const UpdateStatusResponse: c.Codec<UpdateStatusResponse> = c.struct({});

export interface GetStatusRequest {
  idPrincipal: number;
}
export const GetStatusRequest: c.Codec<GetStatusRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface GetStatusResponse {
  strStatus: string;
}
export const GetStatusResponse: c.Codec<GetStatusResponse> = c.struct({
  strStatus: c.string,
});

export interface GetLastConnectionStatsRequest {
  idPrincipal: number;
}
export const GetLastConnectionStatsRequest: c.Codec<GetLastConnectionStatsRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface GetLastConnectionStatsResponse {
  dtLastSessionLogin: bigint;
  dtLastSessionLogout: bigint;
  dtCurrentSessionLogin: bigint;
}
export const GetLastConnectionStatsResponse: c.Codec<GetLastConnectionStatsResponse> = c.struct({
  dtLastSessionLogin: q.dateTime,
  dtLastSessionLogout: q.dateTime,
  dtCurrentSessionLogin: q.dateTime,
});

export interface ResetPasswordRequest {}
export const ResetPasswordRequest: c.Codec<ResetPasswordRequest> = c.struct({});

export interface ResetPasswordResponse {
  returnValue: boolean;
}
export const ResetPasswordResponse: c.Codec<ResetPasswordResponse> = c.struct({
  returnValue: c.bool,
});

export interface CreateAccountWithCustomDataRequest {
  strPrincipalName: string;
  strKey: string;
  uiGroups: number;
  strEmail: string;
  oPublicData: q.AnyData;
  oPrivateData: q.AnyData;
}
export const CreateAccountWithCustomDataRequest: c.Codec<CreateAccountWithCustomDataRequest> = c.struct({
  strPrincipalName: c.string,
  strKey: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
  oPublicData: q.anyData,
  oPrivateData: q.anyData,
});

export interface CreateAccountWithCustomDataResponse {}
export const CreateAccountWithCustomDataResponse: c.Codec<CreateAccountWithCustomDataResponse> = c.struct({});

export interface RetrieveAccountRequest {}
export const RetrieveAccountRequest: c.Codec<RetrieveAccountRequest> = c.struct({});

export interface RetrieveAccountResponse {
  oAccountData: AccountData;
  oPublicData: q.AnyData;
  oPrivateData: q.AnyData;
}
export const RetrieveAccountResponse: c.Codec<RetrieveAccountResponse> = c.struct({
  oAccountData: AccountData,
  oPublicData: q.anyData,
  oPrivateData: q.anyData,
});

export interface UpdateAccountRequest {
  strKey: string;
  strEmail: string;
  oPublicData: q.AnyData;
  oPrivateData: q.AnyData;
}
export const UpdateAccountRequest: c.Codec<UpdateAccountRequest> = c.struct({
  strKey: c.string,
  strEmail: c.string,
  oPublicData: q.anyData,
  oPrivateData: q.anyData,
});

export interface UpdateAccountResponse {}
export const UpdateAccountResponse: c.Codec<UpdateAccountResponse> = c.struct({});

export interface ChangePasswordByGuestRequest {
  strPrincipalName: string;
  strEmail: string;
  strKey: string;
}
export const ChangePasswordByGuestRequest: c.Codec<ChangePasswordByGuestRequest> = c.struct({
  strPrincipalName: c.string,
  strEmail: c.string,
  strKey: c.string,
});

export interface ChangePasswordByGuestResponse {}
export const ChangePasswordByGuestResponse: c.Codec<ChangePasswordByGuestResponse> = c.struct({});

export interface FindByNameLikeRequest {
  uiGroups: number;
  strLike: string;
  resultRange: q.ResultRange;
}
export const FindByNameLikeRequest: c.Codec<FindByNameLikeRequest> = c.struct({
  uiGroups: c.u32,
  strLike: c.string,
  resultRange: q.ResultRange,
});

export interface FindByNameLikeResponse {
  plstAccounts: BasicAccountInfo[];
}
export const FindByNameLikeResponse: c.Codec<FindByNameLikeResponse> = c.struct({
  plstAccounts: c.list(BasicAccountInfo),
});

export interface CustomCreateAccountRequest {
  strPrincipalName: string;
  strKey: string;
  uiGroups: number;
  strEmail: string;
  oAuthData: q.AnyData;
}
export const CustomCreateAccountRequest: c.Codec<CustomCreateAccountRequest> = c.struct({
  strPrincipalName: c.string,
  strKey: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
  oAuthData: q.anyData,
});

export interface CustomCreateAccountResponse {
  pid: number;
}
export const CustomCreateAccountResponse: c.Codec<CustomCreateAccountResponse> = c.struct({
  pid: c.u32,
});

export interface LookupOrCreateAccountRequest {
  strPrincipalName: string;
  strKey: string;
  uiGroups: number;
  strEmail: string;
  oAuthData: q.AnyData;
}
export const LookupOrCreateAccountRequest: c.Codec<LookupOrCreateAccountRequest> = c.struct({
  strPrincipalName: c.string,
  strKey: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
  oAuthData: q.anyData,
});

export interface LookupOrCreateAccountResponse {
  pid: number;
}
export const LookupOrCreateAccountResponse: c.Codec<LookupOrCreateAccountResponse> = c.struct({
  pid: c.u32,
});

export interface CreateAccountExRequest {
  principalType: number;
  strPrincipalName: string;
  strKey: string;
  uiGroups: number;
  strEmail: string;
  context: bigint;
}
export const CreateAccountExRequest: c.Codec<CreateAccountExRequest> = c.struct({
  principalType: c.i8,
  strPrincipalName: c.string,
  strKey: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
  context: c.u64,
});

export interface CreateAccountExResponse {
  returnValue: number;
}
export const CreateAccountExResponse: c.Codec<CreateAccountExResponse> = c.struct({
  returnValue: q.qresult,
});

export interface DisconnectPrincipalRequest {
  idPrincipal: number;
}
export const DisconnectPrincipalRequest: c.Codec<DisconnectPrincipalRequest> = c.struct({
  idPrincipal: c.u32,
});

export interface DisconnectPrincipalResponse {
  returnValue: boolean;
}
export const DisconnectPrincipalResponse: c.Codec<DisconnectPrincipalResponse> = c.struct({
  returnValue: c.bool,
});

export interface DisconnectAllPrincipalsRequest {}
export const DisconnectAllPrincipalsRequest: c.Codec<DisconnectAllPrincipalsRequest> = c.struct({});

export interface DisconnectAllPrincipalsResponse {
  returnValue: boolean;
}
export const DisconnectAllPrincipalsResponse: c.Codec<DisconnectAllPrincipalsResponse> = c.struct({
  returnValue: c.bool,
});

export const AccountManagementProtocol = defineProtocol({
  id: 25,
  name: "AccountManagementProtocol",
  methods: {
    createAccount: { id: 1, name: "CreateAccount", request: CreateAccountRequest, response: CreateAccountResponse },
    deleteAccount: { id: 2, name: "DeleteAccount", request: DeleteAccountRequest, response: DeleteAccountResponse },
    disableAccount: { id: 3, name: "DisableAccount", request: DisableAccountRequest, response: DisableAccountResponse },
    changePassword: { id: 4, name: "ChangePassword", request: ChangePasswordRequest, response: ChangePasswordResponse },
    testCapability: { id: 5, name: "TestCapability", request: TestCapabilityRequest, response: TestCapabilityResponse },
    getName: { id: 6, name: "GetName", request: GetNameRequest, response: GetNameResponse },
    getAccountData: { id: 7, name: "GetAccountData", request: GetAccountDataRequest, response: GetAccountDataResponse },
    getPrivateData: { id: 8, name: "GetPrivateData", request: GetPrivateDataRequest, response: GetPrivateDataResponse },
    getPublicData: { id: 9, name: "GetPublicData", request: GetPublicDataRequest, response: GetPublicDataResponse },
    getMultiplePublicData: { id: 10, name: "GetMultiplePublicData", request: GetMultiplePublicDataRequest, response: GetMultiplePublicDataResponse },
    updateAccountName: { id: 11, name: "UpdateAccountName", request: UpdateAccountNameRequest, response: UpdateAccountNameResponse },
    updateAccountEmail: { id: 12, name: "UpdateAccountEmail", request: UpdateAccountEmailRequest, response: UpdateAccountEmailResponse },
    updateCustomData: { id: 13, name: "UpdateCustomData", request: UpdateCustomDataRequest, response: UpdateCustomDataResponse },
    findByNameRegex: { id: 14, name: "FindByNameRegex", request: FindByNameRegexRequest, response: FindByNameRegexResponse },
    updateAccountExpiryDate: { id: 15, name: "UpdateAccountExpiryDate", request: UpdateAccountExpiryDateRequest, response: UpdateAccountExpiryDateResponse },
    updateAccountEffectiveDate: { id: 16, name: "UpdateAccountEffectiveDate", request: UpdateAccountEffectiveDateRequest, response: UpdateAccountEffectiveDateResponse },
    updateStatus: { id: 17, name: "UpdateStatus", request: UpdateStatusRequest, response: UpdateStatusResponse },
    getStatus: { id: 18, name: "GetStatus", request: GetStatusRequest, response: GetStatusResponse },
    getLastConnectionStats: { id: 19, name: "GetLastConnectionStats", request: GetLastConnectionStatsRequest, response: GetLastConnectionStatsResponse },
    resetPassword: { id: 20, name: "ResetPassword", request: ResetPasswordRequest, response: ResetPasswordResponse },
    createAccountWithCustomData: { id: 21, name: "CreateAccountWithCustomData", request: CreateAccountWithCustomDataRequest, response: CreateAccountWithCustomDataResponse },
    retrieveAccount: { id: 22, name: "RetrieveAccount", request: RetrieveAccountRequest, response: RetrieveAccountResponse },
    updateAccount: { id: 23, name: "UpdateAccount", request: UpdateAccountRequest, response: UpdateAccountResponse },
    changePasswordByGuest: { id: 24, name: "ChangePasswordByGuest", request: ChangePasswordByGuestRequest, response: ChangePasswordByGuestResponse },
    findByNameLike: { id: 25, name: "FindByNameLike", request: FindByNameLikeRequest, response: FindByNameLikeResponse },
    customCreateAccount: { id: 26, name: "CustomCreateAccount", request: CustomCreateAccountRequest, response: CustomCreateAccountResponse },
    lookupOrCreateAccount: { id: 27, name: "LookupOrCreateAccount", request: LookupOrCreateAccountRequest, response: LookupOrCreateAccountResponse },
    createAccountEx: { id: 28, name: "CreateAccountEx", request: CreateAccountExRequest, response: CreateAccountExResponse },
    disconnectPrincipal: { id: 29, name: "DisconnectPrincipal", request: DisconnectPrincipalRequest, response: DisconnectPrincipalResponse },
    disconnectAllPrincipals: { id: 30, name: "DisconnectAllPrincipals", request: DisconnectAllPrincipalsRequest, response: DisconnectAllPrincipalsResponse },
  },
});
