// AUTOGENERATED by scripts/generate-protocols.ts from ddl/AccountManagementService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface AccountData {
  pid: number;
  strName: string;
  uiGroups: number;
  strEmail: string;
  dtCreationDate: bigint;
  dtEffectiveDate: bigint;
  strNotEffectiveMsg: string;
  dtExpiryDate: bigint;
  strExpiredMsg: string;
}
export const AccountData: c.Codec<AccountData> = c.struct({
  pid: c.u32,
  strName: c.string,
  uiGroups: c.u32,
  strEmail: c.string,
  dtCreationDate: q.dateTime,
  dtEffectiveDate: q.dateTime,
  strNotEffectiveMsg: c.string,
  dtExpiryDate: q.dateTime,
  strExpiredMsg: c.string,
});

export interface BasicAccountInfo {
  pidOwner: number;
  strName: string;
}
export const BasicAccountInfo: c.Codec<BasicAccountInfo> = c.struct({
  pidOwner: c.u32,
  strName: c.string,
});

export interface PublicData {}
export const PublicData: c.Codec<PublicData> = c.struct({});

export interface PrivateData {}
export const PrivateData: c.Codec<PrivateData> = c.struct({});
