// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UbiAccountManagementService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface ExternalAccount {
  accountType: number;
  id: string;
  username: string;
}
export const ExternalAccount: c.Codec<ExternalAccount> = c.struct({
  accountType: c.u32,
  id: c.string,
  username: c.string,
});

export interface UbiAccountStatus {
  basicStatus: number;
  missingRequiredInformations: boolean;
  recoveringPassword: boolean;
  pendingDeactivation: boolean;
}
export const UbiAccountStatus: c.Codec<UbiAccountStatus> = c.struct({
  basicStatus: c.u32,
  missingRequiredInformations: c.bool,
  recoveringPassword: c.bool,
  pendingDeactivation: c.bool,
});

export interface UbiAccount {
  ubiAccountId: string;
  username: string;
  password: string;
  status: UbiAccountStatus;
  email: string;
  dateOfBirth: bigint;
  gender: number;
  countryCode: string;
  optIn: boolean;
  thirdPartyOptIn: boolean;
  firstName: string;
  lastName: string;
  preferredLanguage: string;
  externalAccounts: ExternalAccount[];
}
export const UbiAccount: c.Codec<UbiAccount> = c.struct({
  ubiAccountId: c.string,
  username: c.string,
  password: c.string,
  status: UbiAccountStatus,
  email: c.string,
  dateOfBirth: q.dateTime,
  gender: c.u32,
  countryCode: c.string,
  optIn: c.bool,
  thirdPartyOptIn: c.bool,
  firstName: c.string,
  lastName: c.string,
  preferredLanguage: c.string,
  externalAccounts: c.list(ExternalAccount),
});

export interface TOS {
  localeCode: string;
  content: string;
  storingInfoQuestion: string;
}
export const TOS: c.Codec<TOS> = c.struct({
  localeCode: c.string,
  content: c.string,
  storingInfoQuestion: c.string,
});

export interface TOSEx {
  localeCode: string;
  contents: string[];
  storingInfoQuestion: string;
}
export const TOSEx: c.Codec<TOSEx> = c.struct({
  localeCode: c.string,
  contents: c.list(c.string),
  storingInfoQuestion: c.string,
});

export interface ValidationFailureReason {
  validationId: number;
  description: string;
}
export const ValidationFailureReason: c.Codec<ValidationFailureReason> = c.struct({
  validationId: c.u32,
  description: c.string,
});

export interface UsernameValidation {
  suggestions: string[];
  reasons: ValidationFailureReason[];
}
export const UsernameValidation: c.Codec<UsernameValidation> = c.struct({
  suggestions: c.list(c.string),
  reasons: c.list(ValidationFailureReason),
});

export interface Country {
  code: string;
  name: string;
}
export const Country: c.Codec<Country> = c.struct({
  code: c.string,
  name: c.string,
});
