// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UbiAccountManagementService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { Country, TOS, TOSEx, UbiAccount, UsernameValidation, ValidationFailureReason } from "./types";

export interface CreateAccountRequest {}
export const CreateAccountRequest: c.Codec<CreateAccountRequest> = c.struct({});

export interface CreateAccountResponse {
  ubiAccount: UbiAccount;
  failedReasons: ValidationFailureReason[];
}
export const CreateAccountResponse: c.Codec<CreateAccountResponse> = c.struct({
  ubiAccount: UbiAccount,
  failedReasons: c.list(ValidationFailureReason),
});

export interface UpdateAccountRequest {}
export const UpdateAccountRequest: c.Codec<UpdateAccountRequest> = c.struct({});

export interface UpdateAccountResponse {
  ubiAccount: UbiAccount;
  failedReasons: ValidationFailureReason[];
}
export const UpdateAccountResponse: c.Codec<UpdateAccountResponse> = c.struct({
  ubiAccount: UbiAccount,
  failedReasons: c.list(ValidationFailureReason),
});

export interface GetAccountRequest {}
export const GetAccountRequest: c.Codec<GetAccountRequest> = c.struct({});

export interface GetAccountResponse {
  ubiAccount: UbiAccount;
  exists: boolean;
}
export const GetAccountResponse: c.Codec<GetAccountResponse> = c.struct({
  ubiAccount: UbiAccount,
  exists: c.bool,
});

export interface LinkAccountRequest {
  ubiAccountUsername: string;
  ubiAccountPassword: string;
}
export const LinkAccountRequest: c.Codec<LinkAccountRequest> = c.struct({
  ubiAccountUsername: c.string,
  ubiAccountPassword: c.string,
});

export interface LinkAccountResponse {}
export const LinkAccountResponse: c.Codec<LinkAccountResponse> = c.struct({});

export interface GetTosRequest {
  countryCode: string;
  languageCode: string;
  htmlVersion: boolean;
}
export const GetTosRequest: c.Codec<GetTosRequest> = c.struct({
  countryCode: c.string,
  languageCode: c.string,
  htmlVersion: c.bool,
});

export interface GetTosResponse {
  tos: TOS;
}
export const GetTosResponse: c.Codec<GetTosResponse> = c.struct({
  tos: TOS,
});

export interface ValidateUsernameRequest {
  username: string;
}
export const ValidateUsernameRequest: c.Codec<ValidateUsernameRequest> = c.struct({
  username: c.string,
});

export interface ValidateUsernameResponse {
  usernameValidation: UsernameValidation;
}
export const ValidateUsernameResponse: c.Codec<ValidateUsernameResponse> = c.struct({
  usernameValidation: UsernameValidation,
});

export interface ValidatePasswordRequest {
  password: string;
  username: string;
}
export const ValidatePasswordRequest: c.Codec<ValidatePasswordRequest> = c.struct({
  password: c.string,
  username: c.string,
});

export interface ValidatePasswordResponse {
  failedReasons: ValidationFailureReason[];
}
export const ValidatePasswordResponse: c.Codec<ValidatePasswordResponse> = c.struct({
  failedReasons: c.list(ValidationFailureReason),
});

export interface ValidateEmailRequest {
  email: string;
}
export const ValidateEmailRequest: c.Codec<ValidateEmailRequest> = c.struct({
  email: c.string,
});

export interface ValidateEmailResponse {
  failedReasons: ValidationFailureReason[];
}
export const ValidateEmailResponse: c.Codec<ValidateEmailResponse> = c.struct({
  failedReasons: c.list(ValidationFailureReason),
});

export interface GetCountryListRequest {
  languageCode: string;
}
export const GetCountryListRequest: c.Codec<GetCountryListRequest> = c.struct({
  languageCode: c.string,
});

export interface GetCountryListResponse {
  countries: Country[];
}
export const GetCountryListResponse: c.Codec<GetCountryListResponse> = c.struct({
  countries: c.list(Country),
});

export interface ForgetPasswordRequest {
  usernameOrEmail: string;
}
export const ForgetPasswordRequest: c.Codec<ForgetPasswordRequest> = c.struct({
  usernameOrEmail: c.string,
});

export interface ForgetPasswordResponse {}
export const ForgetPasswordResponse: c.Codec<ForgetPasswordResponse> = c.struct({});

export interface LookupPrincipalIdsRequest {
  ubiAccountIds: string[];
}
export const LookupPrincipalIdsRequest: c.Codec<LookupPrincipalIdsRequest> = c.struct({
  ubiAccountIds: c.list(c.string),
});

export interface LookupPrincipalIdsResponse {
  pids: Map<string, number>;
}
export const LookupPrincipalIdsResponse: c.Codec<LookupPrincipalIdsResponse> = c.struct({
  pids: c.map(c.string, c.u32),
});

export interface LookupUbiAccountIdsByPidsRequest {
  pids: number[];
}
export const LookupUbiAccountIdsByPidsRequest: c.Codec<LookupUbiAccountIdsByPidsRequest> = c.struct({
  pids: c.list(c.u32),
});

export interface LookupUbiAccountIdsByPidsResponse {
  ubiaccountIds: Map<number, string>;
}
export const LookupUbiAccountIdsByPidsResponse: c.Codec<LookupUbiAccountIdsByPidsResponse> = c.struct({
  ubiaccountIds: c.map(c.u32, c.string),
});

export interface LookupUbiAccountIdsByUsernamesRequest {
  usernames: string[];
}
export const LookupUbiAccountIdsByUsernamesRequest: c.Codec<LookupUbiAccountIdsByUsernamesRequest> = c.struct({
  usernames: c.list(c.string),
});

export interface LookupUbiAccountIdsByUsernamesResponse {
  ubiAccountIds: Map<string, string>;
}
export const LookupUbiAccountIdsByUsernamesResponse: c.Codec<LookupUbiAccountIdsByUsernamesResponse> = c.struct({
  ubiAccountIds: c.map(c.string, c.string),
});

export interface LookupUsernamesByUbiAccountIdsRequest {
  ubiAccountIds: string[];
}
export const LookupUsernamesByUbiAccountIdsRequest: c.Codec<LookupUsernamesByUbiAccountIdsRequest> = c.struct({
  ubiAccountIds: c.list(c.string),
});

export interface LookupUsernamesByUbiAccountIdsResponse {
  usernames: Map<string, string>;
}
export const LookupUsernamesByUbiAccountIdsResponse: c.Codec<LookupUsernamesByUbiAccountIdsResponse> = c.struct({
  usernames: c.map(c.string, c.string),
});

export interface LookupUbiAccountIdsByUsernameSubStringRequest {
  usernameSubString: string;
}
export const LookupUbiAccountIdsByUsernameSubStringRequest: c.Codec<LookupUbiAccountIdsByUsernameSubStringRequest> = c.struct({
  usernameSubString: c.string,
});

export interface LookupUbiAccountIdsByUsernameSubStringResponse {
  ubiAccountIds: Map<string, string>;
}
export const LookupUbiAccountIdsByUsernameSubStringResponse: c.Codec<LookupUbiAccountIdsByUsernameSubStringResponse> = c.struct({
  ubiAccountIds: c.map(c.string, c.string),
});

export interface UserHasPlayedRequest {
  ubiAccountIds: string[];
}
export const UserHasPlayedRequest: c.Codec<UserHasPlayedRequest> = c.struct({
  ubiAccountIds: c.list(c.string),
});

export interface UserHasPlayedResponse {
  userPresence: Map<string, boolean>;
}
export const UserHasPlayedResponse: c.Codec<UserHasPlayedResponse> = c.struct({
  userPresence: c.map(c.string, c.bool),
});

export interface IsUserPlayingRequest {
  ubiAccountIds: string[];
}
export const IsUserPlayingRequest: c.Codec<IsUserPlayingRequest> = c.struct({
  ubiAccountIds: c.list(c.string),
});

export interface IsUserPlayingResponse {
  userPresence: Map<string, boolean>;
}
export const IsUserPlayingResponse: c.Codec<IsUserPlayingResponse> = c.struct({
  userPresence: c.map(c.string, c.bool),
});

export interface LookupUbiAccountIdsByUsernamesGlobalRequest {
  usernames: string[];
}
export const LookupUbiAccountIdsByUsernamesGlobalRequest: c.Codec<LookupUbiAccountIdsByUsernamesGlobalRequest> = c.struct({
  usernames: c.list(c.string),
});

export interface LookupUbiAccountIdsByUsernamesGlobalResponse {
  ubiAccountIds: Map<string, string>;
}
export const LookupUbiAccountIdsByUsernamesGlobalResponse: c.Codec<LookupUbiAccountIdsByUsernamesGlobalResponse> = c.struct({
  ubiAccountIds: c.map(c.string, c.string),
});

export interface LookupUbiAccountIdsByEmailsGlobalRequest {
  emails: string[];
}
export const LookupUbiAccountIdsByEmailsGlobalRequest: c.Codec<LookupUbiAccountIdsByEmailsGlobalRequest> = c.struct({
  emails: c.list(c.string),
});

export interface LookupUbiAccountIdsByEmailsGlobalResponse {
  ubiAccountIds: Map<string, string>;
}
export const LookupUbiAccountIdsByEmailsGlobalResponse: c.Codec<LookupUbiAccountIdsByEmailsGlobalResponse> = c.struct({
  ubiAccountIds: c.map(c.string, c.string),
});

export interface LookupUsernamesByUbiAccountIdsGlobalRequest {
  ubiAccountIds: string[];
}
export const LookupUsernamesByUbiAccountIdsGlobalRequest: c.Codec<LookupUsernamesByUbiAccountIdsGlobalRequest> = c.struct({
  ubiAccountIds: c.list(c.string),
});

export interface LookupUsernamesByUbiAccountIdsGlobalResponse {
  usernames: Map<string, string>;
}
export const LookupUsernamesByUbiAccountIdsGlobalResponse: c.Codec<LookupUsernamesByUbiAccountIdsGlobalResponse> = c.struct({
  usernames: c.map(c.string, c.string),
});

export interface GetTosExRequest {
  countryCode: string;
  languageCode: string;
  htmlVersion: boolean;
}
export const GetTosExRequest: c.Codec<GetTosExRequest> = c.struct({
  countryCode: c.string,
  languageCode: c.string,
  htmlVersion: c.bool,
});

export interface GetTosExResponse {
  tosex: TOSEx;
}
export const GetTosExResponse: c.Codec<GetTosExResponse> = c.struct({
  tosex: TOSEx,
});

export interface HasAcceptedLatestTosRequest {}
export const HasAcceptedLatestTosRequest: c.Codec<HasAcceptedLatestTosRequest> = c.struct({});

export interface HasAcceptedLatestTosResponse {
  hasAccepted: boolean;
  failedReasons: ValidationFailureReason[];
}
export const HasAcceptedLatestTosResponse: c.Codec<HasAcceptedLatestTosResponse> = c.struct({
  hasAccepted: c.bool,
  failedReasons: c.list(ValidationFailureReason),
});

export interface AcceptLatestTosRequest {}
export const AcceptLatestTosRequest: c.Codec<AcceptLatestTosRequest> = c.struct({});

export interface AcceptLatestTosResponse {
  failedReasons: ValidationFailureReason[];
}
export const AcceptLatestTosResponse: c.Codec<AcceptLatestTosResponse> = c.struct({
  failedReasons: c.list(ValidationFailureReason),
});

export const UbiAccountManagementProtocol = defineProtocol({
  id: 29,
  name: "UbiAccountManagementProtocol",
  methods: {
    createAccount: { id: 1, name: "CreateAccount", request: CreateAccountRequest, response: CreateAccountResponse },
    updateAccount: { id: 2, name: "UpdateAccount", request: UpdateAccountRequest, response: UpdateAccountResponse },
    getAccount: { id: 3, name: "GetAccount", request: GetAccountRequest, response: GetAccountResponse },
    linkAccount: { id: 4, name: "LinkAccount", request: LinkAccountRequest, response: LinkAccountResponse },
    getTos: { id: 5, name: "GetTOS", request: GetTosRequest, response: GetTosResponse },
    validateUsername: { id: 6, name: "ValidateUsername", request: ValidateUsernameRequest, response: ValidateUsernameResponse },
    validatePassword: { id: 7, name: "ValidatePassword", request: ValidatePasswordRequest, response: ValidatePasswordResponse },
    validateEmail: { id: 8, name: "ValidateEmail", request: ValidateEmailRequest, response: ValidateEmailResponse },
    getCountryList: { id: 9, name: "GetCountryList", request: GetCountryListRequest, response: GetCountryListResponse },
    forgetPassword: { id: 10, name: "ForgetPassword", request: ForgetPasswordRequest, response: ForgetPasswordResponse },
    lookupPrincipalIds: { id: 11, name: "LookupPrincipalIds", request: LookupPrincipalIdsRequest, response: LookupPrincipalIdsResponse },
    lookupUbiAccountIdsByPids: { id: 12, name: "LookupUbiAccountIDsByPids", request: LookupUbiAccountIdsByPidsRequest, response: LookupUbiAccountIdsByPidsResponse },
    lookupUbiAccountIdsByUsernames: { id: 13, name: "LookupUbiAccountIDsByUsernames", request: LookupUbiAccountIdsByUsernamesRequest, response: LookupUbiAccountIdsByUsernamesResponse },
    lookupUsernamesByUbiAccountIds: { id: 14, name: "LookupUsernamesByUbiAccountIDs", request: LookupUsernamesByUbiAccountIdsRequest, response: LookupUsernamesByUbiAccountIdsResponse },
    lookupUbiAccountIdsByUsernameSubString: { id: 15, name: "LookupUbiAccountIDsByUsernameSubString", request: LookupUbiAccountIdsByUsernameSubStringRequest, response: LookupUbiAccountIdsByUsernameSubStringResponse },
    userHasPlayed: { id: 16, name: "UserHasPlayed", request: UserHasPlayedRequest, response: UserHasPlayedResponse },
    isUserPlaying: { id: 17, name: "IsUserPlaying", request: IsUserPlayingRequest, response: IsUserPlayingResponse },
    lookupUbiAccountIdsByUsernamesGlobal: { id: 18, name: "LookupUbiAccountIDsByUsernamesGlobal", request: LookupUbiAccountIdsByUsernamesGlobalRequest, response: LookupUbiAccountIdsByUsernamesGlobalResponse },
    lookupUbiAccountIdsByEmailsGlobal: { id: 19, name: "LookupUbiAccountIDsByEmailsGlobal", request: LookupUbiAccountIdsByEmailsGlobalRequest, response: LookupUbiAccountIdsByEmailsGlobalResponse },
    lookupUsernamesByUbiAccountIdsGlobal: { id: 20, name: "LookupUsernamesByUbiAccountIDsGlobal", request: LookupUsernamesByUbiAccountIdsGlobalRequest, response: LookupUsernamesByUbiAccountIdsGlobalResponse },
    getTosEx: { id: 21, name: "GetTOSEx", request: GetTosExRequest, response: GetTosExResponse },
    hasAcceptedLatestTos: { id: 22, name: "HasAcceptedLatestTOS", request: HasAcceptedLatestTosRequest, response: HasAcceptedLatestTosResponse },
    acceptLatestTos: { id: 23, name: "AcceptLatestTOS", request: AcceptLatestTosRequest, response: AcceptLatestTosResponse },
  },
});
