// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UplayWinService.json. Do not edit.
import * as c from "../../quazal/codec";

export interface UplayActionPlatform {
  platformCode: string;
  completed: boolean;
  specificKey: string;
}
export const UplayActionPlatform: c.Codec<UplayActionPlatform> = c.struct({
  platformCode: c.string,
  completed: c.bool,
  specificKey: c.string,
});

export interface UplayRewardPlatform {
  platformCode: string;
  purchased: boolean;
}
export const UplayRewardPlatform: c.Codec<UplayRewardPlatform> = c.struct({
  platformCode: c.string,
  purchased: c.bool,
});

export interface UplayAction {
  code: string;
  name: string;
  description: string;
  value: number;
  gameCode: string;
  platforms: UplayActionPlatform[];
}
export const UplayAction: c.Codec<UplayAction> = c.struct({
  code: c.string,
  name: c.string,
  description: c.string,
  value: c.i32,
  gameCode: c.string,
  platforms: c.list(UplayActionPlatform),
});

export interface UplayReward {
  code: string;
  name: string;
  description: string;
  value: number;
  rewardTypeName: string;
  gameCode: string;
  platforms: UplayRewardPlatform[];
}
export const UplayReward: c.Codec<UplayReward> = c.struct({
  code: c.string,
  name: c.string,
  description: c.string,
  value: c.i32,
  rewardTypeName: c.string,
  gameCode: c.string,
  platforms: c.list(UplayRewardPlatform),
});

export interface UplaySectionContentLocalized {
  key: string;
  culture: string;
  text: string;
  url: string;
  duration: number;
  size: string;
  width: string;
  height: string;
}
export const UplaySectionContentLocalized: c.Codec<UplaySectionContentLocalized> = c.struct({
  key: c.string,
  culture: c.string,
  text: c.string,
  url: c.string,
  duration: c.i32,
  size: c.string,
  width: c.string,
  height: c.string,
});

export interface UplaySectionContent {
  key: string;
  name: string;
  order: number;
  typeName: string;
  localizedInfo: UplaySectionContentLocalized;
}
export const UplaySectionContent: c.Codec<UplaySectionContent> = c.struct({
  key: c.string,
  name: c.string,
  order: c.i16,
  typeName: c.string,
  localizedInfo: UplaySectionContentLocalized,
});

export interface UplaySection {
  key: string;
  name: string;
  typeName: string;
  menuTypeName: string;
  contentList: UplaySectionContent[];
  gameCode: string;
  platformCode: string;
}
export const UplaySection: c.Codec<UplaySection> = c.struct({
  key: c.string,
  name: c.string,
  typeName: c.string,
  menuTypeName: c.string,
  contentList: c.list(UplaySectionContent),
  gameCode: c.string,
  platformCode: c.string,
});
