// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UplayWinService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { UplayAction, UplayReward, UplaySection } from "./types";

export interface GetActionsRequest {
  startRowIndex: number;
  maximumRows: number;
  sortExpression: string;
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const GetActionsRequest: c.Codec<GetActionsRequest> = c.struct({
  startRowIndex: c.i32,
  maximumRows: c.i32,
  sortExpression: c.string,
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetActionsResponse {
  actionList: UplayAction[];
}
export const GetActionsResponse: c.Codec<GetActionsResponse> = c.struct({
  actionList: c.list(UplayAction),
});

export interface GetActionsCompletedRequest {
  startRowIndex: number;
  maximumRows: number;
  sortExpression: string;
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const GetActionsCompletedRequest: c.Codec<GetActionsCompletedRequest> = c.struct({
  startRowIndex: c.i32,
  maximumRows: c.i32,
  sortExpression: c.string,
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetActionsCompletedResponse {
  actionList: UplayAction[];
}
export const GetActionsCompletedResponse: c.Codec<GetActionsCompletedResponse> = c.struct({
  actionList: c.list(UplayAction),
});

export interface GetActionsCountRequest {
  platformCode: string;
  gameCode: string;
}
export const GetActionsCountRequest: c.Codec<GetActionsCountRequest> = c.struct({
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetActionsCountResponse {
  actionsCount: number;
}
export const GetActionsCountResponse: c.Codec<GetActionsCountResponse> = c.struct({
  actionsCount: c.i32,
});

export interface GetActionsCompletedCountRequest {
  platformCode: string;
  gameCode: string;
}
export const GetActionsCompletedCountRequest: c.Codec<GetActionsCompletedCountRequest> = c.struct({
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetActionsCompletedCountResponse {
  actionsCount: number;
}
export const GetActionsCompletedCountResponse: c.Codec<GetActionsCompletedCountResponse> = c.struct({
  actionsCount: c.i32,
});

export interface GetRewardsRequest {
  startRowIndex: number;
  maximumRows: number;
  sortExpression: string;
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const GetRewardsRequest: c.Codec<GetRewardsRequest> = c.struct({
  startRowIndex: c.i32,
  maximumRows: c.i32,
  sortExpression: c.string,
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetRewardsResponse {
  rewardList: UplayReward[];
}
export const GetRewardsResponse: c.Codec<GetRewardsResponse> = c.struct({
  rewardList: c.list(UplayReward),
});

export interface GetRewardsPurchasedRequest {
  startRowIndex: number;
  maximumRows: number;
  sortExpression: string;
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const GetRewardsPurchasedRequest: c.Codec<GetRewardsPurchasedRequest> = c.struct({
  startRowIndex: c.i32,
  maximumRows: c.i32,
  sortExpression: c.string,
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetRewardsPurchasedResponse {
  rewardList: UplayReward[];
}
export const GetRewardsPurchasedResponse: c.Codec<GetRewardsPurchasedResponse> = c.struct({
  rewardList: c.list(UplayReward),
});

export interface UplayWelcomeRequest {
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const UplayWelcomeRequest: c.Codec<UplayWelcomeRequest> = c.struct({
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface UplayWelcomeResponse {
  actionList: UplayAction[];
}
export const UplayWelcomeResponse: c.Codec<UplayWelcomeResponse> = c.struct({
  actionList: c.list(UplayAction),
});

export interface SetActionCompletedRequest {
  actionCode: string;
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const SetActionCompletedRequest: c.Codec<SetActionCompletedRequest> = c.struct({
  actionCode: c.string,
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface SetActionCompletedResponse {
  unlockedAction: UplayAction;
}
export const SetActionCompletedResponse: c.Codec<SetActionCompletedResponse> = c.struct({
  unlockedAction: UplayAction,
});

export interface SetActionsCompletedRequest {
  actionCodeList: string[];
  cultureName: string;
  platformCode: string;
  gameCode: string;
}
export const SetActionsCompletedRequest: c.Codec<SetActionsCompletedRequest> = c.struct({
  actionCodeList: c.list(c.string),
  cultureName: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface SetActionsCompletedResponse {
  actionList: UplayAction[];
}
export const SetActionsCompletedResponse: c.Codec<SetActionsCompletedResponse> = c.struct({
  actionList: c.list(UplayAction),
});

export interface GetUserTokenRequest {}
export const GetUserTokenRequest: c.Codec<GetUserTokenRequest> = c.struct({});

export interface GetUserTokenResponse {
  token: string;
}
export const GetUserTokenResponse: c.Codec<GetUserTokenResponse> = c.struct({
  token: c.string,
});

export interface GetVirtualCurrencyUserBalanceRequest {
  platformCode: string;
}
export const GetVirtualCurrencyUserBalanceRequest: c.Codec<GetVirtualCurrencyUserBalanceRequest> = c.struct({
  platformCode: c.string,
});

export interface GetVirtualCurrencyUserBalanceResponse {
  virtualCurrencyUserBalance: number;
}
export const GetVirtualCurrencyUserBalanceResponse: c.Codec<GetVirtualCurrencyUserBalanceResponse> = c.struct({
  virtualCurrencyUserBalance: c.i32,
});

export interface GetSectionsByKeyRequest {
  cultureName: string;
  sectionKey: string;
  platformCode: string;
  gameCode: string;
}
export const GetSectionsByKeyRequest: c.Codec<GetSectionsByKeyRequest> = c.struct({
  cultureName: c.string,
  sectionKey: c.string,
  platformCode: c.string,
  gameCode: c.string,
});

export interface GetSectionsByKeyResponse {
  sectionList: UplaySection[];
}
export const GetSectionsByKeyResponse: c.Codec<GetSectionsByKeyResponse> = c.struct({
  sectionList: c.list(UplaySection),
});

export interface BuyRewardRequest {
  rewardCode: string;
  platformCode: string;
}
export const BuyRewardRequest: c.Codec<BuyRewardRequest> = c.struct({
  rewardCode: c.string,
  platformCode: c.string,
});

export interface BuyRewardResponse {
  virtualCurrencyUserBalance: number;
}
export const BuyRewardResponse: c.Codec<BuyRewardResponse> = c.struct({
  virtualCurrencyUserBalance: c.i32,
});

export const UplayWinProtocol = defineProtocol({
  id: 49,
  name: "UplayWinProtocol",
  methods: {
    getActions: { id: 1, name: "GetActions", request: GetActionsRequest, response: GetActionsResponse },
    getActionsCompleted: { id: 2, name: "GetActionsCompleted", request: GetActionsCompletedRequest, response: GetActionsCompletedResponse },
    getActionsCount: { id: 3, name: "GetActionsCount", request: GetActionsCountRequest, response: GetActionsCountResponse },
    getActionsCompletedCount: { id: 4, name: "GetActionsCompletedCount", request: GetActionsCompletedCountRequest, response: GetActionsCompletedCountResponse },
    getRewards: { id: 5, name: "GetRewards", request: GetRewardsRequest, response: GetRewardsResponse },
    getRewardsPurchased: { id: 6, name: "GetRewardsPurchased", request: GetRewardsPurchasedRequest, response: GetRewardsPurchasedResponse },
    uplayWelcome: { id: 7, name: "UplayWelcome", request: UplayWelcomeRequest, response: UplayWelcomeResponse },
    setActionCompleted: { id: 8, name: "SetActionCompleted", request: SetActionCompletedRequest, response: SetActionCompletedResponse },
    setActionsCompleted: { id: 9, name: "SetActionsCompleted", request: SetActionsCompletedRequest, response: SetActionsCompletedResponse },
    getUserToken: { id: 10, name: "GetUserToken", request: GetUserTokenRequest, response: GetUserTokenResponse },
    getVirtualCurrencyUserBalance: { id: 11, name: "GetVirtualCurrencyUserBalance", request: GetVirtualCurrencyUserBalanceRequest, response: GetVirtualCurrencyUserBalanceResponse },
    getSectionsByKey: { id: 12, name: "GetSectionsByKey", request: GetSectionsByKeyRequest, response: GetSectionsByKeyResponse },
    buyReward: { id: 13, name: "BuyReward", request: BuyRewardRequest, response: BuyRewardResponse },
  },
});
