// AUTOGENERATED by scripts/generate-protocols.ts from ddl/HealthService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface PingDaemonRequest {}
export const PingDaemonRequest: c.Codec<PingDaemonRequest> = c.struct({});

export interface PingDaemonResponse {
  returnValue: boolean;
}
export const PingDaemonResponse: c.Codec<PingDaemonResponse> = c.struct({
  returnValue: c.bool,
});

export interface PingDatabaseRequest {}
export const PingDatabaseRequest: c.Codec<PingDatabaseRequest> = c.struct({});

export interface PingDatabaseResponse {
  returnValue: boolean;
}
export const PingDatabaseResponse: c.Codec<PingDatabaseResponse> = c.struct({
  returnValue: c.bool,
});

export interface RunSanityCheckRequest {}
export const RunSanityCheckRequest: c.Codec<RunSanityCheckRequest> = c.struct({});

export interface RunSanityCheckResponse {
  returnValue: boolean;
}
export const RunSanityCheckResponse: c.Codec<RunSanityCheckResponse> = c.struct({
  returnValue: c.bool,
});

export interface FixSanityErrorsRequest {}
export const FixSanityErrorsRequest: c.Codec<FixSanityErrorsRequest> = c.struct({});

export interface FixSanityErrorsResponse {
  returnValue: boolean;
}
export const FixSanityErrorsResponse: c.Codec<FixSanityErrorsResponse> = c.struct({
  returnValue: c.bool,
});

export const HealthProtocol = defineProtocol({
  id: 18,
  name: "HealthProtocol",
  methods: {
    pingDaemon: { id: 1, name: "PingDaemon", request: PingDaemonRequest, response: PingDaemonResponse },
    pingDatabase: { id: 2, name: "PingDatabase", request: PingDatabaseRequest, response: PingDatabaseResponse },
    runSanityCheck: { id: 3, name: "RunSanityCheck", request: RunSanityCheckRequest, response: RunSanityCheckResponse },
    fixSanityErrors: { id: 4, name: "FixSanityErrors", request: FixSanityErrorsRequest, response: FixSanityErrorsResponse },
  },
});
