// AUTOGENERATED by scripts/generate-protocols.ts from ddl/HealthService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface PingDaemonRequest {}
export const PingDaemonRequest: c.Codec<PingDaemonRequest> = c.struct({});

export interface PingDaemonResponse {
  returnValue: boolean;
}
export const PingDaemonResponse: c.Codec<PingDaemonResponse> = c.struct({
  returnValue: c.bool,
});

export interface GetClusterMembersRequest {}
export const GetClusterMembersRequest: c.Codec<GetClusterMembersRequest> = c.struct({});

export interface GetClusterMembersResponse {
  strValues: string[];
}
export const GetClusterMembersResponse: c.Codec<GetClusterMembersResponse> = c.struct({
  strValues: c.list(c.string),
});

export const MonitoringProtocol = defineProtocol({
  id: 19,
  name: "MonitoringProtocol",
  methods: {
    pingDaemon: { id: 1, name: "PingDaemon", request: PingDaemonRequest, response: PingDaemonResponse },
    getClusterMembers: { id: 2, name: "GetClusterMembers", request: GetClusterMembersRequest, response: GetClusterMembersResponse },
  },
});
