// AUTOGENERATED by scripts/generate-protocols.ts from ddl/AuthenticationFoundation.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { RVConnectionData } from "./types";

export interface LoginRequest {
  strUserName: string;
}
export const LoginRequest: c.Codec<LoginRequest> = c.struct({
  strUserName: c.string,
});

export interface LoginResponse {
  returnValue: number;
  pidPrincipal: number;
  pbufResponse: Buffer;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginResponse: c.Codec<LoginResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pbufResponse: c.buffer,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginExRequest {
  strUserName: string;
  oExtraData: q.AnyData;
}
export const LoginExRequest: c.Codec<LoginExRequest> = c.struct({
  strUserName: c.string,
  oExtraData: q.anyData,
});

export interface LoginExResponse {
  returnValue: number;
  pidPrincipal: number;
  pbufResponse: Buffer;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginExResponse: c.Codec<LoginExResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pbufResponse: c.buffer,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface RequestTicketRequest {
  idSource: number;
  idTarget: number;
}
export const RequestTicketRequest: c.Codec<RequestTicketRequest> = c.struct({
  idSource: c.u32,
  idTarget: c.u32,
});

export interface RequestTicketResponse {
  returnValue: number;
  bufResponse: Buffer;
}
export const RequestTicketResponse: c.Codec<RequestTicketResponse> = c.struct({
  returnValue: q.qresult,
  bufResponse: c.buffer,
});

export interface GetPidRequest {
  strUserName: string;
}
export const GetPidRequest: c.Codec<GetPidRequest> = c.struct({
  strUserName: c.string,
});

export interface GetPidResponse {
  returnValue: number;
}
export const GetPidResponse: c.Codec<GetPidResponse> = c.struct({
  returnValue: c.u32,
});

export interface GetNameRequest {
  id: number;
}
export const GetNameRequest: c.Codec<GetNameRequest> = c.struct({
  id: c.u32,
});

export interface GetNameResponse {
  returnValue: string;
}
export const GetNameResponse: c.Codec<GetNameResponse> = c.struct({
  returnValue: c.string,
});

export interface LoginWithContextRequest {
  loginData: q.AnyData;
}
export const LoginWithContextRequest: c.Codec<LoginWithContextRequest> = c.struct({
  loginData: q.anyData,
});

export interface LoginWithContextResponse {
  returnValue: number;
  pidPrincipal: number;
  pbufResponse: Buffer;
  pConnectionData: RVConnectionData;
}
export const LoginWithContextResponse: c.Codec<LoginWithContextResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pbufResponse: c.buffer,
  pConnectionData: RVConnectionData,
});

export const TicketGrantingProtocol = defineProtocol({
  id: 10,
  name: "TicketGrantingProtocol",
  methods: {
    login: { id: 1, name: "Login", request: LoginRequest, response: LoginResponse },
    loginEx: { id: 2, name: "LoginEx", request: LoginExRequest, response: LoginExResponse },
    requestTicket: { id: 3, name: "RequestTicket", request: RequestTicketRequest, response: RequestTicketResponse },
    getPid: { id: 4, name: "GetPID", request: GetPidRequest, response: GetPidResponse },
    getName: { id: 5, name: "GetName", request: GetNameRequest, response: GetNameResponse },
    loginWithContext: { id: 6, name: "LoginWithContext", request: LoginWithContextRequest, response: LoginWithContextResponse },
  },
});
