// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UbiAuthentication.json. Do not edit.
import * as c from "../../quazal/codec";

export interface UbiAuthenticationLoginCustomData {
  userName: string;
  onlineKey: string;
  password: string;
}
export const UbiAuthenticationLoginCustomData: c.Codec<UbiAuthenticationLoginCustomData> = c.struct({
  userName: c.string,
  onlineKey: c.string,
  password: c.string,
});
