// AUTOGENERATED by scripts/generate-protocols.ts from ddl/NewsService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { NewsChannel, NewsHeader, NewsMessage, NewsRecipient } from "./types";

export interface GetChannelsRequest {
  resultRange: q.ResultRange;
}
export const GetChannelsRequest: c.Codec<GetChannelsRequest> = c.struct({
  resultRange: q.ResultRange,
});

export interface GetChannelsResponse {
  channels: NewsChannel[];
}
export const GetChannelsResponse: c.Codec<GetChannelsResponse> = c.struct({
  channels: c.list(NewsChannel),
});

export interface GetChannelsByTypesRequest {
  newsChannelTypes: string[];
  resultRange: q.ResultRange;
}
export const GetChannelsByTypesRequest: c.Codec<GetChannelsByTypesRequest> = c.struct({
  newsChannelTypes: c.list(c.string),
  resultRange: q.ResultRange,
});

export interface GetChannelsByTypesResponse {
  channels: NewsChannel[];
}
export const GetChannelsByTypesResponse: c.Codec<GetChannelsByTypesResponse> = c.struct({
  channels: c.list(NewsChannel),
});

export interface GetSubscribableChannelsRequest {
  resultRange: q.ResultRange;
}
export const GetSubscribableChannelsRequest: c.Codec<GetSubscribableChannelsRequest> = c.struct({
  resultRange: q.ResultRange,
});

export interface GetSubscribableChannelsResponse {
  channels: NewsChannel[];
}
export const GetSubscribableChannelsResponse: c.Codec<GetSubscribableChannelsResponse> = c.struct({
  channels: c.list(NewsChannel),
});

export interface GetChannelsByIdsRequest {
  newsChannelIds: number[];
}
export const GetChannelsByIdsRequest: c.Codec<GetChannelsByIdsRequest> = c.struct({
  newsChannelIds: c.list(c.u32),
});

export interface GetChannelsByIdsResponse {
  channels: NewsChannel[];
}
export const GetChannelsByIdsResponse: c.Codec<GetChannelsByIdsResponse> = c.struct({
  channels: c.list(NewsChannel),
});

export interface GetSubscribedChannelsRequest {
  resultRange: q.ResultRange;
}
export const GetSubscribedChannelsRequest: c.Codec<GetSubscribedChannelsRequest> = c.struct({
  resultRange: q.ResultRange,
});

export interface GetSubscribedChannelsResponse {
  channels: NewsChannel[];
}
export const GetSubscribedChannelsResponse: c.Codec<GetSubscribedChannelsResponse> = c.struct({
  channels: c.list(NewsChannel),
});

export interface SubscribeChannelRequest {
  newsChannelId: number;
}
export const SubscribeChannelRequest: c.Codec<SubscribeChannelRequest> = c.struct({
  newsChannelId: c.u32,
});

export interface SubscribeChannelResponse {}
export const SubscribeChannelResponse: c.Codec<SubscribeChannelResponse> = c.struct({});

export interface UnsubscribeChannelRequest {
  newsChannelId: number;
}
export const UnsubscribeChannelRequest: c.Codec<UnsubscribeChannelRequest> = c.struct({
  newsChannelId: c.u32,
});

export interface UnsubscribeChannelResponse {}
export const UnsubscribeChannelResponse: c.Codec<UnsubscribeChannelResponse> = c.struct({});

export interface GetNewsHeadersRequest {
  recipient: NewsRecipient;
  range: q.ResultRange;
}
export const GetNewsHeadersRequest: c.Codec<GetNewsHeadersRequest> = c.struct({
  recipient: NewsRecipient,
  range: q.ResultRange,
});

export interface GetNewsHeadersResponse {
  newsHeaders: NewsHeader[];
}
export const GetNewsHeadersResponse: c.Codec<GetNewsHeadersResponse> = c.struct({
  newsHeaders: c.list(NewsHeader),
});

export interface GetNewsMessagesRequest {
  newsMessageIds: number[];
}
export const GetNewsMessagesRequest: c.Codec<GetNewsMessagesRequest> = c.struct({
  newsMessageIds: c.list(c.u32),
});

export interface GetNewsMessagesResponse {
  newsMessages: NewsMessage[];
}
export const GetNewsMessagesResponse: c.Codec<GetNewsMessagesResponse> = c.struct({
  newsMessages: c.list(NewsMessage),
});

export interface GetNumberOfNewsRequest {
  recipient: NewsRecipient;
}
export const GetNumberOfNewsRequest: c.Codec<GetNumberOfNewsRequest> = c.struct({
  recipient: NewsRecipient,
});

export interface GetNumberOfNewsResponse {
  numberOfNews: number;
}
export const GetNumberOfNewsResponse: c.Codec<GetNumberOfNewsResponse> = c.struct({
  numberOfNews: c.u32,
});

export interface GetChannelByTypeRequest {
  newsChannelType: string;
}
export const GetChannelByTypeRequest: c.Codec<GetChannelByTypeRequest> = c.struct({
  newsChannelType: c.string,
});

export interface GetChannelByTypeResponse {
  channel: NewsChannel;
}
export const GetChannelByTypeResponse: c.Codec<GetChannelByTypeResponse> = c.struct({
  channel: NewsChannel,
});

export interface GetNewsHeadersByTypeRequest {
  newsChannelType: string;
  range: q.ResultRange;
}
export const GetNewsHeadersByTypeRequest: c.Codec<GetNewsHeadersByTypeRequest> = c.struct({
  newsChannelType: c.string,
  range: q.ResultRange,
});

export interface GetNewsHeadersByTypeResponse {
  newsHeaders: NewsHeader[];
}
export const GetNewsHeadersByTypeResponse: c.Codec<GetNewsHeadersByTypeResponse> = c.struct({
  newsHeaders: c.list(NewsHeader),
});

export interface GetNewsMessagesByTypeRequest {
  newsChannelType: string;
  range: q.ResultRange;
}
export const GetNewsMessagesByTypeRequest: c.Codec<GetNewsMessagesByTypeRequest> = c.struct({
  newsChannelType: c.string,
  range: q.ResultRange,
});

export interface GetNewsMessagesByTypeResponse {
  newsMessages: NewsMessage[];
}
export const GetNewsMessagesByTypeResponse: c.Codec<GetNewsMessagesByTypeResponse> = c.struct({
  newsMessages: c.list(NewsMessage),
});

export const NewsProtocol = defineProtocol({
  id: undefined,
  name: "NewsProtocol",
  methods: {
    getChannels: { id: 1, name: "GetChannels", request: GetChannelsRequest, response: GetChannelsResponse },
    getChannelsByTypes: { id: 2, name: "GetChannelsByTypes", request: GetChannelsByTypesRequest, response: GetChannelsByTypesResponse },
    getSubscribableChannels: { id: 3, name: "GetSubscribableChannels", request: GetSubscribableChannelsRequest, response: GetSubscribableChannelsResponse },
    getChannelsByIds: { id: 4, name: "GetChannelsByIDs", request: GetChannelsByIdsRequest, response: GetChannelsByIdsResponse },
    getSubscribedChannels: { id: 5, name: "GetSubscribedChannels", request: GetSubscribedChannelsRequest, response: GetSubscribedChannelsResponse },
    subscribeChannel: { id: 6, name: "SubscribeChannel", request: SubscribeChannelRequest, response: SubscribeChannelResponse },
    unsubscribeChannel: { id: 7, name: "UnsubscribeChannel", request: UnsubscribeChannelRequest, response: UnsubscribeChannelResponse },
    getNewsHeaders: { id: 8, name: "GetNewsHeaders", request: GetNewsHeadersRequest, response: GetNewsHeadersResponse },
    getNewsMessages: { id: 9, name: "GetNewsMessages", request: GetNewsMessagesRequest, response: GetNewsMessagesResponse },
    getNumberOfNews: { id: 10, name: "GetNumberOfNews", request: GetNumberOfNewsRequest, response: GetNumberOfNewsResponse },
    getChannelByType: { id: 11, name: "GetChannelByType", request: GetChannelByTypeRequest, response: GetChannelByTypeResponse },
    getNewsHeadersByType: { id: 12, name: "GetNewsHeadersByType", request: GetNewsHeadersByTypeRequest, response: GetNewsHeadersByTypeResponse },
    getNewsMessagesByType: { id: 13, name: "GetNewsMessagesByType", request: GetNewsMessagesByTypeRequest, response: GetNewsMessagesByTypeResponse },
  },
});
