// AUTOGENERATED by scripts/generate-protocols.ts from ddl/NewsService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface NewsChannel {
  id: number;
  ownerPid: number;
  name: string;
  description: string;
  creationTime: bigint;
  expirationTime: bigint;
  type: string;
  locale: string;
  subscribable: boolean;
}
export const NewsChannel: c.Codec<NewsChannel> = c.struct({
  id: c.u32,
  ownerPid: c.u32,
  name: c.string,
  description: c.string,
  creationTime: q.dateTime,
  expirationTime: q.dateTime,
  type: c.string,
  locale: c.string,
  subscribable: c.bool,
});

export interface NewsHeader {
  id: number;
  recipientId: number;
  recipientType: number;
  publisherPid: number;
  publisherName: string;
  publicationTime: bigint;
  displayTime: bigint;
  expirationTime: bigint;
  title: string;
  link: string;
}
export const NewsHeader: c.Codec<NewsHeader> = c.struct({
  id: c.u32,
  recipientId: c.u32,
  recipientType: c.u32,
  publisherPid: c.u32,
  publisherName: c.string,
  publicationTime: q.dateTime,
  displayTime: q.dateTime,
  expirationTime: q.dateTime,
  title: c.string,
  link: c.string,
});

export interface NewsMessage {
  newsHeader: NewsHeader;
  body: string;
}
export const NewsMessage: c.Codec<NewsMessage> = c.struct({
  newsHeader: NewsHeader,
  body: c.string,
});

export interface NewsRecipient {
  recipientId: number;
  recipientType: number;
}
export const NewsRecipient: c.Codec<NewsRecipient> = c.struct({
  recipientId: c.u32,
  recipientType: c.u32,
});

export interface NewsFeedLink {
  id: number;
  newsChannelId: number;
  url: string;
  description: string;
  feedUpdatedParseTime: bigint;
  lastUpdatedTime: bigint;
  nextRefreshTime: bigint;
  refreshElapsedTimeMilliseconds: number;
  refreshPeriodSeconds: number;
  refreshEnabled: boolean;
  refreshMethod: number;
  newestMessageTime: bigint;
  messageAdded: number;
}
export const NewsFeedLink: c.Codec<NewsFeedLink> = c.struct({
  id: c.u32,
  newsChannelId: c.u32,
  url: c.string,
  description: c.string,
  feedUpdatedParseTime: q.dateTime,
  lastUpdatedTime: q.dateTime,
  nextRefreshTime: q.dateTime,
  refreshElapsedTimeMilliseconds: c.u32,
  refreshPeriodSeconds: c.u32,
  refreshEnabled: c.bool,
  refreshMethod: c.u32,
  newestMessageTime: q.dateTime,
  messageAdded: c.u32,
});
