// AUTOGENERATED by scripts/generate-protocols.ts from ddl/PrivilegesService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { Privilege, PrivilegeEx, PrivilegeGroup } from "./types";

export interface GetPrivilegesRequest {
  localeCode: string;
}
export const GetPrivilegesRequest: c.Codec<GetPrivilegesRequest> = c.struct({
  localeCode: c.string,
});

export interface GetPrivilegesResponse {
  privileges: Map<number, Privilege>;
}
export const GetPrivilegesResponse: c.Codec<GetPrivilegesResponse> = c.struct({
  privileges: c.map(c.u32, Privilege),
});

export interface ActivateKeyRequest {
  uniqueKey: string;
  languageCode: string;
}
export const ActivateKeyRequest: c.Codec<ActivateKeyRequest> = c.struct({
  uniqueKey: c.string,
  languageCode: c.string,
});

export interface ActivateKeyResponse {
  privilege: PrivilegeGroup;
}
export const ActivateKeyResponse: c.Codec<ActivateKeyResponse> = c.struct({
  privilege: PrivilegeGroup,
});

export interface ActivateKeyWithExpectedPrivilegesRequest {
  uniqueKey: string;
  languageCode: string;
  expectedPrivilegeIds: number[];
}
export const ActivateKeyWithExpectedPrivilegesRequest: c.Codec<ActivateKeyWithExpectedPrivilegesRequest> = c.struct({
  uniqueKey: c.string,
  languageCode: c.string,
  expectedPrivilegeIds: c.list(c.u32),
});

export interface ActivateKeyWithExpectedPrivilegesResponse {
  privilege: PrivilegeGroup;
}
export const ActivateKeyWithExpectedPrivilegesResponse: c.Codec<ActivateKeyWithExpectedPrivilegesResponse> = c.struct({
  privilege: PrivilegeGroup,
});

export interface GetPrivilegeRemainDurationRequest {
  privilegeId: number;
}
export const GetPrivilegeRemainDurationRequest: c.Codec<GetPrivilegeRemainDurationRequest> = c.struct({
  privilegeId: c.u32,
});

export interface GetPrivilegeRemainDurationResponse {
  seconds: number;
}
export const GetPrivilegeRemainDurationResponse: c.Codec<GetPrivilegeRemainDurationResponse> = c.struct({
  seconds: c.i32,
});

export interface GetExpiredPrivilegesRequest {}
export const GetExpiredPrivilegesRequest: c.Codec<GetExpiredPrivilegesRequest> = c.struct({});

export interface GetExpiredPrivilegesResponse {
  expiredPrivileges: PrivilegeEx[];
}
export const GetExpiredPrivilegesResponse: c.Codec<GetExpiredPrivilegesResponse> = c.struct({
  expiredPrivileges: c.list(PrivilegeEx),
});

export interface GetPrivilegesExRequest {
  localeCode: string;
}
export const GetPrivilegesExRequest: c.Codec<GetPrivilegesExRequest> = c.struct({
  localeCode: c.string,
});

export interface GetPrivilegesExResponse {
  privilegesEx: PrivilegeEx[];
}
export const GetPrivilegesExResponse: c.Codec<GetPrivilegesExResponse> = c.struct({
  privilegesEx: c.list(PrivilegeEx),
});

export const PrivilegesProtocol = defineProtocol({
  id: 35,
  name: "PrivilegesProtocol",
  methods: {
    getPrivileges: { id: 1, name: "GetPrivileges", request: GetPrivilegesRequest, response: GetPrivilegesResponse },
    activateKey: { id: 2, name: "ActivateKey", request: ActivateKeyRequest, response: ActivateKeyResponse },
    activateKeyWithExpectedPrivileges: { id: 3, name: "ActivateKeyWithExpectedPrivileges", request: ActivateKeyWithExpectedPrivilegesRequest, response: ActivateKeyWithExpectedPrivilegesResponse },
    getPrivilegeRemainDuration: { id: 4, name: "GetPrivilegeRemainDuration", request: GetPrivilegeRemainDurationRequest, response: GetPrivilegeRemainDurationResponse },
    getExpiredPrivileges: { id: 5, name: "GetExpiredPrivileges", request: GetExpiredPrivilegesRequest, response: GetExpiredPrivilegesResponse },
    getPrivilegesEx: { id: 6, name: "GetPrivilegesEx", request: GetPrivilegesExRequest, response: GetPrivilegesExResponse },
  },
});
