// AUTOGENERATED by scripts/generate-protocols.ts from ddl/PrivilegesService.json. Do not edit.
import * as c from "../../quazal/codec";

export interface Privilege {
  id: number;
  description: string;
}
export const Privilege: c.Codec<Privilege> = c.struct({
  id: c.u32,
  description: c.string,
});

export interface PrivilegeEx {
  id: number;
  description: string;
  duration: number;
}
export const PrivilegeEx: c.Codec<PrivilegeEx> = c.struct({
  id: c.u32,
  description: c.string,
  duration: c.i32,
});

export interface PrivilegeGroup {
  description: string;
  privileges: Privilege[];
}
export const PrivilegeGroup: c.Codec<PrivilegeGroup> = c.struct({
  description: c.string,
  privileges: c.list(Privilege),
});
