// AUTOGENERATED by scripts/generate-protocols.ts from ddl/PlayerStatsService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { LeaderboardHistoryQuery, LeaderboardQuery, LeaderboardQuery2, LeaderboardResult, PlayerStatUpdate, PopulationStatQuery, PopulationStatResult, StatboardHistoryAggregatedQuery, StatboardHistoryQuery, StatboardQuery, StatboardResult } from "./types";

export interface WriteStatsRequest {
  playerStatUpdates: PlayerStatUpdate[];
}
export const WriteStatsRequest: c.Codec<WriteStatsRequest> = c.struct({
  playerStatUpdates: c.list(PlayerStatUpdate),
});

export interface WriteStatsResponse {}
export const WriteStatsResponse: c.Codec<WriteStatsResponse> = c.struct({});

export interface ReadStatsByPlayersRequest {
  playerPids: number[];
  queries: StatboardQuery[];
}
export const ReadStatsByPlayersRequest: c.Codec<ReadStatsByPlayersRequest> = c.struct({
  playerPids: c.list(c.u32),
  queries: c.list(StatboardQuery),
});

export interface ReadStatsByPlayersResponse {
  results: StatboardResult[];
}
export const ReadStatsByPlayersResponse: c.Codec<ReadStatsByPlayersResponse> = c.struct({
  results: c.list(StatboardResult),
});

export interface ReadLeaderboardsNearPlayerRequest {
  playerPid: number;
  count: number;
  queries: LeaderboardQuery[];
}
export const ReadLeaderboardsNearPlayerRequest: c.Codec<ReadLeaderboardsNearPlayerRequest> = c.struct({
  playerPid: c.u32,
  count: c.u32,
  queries: c.list(LeaderboardQuery),
});

export interface ReadLeaderboardsNearPlayerResponse {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsNearPlayerResponse: c.Codec<ReadLeaderboardsNearPlayerResponse> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadLeaderboardsByRankRequest {
  startingRank: number;
  count: number;
  queries: LeaderboardQuery[];
}
export const ReadLeaderboardsByRankRequest: c.Codec<ReadLeaderboardsByRankRequest> = c.struct({
  startingRank: c.u32,
  count: c.u32,
  queries: c.list(LeaderboardQuery),
});

export interface ReadLeaderboardsByRankResponse {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsByRankResponse: c.Codec<ReadLeaderboardsByRankResponse> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadLeaderboardsByPlayersRequest {
  playerPids: number[];
  queries: LeaderboardQuery[];
}
export const ReadLeaderboardsByPlayersRequest: c.Codec<ReadLeaderboardsByPlayersRequest> = c.struct({
  playerPids: c.list(c.u32),
  queries: c.list(LeaderboardQuery),
});

export interface ReadLeaderboardsByPlayersResponse {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsByPlayersResponse: c.Codec<ReadLeaderboardsByPlayersResponse> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadStatboardHistoryRequest {
  queries: StatboardHistoryQuery[];
}
export const ReadStatboardHistoryRequest: c.Codec<ReadStatboardHistoryRequest> = c.struct({
  queries: c.list(StatboardHistoryQuery),
});

export interface ReadStatboardHistoryResponse {
  results: StatboardResult[];
}
export const ReadStatboardHistoryResponse: c.Codec<ReadStatboardHistoryResponse> = c.struct({
  results: c.list(StatboardResult),
});

export interface ReadLeaderboardHistoryRequest {
  queries: LeaderboardHistoryQuery[];
}
export const ReadLeaderboardHistoryRequest: c.Codec<ReadLeaderboardHistoryRequest> = c.struct({
  queries: c.list(LeaderboardHistoryQuery),
});

export interface ReadLeaderboardHistoryResponse {
  results: LeaderboardResult[];
}
export const ReadLeaderboardHistoryResponse: c.Codec<ReadLeaderboardHistoryResponse> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadStatboardHistoryAggregatedRequest {
  queries: StatboardHistoryAggregatedQuery[];
}
export const ReadStatboardHistoryAggregatedRequest: c.Codec<ReadStatboardHistoryAggregatedRequest> = c.struct({
  queries: c.list(StatboardHistoryAggregatedQuery),
});

export interface ReadStatboardHistoryAggregatedResponse {
  results: StatboardResult[];
}
export const ReadStatboardHistoryAggregatedResponse: c.Codec<ReadStatboardHistoryAggregatedResponse> = c.struct({
  results: c.list(StatboardResult),
});

export interface GetStatboardNextPurgeDateRequest {
  boardId: number;
  resetFrequency: number;
}
export const GetStatboardNextPurgeDateRequest: c.Codec<GetStatboardNextPurgeDateRequest> = c.struct({
  boardId: c.u32,
  resetFrequency: c.u32,
});

export interface GetStatboardNextPurgeDateResponse {
  purgeDate: bigint;
}
export const GetStatboardNextPurgeDateResponse: c.Codec<GetStatboardNextPurgeDateResponse> = c.struct({
  purgeDate: q.dateTime,
});

export interface ReadLeaderboardsNearPlayer2Request {
  playerPid: number;
  count: number;
  queries: LeaderboardQuery2[];
}
export const ReadLeaderboardsNearPlayer2Request: c.Codec<ReadLeaderboardsNearPlayer2Request> = c.struct({
  playerPid: c.u32,
  count: c.u32,
  queries: c.list(LeaderboardQuery2),
});

export interface ReadLeaderboardsNearPlayer2Response {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsNearPlayer2Response: c.Codec<ReadLeaderboardsNearPlayer2Response> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadLeaderboardsByRank2Request {
  startingRank: number;
  count: number;
  queries: LeaderboardQuery2[];
}
export const ReadLeaderboardsByRank2Request: c.Codec<ReadLeaderboardsByRank2Request> = c.struct({
  startingRank: c.u32,
  count: c.u32,
  queries: c.list(LeaderboardQuery2),
});

export interface ReadLeaderboardsByRank2Response {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsByRank2Response: c.Codec<ReadLeaderboardsByRank2Response> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadLeaderboardsByPlayers2Request {
  queries: LeaderboardQuery2[];
}
export const ReadLeaderboardsByPlayers2Request: c.Codec<ReadLeaderboardsByPlayers2Request> = c.struct({
  queries: c.list(LeaderboardQuery2),
});

export interface ReadLeaderboardsByPlayers2Response {
  results: LeaderboardResult[];
}
export const ReadLeaderboardsByPlayers2Response: c.Codec<ReadLeaderboardsByPlayers2Response> = c.struct({
  results: c.list(LeaderboardResult),
});

export interface ReadPopulationStatsRequest {
  queries: PopulationStatQuery[];
}
export const ReadPopulationStatsRequest: c.Codec<ReadPopulationStatsRequest> = c.struct({
  queries: c.list(PopulationStatQuery),
});

export interface ReadPopulationStatsResponse {
  results: PopulationStatResult[];
}
export const ReadPopulationStatsResponse: c.Codec<ReadPopulationStatsResponse> = c.struct({
  results: c.list(PopulationStatResult),
});

export const PlayerStatsProtocol = defineProtocol({
  id: 55,
  name: "PlayerStatsProtocol",
  methods: {
    writeStats: { id: 1, name: "WriteStats", request: WriteStatsRequest, response: WriteStatsResponse },
    readStatsByPlayers: { id: 2, name: "ReadStatsByPlayers", request: ReadStatsByPlayersRequest, response: ReadStatsByPlayersResponse },
    readLeaderboardsNearPlayer: { id: 3, name: "ReadLeaderboardsNearPlayer", request: ReadLeaderboardsNearPlayerRequest, response: ReadLeaderboardsNearPlayerResponse },
    readLeaderboardsByRank: { id: 4, name: "ReadLeaderboardsByRank", request: ReadLeaderboardsByRankRequest, response: ReadLeaderboardsByRankResponse },
    readLeaderboardsByPlayers: { id: 5, name: "ReadLeaderboardsByPlayers", request: ReadLeaderboardsByPlayersRequest, response: ReadLeaderboardsByPlayersResponse },
    readStatboardHistory: { id: 6, name: "ReadStatboardHistory", request: ReadStatboardHistoryRequest, response: ReadStatboardHistoryResponse },
    readLeaderboardHistory: { id: 7, name: "ReadLeaderboardHistory", request: ReadLeaderboardHistoryRequest, response: ReadLeaderboardHistoryResponse },
    readStatboardHistoryAggregated: { id: 8, name: "ReadStatboardHistoryAggregated", request: ReadStatboardHistoryAggregatedRequest, response: ReadStatboardHistoryAggregatedResponse },
    getStatboardNextPurgeDate: { id: 9, name: "GetStatboardNextPurgeDate", request: GetStatboardNextPurgeDateRequest, response: GetStatboardNextPurgeDateResponse },
    readLeaderboardsNearPlayer2: { id: 10, name: "ReadLeaderboardsNearPlayer2", request: ReadLeaderboardsNearPlayer2Request, response: ReadLeaderboardsNearPlayer2Response },
    readLeaderboardsByRank2: { id: 11, name: "ReadLeaderboardsByRank2", request: ReadLeaderboardsByRank2Request, response: ReadLeaderboardsByRank2Response },
    readLeaderboardsByPlayers2: { id: 12, name: "ReadLeaderboardsByPlayers2", request: ReadLeaderboardsByPlayers2Request, response: ReadLeaderboardsByPlayers2Response },
    readPopulationStats: { id: 13, name: "ReadPopulationStats", request: ReadPopulationStatsRequest, response: ReadPopulationStatsResponse },
  },
});
