// AUTOGENERATED by scripts/generate-protocols.ts from ddl/PlayerStatsService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface PlayerStatUpdate {
  boardId: number;
  contextIds: number[];
  stats: q.PropertyVariant[];
}
export const PlayerStatUpdate: c.Codec<PlayerStatUpdate> = c.struct({
  boardId: c.u32,
  contextIds: c.list(c.u32),
  stats: c.list(q.PropertyVariant),
});

export interface PlayerStatSortCriteria {
  sortStatId: number;
  sortOrder: number;
}
export const PlayerStatSortCriteria: c.Codec<PlayerStatSortCriteria> = c.struct({
  sortStatId: c.u32,
  sortOrder: c.u32,
});

export interface StatboardQuery {
  boardId: number;
  contextIds: number[];
  resetFrequency: number;
  statIds: number[];
  sortCriterias: PlayerStatSortCriteria[];
}
export const StatboardQuery: c.Codec<StatboardQuery> = c.struct({
  boardId: c.u32,
  contextIds: c.list(c.u32),
  resetFrequency: c.u32,
  statIds: c.list(c.u32),
  sortCriterias: c.list(PlayerStatSortCriteria),
});

export interface LeaderboardQuery {
  boardId: number;
  contextId: number;
  resetFrequency: number;
  statIds: number[];
}
export const LeaderboardQuery: c.Codec<LeaderboardQuery> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  resetFrequency: c.u32,
  statIds: c.list(c.u32),
});

export interface LeaderboardQuery2 {
  boardId: number;
  contextId: number;
  resetFrequency: number;
  statIds: number[];
  estimatedPids: number[];
}
export const LeaderboardQuery2: c.Codec<LeaderboardQuery2> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  resetFrequency: c.u32,
  statIds: c.list(c.u32),
  estimatedPids: c.list(c.u32),
});

export interface PlayerStatSet {
  playerPid: number;
  playerName: string;
  submittedTime: bigint;
  stats: q.PropertyVariant[];
}
export const PlayerStatSet: c.Codec<PlayerStatSet> = c.struct({
  playerPid: c.u32,
  playerName: c.string,
  submittedTime: q.dateTime,
  stats: c.list(q.PropertyVariant),
});

export interface StatboardResult {
  boardId: number;
  contextId: number;
  resetFrequency: number;
  playerStatSets: PlayerStatSet[];
  defaultStatValues: q.PropertyVariant[];
}
export const StatboardResult: c.Codec<StatboardResult> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  resetFrequency: c.u32,
  playerStatSets: c.list(PlayerStatSet),
  defaultStatValues: c.list(q.PropertyVariant),
});

export interface PlayerRank {
  playerStatSet: PlayerStatSet;
  rankStatus: number;
  rank: number;
  score: q.Variant;
}
export const PlayerRank: c.Codec<PlayerRank> = c.struct({
  playerStatSet: PlayerStatSet,
  rankStatus: c.u32,
  rank: c.u32,
  score: q.variant,
});

export interface LeaderboardResult {
  boardId: number;
  contextId: number;
  resetFrequency: number;
  leaderboardTotalPlayerCount: number;
  playerRanks: PlayerRank[];
}
export const LeaderboardResult: c.Codec<LeaderboardResult> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  resetFrequency: c.u32,
  leaderboardTotalPlayerCount: c.u32,
  playerRanks: c.list(PlayerRank),
});

export interface DateRange {
  startingDatetime: bigint;
  endingDatetime: bigint;
}
export const DateRange: c.Codec<DateRange> = c.struct({
  startingDatetime: q.dateTime,
  endingDatetime: q.dateTime,
});

export interface StatboardHistoryQuery {
  playerPids: number[];
  boardId: number;
  contextIds: number[];
  statIds: number[];
  resultRange: q.ResultRange;
  playerStats: q.PropertyVariant[];
  dateRanges: DateRange[];
  sortCriterias: PlayerStatSortCriteria[];
}
export const StatboardHistoryQuery: c.Codec<StatboardHistoryQuery> = c.struct({
  playerPids: c.list(c.u32),
  boardId: c.u32,
  contextIds: c.list(c.u32),
  statIds: c.list(c.u32),
  resultRange: q.ResultRange,
  playerStats: c.list(q.PropertyVariant),
  dateRanges: c.list(DateRange),
  sortCriterias: c.list(PlayerStatSortCriteria),
});

export interface StatboardHistoryAggregatedQuery {
  playerPids: number[];
  boardId: number;
  contextIds: number[];
  statIds: number[];
  resultRange: q.ResultRange;
  playerStats: q.PropertyVariant[];
  dateRanges: DateRange[];
  sortCriterias: PlayerStatSortCriteria[];
  filterOption: number;
}
export const StatboardHistoryAggregatedQuery: c.Codec<StatboardHistoryAggregatedQuery> = c.struct({
  playerPids: c.list(c.u32),
  boardId: c.u32,
  contextIds: c.list(c.u32),
  statIds: c.list(c.u32),
  resultRange: q.ResultRange,
  playerStats: c.list(q.PropertyVariant),
  dateRanges: c.list(DateRange),
  sortCriterias: c.list(PlayerStatSortCriteria),
  filterOption: c.u32,
});

export interface LeaderboardHistoryQuery {
  playerPids: number[];
  boardId: number;
  contextId: number;
  resultRange: q.ResultRange;
  dateRanges: DateRange[];
  filterOption: number;
}
export const LeaderboardHistoryQuery: c.Codec<LeaderboardHistoryQuery> = c.struct({
  playerPids: c.list(c.u32),
  boardId: c.u32,
  contextId: c.u32,
  resultRange: q.ResultRange,
  dateRanges: c.list(DateRange),
  filterOption: c.u32,
});

export interface PopulationStatQuery {
  boardId: number;
  contextId: number;
  statIds: number[];
}
export const PopulationStatQuery: c.Codec<PopulationStatQuery> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  statIds: c.list(c.u32),
});

export interface PopulationStatResult {
  boardId: number;
  contextId: number;
  statId: number;
  sum: number;
  average: number;
  standardDeviation: number;
}
export const PopulationStatResult: c.Codec<PopulationStatResult> = c.struct({
  boardId: c.u32,
  contextId: c.u32,
  statId: c.u32,
  sum: c.f64,
  average: c.f64,
  standardDeviation: c.f64,
});
