// AUTOGENERATED by scripts/generate-protocols.ts from ddl/SecureConnectionService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { ConnectionData } from "./types";

export interface RegisterRequest {
  vecMyUrls: q.StationURL[];
}
export const RegisterRequest: c.Codec<RegisterRequest> = c.struct({
  vecMyUrls: c.list(q.stationUrl),
});

export interface RegisterResponse {
  returnValue: number;
  pidConnectionId: number;
  urlPublic: q.StationURL;
}
export const RegisterResponse: c.Codec<RegisterResponse> = c.struct({
  returnValue: q.qresult,
  pidConnectionId: c.u32,
  urlPublic: q.stationUrl,
});

export interface RequestConnectionDataRequest {
  cidTarget: number;
  pidTarget: number;
}
export const RequestConnectionDataRequest: c.Codec<RequestConnectionDataRequest> = c.struct({
  cidTarget: c.u32,
  pidTarget: c.u32,
});

export interface RequestConnectionDataResponse {
  returnValue: boolean;
  pvecConnectionsData: ConnectionData[];
}
export const RequestConnectionDataResponse: c.Codec<RequestConnectionDataResponse> = c.struct({
  returnValue: c.bool,
  pvecConnectionsData: c.list(ConnectionData),
});

export interface RequestUrlsRequest {
  cidTarget: number;
  pidTarget: number;
}
export const RequestUrlsRequest: c.Codec<RequestUrlsRequest> = c.struct({
  cidTarget: c.u32,
  pidTarget: c.u32,
});

export interface RequestUrlsResponse {
  returnValue: boolean;
  plstUrls: q.StationURL[];
}
export const RequestUrlsResponse: c.Codec<RequestUrlsResponse> = c.struct({
  returnValue: c.bool,
  plstUrls: c.list(q.stationUrl),
});

export interface RegisterExRequest {
  vecMyUrls: q.StationURL[];
  hCustomData: q.AnyData;
}
export const RegisterExRequest: c.Codec<RegisterExRequest> = c.struct({
  vecMyUrls: c.list(q.stationUrl),
  hCustomData: q.anyData,
});

export interface RegisterExResponse {
  returnValue: number;
  pidConnectionId: number;
  urlPublic: q.StationURL;
}
export const RegisterExResponse: c.Codec<RegisterExResponse> = c.struct({
  returnValue: q.qresult,
  pidConnectionId: c.u32,
  urlPublic: q.stationUrl,
});

export const SecureConnectionProtocol = defineProtocol({
  id: 11,
  name: "SecureConnectionProtocol",
  methods: {
    register: { id: 1, name: "Register", request: RegisterRequest, response: RegisterResponse },
    requestConnectionData: { id: 2, name: "RequestConnectionData", request: RequestConnectionDataRequest, response: RequestConnectionDataResponse },
    requestUrls: { id: 3, name: "RequestURLs", request: RequestUrlsRequest, response: RequestUrlsResponse },
    registerEx: { id: 4, name: "RegisterEx", request: RegisterExRequest, response: RegisterExResponse },
  },
});
