// AUTOGENERATED by scripts/generate-protocols.ts from ddl/SecureConnectionService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface ConnectionData {
  stationUrl: q.StationURL;
  connectionId: number;
}
export const ConnectionData: c.Codec<ConnectionData> = c.struct({
  stationUrl: q.stationUrl,
  connectionId: c.u32,
});
