// AUTOGENERATED by scripts/generate-protocols.ts from ddl/LocalizationService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface GetLocaleCodeRequest {}
export const GetLocaleCodeRequest: c.Codec<GetLocaleCodeRequest> = c.struct({});

export interface GetLocaleCodeResponse {
  localCode: string;
}
export const GetLocaleCodeResponse: c.Codec<GetLocaleCodeResponse> = c.struct({
  localCode: c.string,
});

export interface SetLocaleCodeRequest {
  localCode: string;
}
export const SetLocaleCodeRequest: c.Codec<SetLocaleCodeRequest> = c.struct({
  localCode: c.string,
});

export interface SetLocaleCodeResponse {}
export const SetLocaleCodeResponse: c.Codec<SetLocaleCodeResponse> = c.struct({});

export const LocalizationProtocol = defineProtocol({
  id: 39,
  name: "LocalizationProtocol",
  methods: {
    getLocaleCode: { id: 1, name: "GetLocaleCode", request: GetLocaleCodeRequest, response: GetLocaleCodeResponse },
    setLocaleCode: { id: 2, name: "SetLocaleCode", request: SetLocaleCodeRequest, response: SetLocaleCodeResponse },
  },
});
