// AUTOGENERATED by scripts/generate-protocols.ts from ddl/SimpleAuthentication.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { RVConnectionData } from "./types";

export interface AuthenticateRequest {
  strUserName: string;
}
export const AuthenticateRequest: c.Codec<AuthenticateRequest> = c.struct({
  strUserName: c.string,
});

export interface AuthenticateResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const AuthenticateResponse: c.Codec<AuthenticateResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginWithTokenRequest {
  strToken: string;
}
export const LoginWithTokenRequest: c.Codec<LoginWithTokenRequest> = c.struct({
  strToken: c.string,
});

export interface LoginWithTokenResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginWithTokenResponse: c.Codec<LoginWithTokenResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginWithTokenExRequest {
  strToken: string;
  oAnyData: q.AnyData;
}
export const LoginWithTokenExRequest: c.Codec<LoginWithTokenExRequest> = c.struct({
  strToken: c.string,
  oAnyData: q.anyData,
});

export interface LoginWithTokenExResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginWithTokenExResponse: c.Codec<LoginWithTokenExResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginRequest {
  strUsername: string;
  strPassword: string;
}
export const LoginRequest: c.Codec<LoginRequest> = c.struct({
  strUsername: c.string,
  strPassword: c.string,
});

export interface LoginResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginResponse: c.Codec<LoginResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginWithSubAccountRequest {
  loginData: q.AnyData;
}
export const LoginWithSubAccountRequest: c.Codec<LoginWithSubAccountRequest> = c.struct({
  loginData: q.anyData,
});

export interface LoginWithSubAccountResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginWithSubAccountResponse: c.Codec<LoginWithSubAccountResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface RegisterRequest {
  vecMyUrls: q.StationURL[];
}
export const RegisterRequest: c.Codec<RegisterRequest> = c.struct({
  vecMyUrls: c.list(q.stationUrl),
});

export interface RegisterResponse {
  returnValue: number;
  pidConnectionId: number;
  urlPublic: q.StationURL;
}
export const RegisterResponse: c.Codec<RegisterResponse> = c.struct({
  returnValue: q.qresult,
  pidConnectionId: c.u32,
  urlPublic: q.stationUrl,
});

export interface RegisterExRequest {
  vecMyUrls: q.StationURL[];
  hCustomData: q.AnyData;
}
export const RegisterExRequest: c.Codec<RegisterExRequest> = c.struct({
  vecMyUrls: c.list(q.stationUrl),
  hCustomData: q.anyData,
});

export interface RegisterExResponse {
  returnValue: number;
  pidConnectionId: number;
  urlPublic: q.StationURL;
}
export const RegisterExResponse: c.Codec<RegisterExResponse> = c.struct({
  returnValue: q.qresult,
  pidConnectionId: c.u32,
  urlPublic: q.stationUrl,
});

export interface LoginWithTokenCafeRequest {
  strNintendoToken: string;
}
export const LoginWithTokenCafeRequest: c.Codec<LoginWithTokenCafeRequest> = c.struct({
  strNintendoToken: c.string,
});

export interface LoginWithTokenCafeResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginWithTokenCafeResponse: c.Codec<LoginWithTokenCafeResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export interface LoginWithTokenCafeExRequest {
  strNintendoToken: string;
  oAnyData: q.AnyData;
}
export const LoginWithTokenCafeExRequest: c.Codec<LoginWithTokenCafeExRequest> = c.struct({
  strNintendoToken: c.string,
  oAnyData: q.anyData,
});

export interface LoginWithTokenCafeExResponse {
  returnValue: number;
  pidPrincipal: number;
  pConnectionData: RVConnectionData;
  strReturnMsg: string;
}
export const LoginWithTokenCafeExResponse: c.Codec<LoginWithTokenCafeExResponse> = c.struct({
  returnValue: q.qresult,
  pidPrincipal: c.u32,
  pConnectionData: RVConnectionData,
  strReturnMsg: c.string,
});

export const SimpleAuthenticationProtocol = defineProtocol({
  id: 16,
  name: "SimpleAuthenticationProtocol",
  methods: {
    authenticate: { id: 1, name: "Authenticate", request: AuthenticateRequest, response: AuthenticateResponse },
    loginWithToken: { id: 2, name: "LoginWithToken", request: LoginWithTokenRequest, response: LoginWithTokenResponse },
    loginWithTokenEx: { id: 3, name: "LoginWithTokenEx", request: LoginWithTokenExRequest, response: LoginWithTokenExResponse },
    login: { id: 4, name: "Login", request: LoginRequest, response: LoginResponse },
    loginWithSubAccount: { id: 5, name: "LoginWithSubAccount", request: LoginWithSubAccountRequest, response: LoginWithSubAccountResponse },
    register: { id: 6, name: "Register", request: RegisterRequest, response: RegisterResponse },
    registerEx: { id: 7, name: "RegisterEx", request: RegisterExRequest, response: RegisterExResponse },
    loginWithTokenCafe: { id: 8, name: "LoginWithTokenCafe", request: LoginWithTokenCafeRequest, response: LoginWithTokenCafeResponse },
    loginWithTokenCafeEx: { id: 9, name: "LoginWithTokenCafeEx", request: LoginWithTokenCafeExRequest, response: LoginWithTokenCafeExResponse },
  },
});
