// AUTOGENERATED by scripts/generate-protocols.ts from ddl/SimpleAuthentication.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface RVConnectionData {
  urlRegularProtocols: q.StationURL;
  lstSpecialProtocols: number[];
  urlSpecialProtocols: q.StationURL;
}
export const RVConnectionData: c.Codec<RVConnectionData> = c.struct({
  urlRegularProtocols: q.stationUrl,
  lstSpecialProtocols: c.list(c.u8),
  urlSpecialProtocols: q.stationUrl,
});

export interface LoginData {
  principalType: number;
  userName: string;
  context: bigint;
  similarConnection: number;
}
export const LoginData: c.Codec<LoginData> = c.struct({
  principalType: c.i8,
  userName: c.string,
  context: c.u64,
  similarConnection: c.u32,
});
