/**
 * Generates `src/protocols` from the DDL files in `ddl/`.
 *
 * TypeScript counterpart of 5th-echelon's `quazal-tools` generator: every namespace gets a
 * `types.ts` with its classes, and every protocol a module with request/response types and a
 * `defineProtocol` description. Like the Rust generator, only parameters of type "request" end
 * up in requests; response and in/out parameters form the response after the return value.
 *
 * Usage: bun run scripts/generate-protocols.ts
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BUILTIN_CLASSES,
  camel,
  fieldName,
  kebab,
  loadDdl,
  NAMESPACE_LOCAL_CLASSES,
  pascal,
  protocolId,
  type ClassDeclaration,
  type DdlType,
  type Namespace,
} from "./ddl";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "src", "protocols");

interface Mapped {
  ts: string;
  codec: string;
  /** Classes the expression refers to. */
  classes: string[];
}

const PRIMITIVES: Record<string, [ts: string, codec: string]> = {
  bool: ["boolean", "c.bool"],
  byte: ["number", "c.u8"],
  uint8: ["number", "c.u8"],
  char: ["number", "c.u8"],
  uint16: ["number", "c.u16"],
  uint32: ["number", "c.u32"],
  uint64: ["bigint", "c.u64"],
  int8: ["number", "c.i8"],
  int16: ["number", "c.i16"],
  int32: ["number", "c.i32"],
  int64: ["bigint", "c.i64"],
  float: ["number", "c.f32"],
  double: ["number", "c.f64"],
  string: ["string", "c.string"],
  buffer: ["Buffer", "c.buffer"],
  qBuffer: ["Buffer", "c.qBuffer"],
  buffertail: ["Buffer", "c.bufferTail"],
  qresult: ["number", "q.qresult"],
  datetime: ["bigint", "q.dateTime"],
  stationurl: ["q.StationURL", "q.stationUrl"],
  variant: ["q.Variant", "q.variant"],
  Property: ["q.Property", "q.Property"],
  PropertyVariant: ["q.PropertyVariant", "q.PropertyVariant"],
  ResultRange: ["q.ResultRange", "q.ResultRange"],
  Data: ["q.Data", "q.Data"],
};

function mapType(type: DdlType): Mapped {
  if (type.__class__ === "SimpleType") {
    const primitive = PRIMITIVES[type.name];
    if (primitive) {
      return { ts: primitive[0], codec: primitive[1], classes: [] };
    }
    return { ts: type.name, codec: type.name, classes: [type.name] };
  }
  const params = type.parameters.map(mapType);
  switch (type.templ_name) {
    case "qlist":
    case "qvector":
    case "std_list":
      return { ts: `${wrapArray(params[0].ts)}[]`, codec: `c.list(${params[0].codec})`, classes: params[0].classes };
    case "std_map":
      return {
        ts: `Map<${params[0].ts}, ${params[1].ts}>`,
        codec: `c.map(${params[0].codec}, ${params[1].codec})`,
        classes: [...params[0].classes, ...params[1].classes],
      };
    case "any":
      if (type.parameters[1]?.__class__ !== "SimpleType" || type.parameters[1].name !== "string") {
        throw new Error(`unsupported any type ${type.name}`);
      }
      return { ts: "q.AnyData", codec: "q.anyData", classes: [] };
    default:
      throw new Error(`unsupported template ${type.name}`);
  }
}

function wrapArray(ts: string) {
  return ts.includes(" ") || ts.includes("<") ? `(${ts})` : ts;
}

interface Field {
  name: string;
  type: Mapped;
}

/** Emits an interface and a struct codec with the same name. */
function emitStruct(name: string, fields: Field[]) {
  if (fields.length === 0) {
    return `export interface ${name} {}\nexport const ${name}: c.Codec<${name}> = c.struct({});\n`;
  }
  const iface = fields.map((f) => `  ${f.name}: ${f.type.ts};`).join("\n");
  const codec = fields.map((f) => `  ${f.name}: ${f.type.codec},`).join("\n");
  return `export interface ${name} {\n${iface}\n}\nexport const ${name}: c.Codec<${name}> = c.struct({\n${codec}\n});\n`;
}

function classFields(decl: ClassDeclaration): Field[] {
  const fields = decl.variables.map((v) => ({ name: fieldName(v.name1), type: mapType(v.type.type) }));
  // The base class is serialized first. `Data` has no fields, so it is left out.
  if (decl.maybe_base && decl.maybe_base !== "Data") {
    fields.unshift({ name: camel(decl.maybe_base), type: mapType({ __class__: "SimpleType", name: decl.maybe_base }) });
  }
  return fields;
}

/** Namespace of every class that can be imported from other namespaces. */
function buildClassIndex(namespaces: Namespace[]) {
  const index = new Map<string, string>();
  for (const ns of namespaces) {
    for (const decl of ns.classes) {
      if (BUILTIN_CLASSES.has(decl.name1) || NAMESPACE_LOCAL_CLASSES.has(decl.name1)) {
        continue;
      }
      if (index.has(decl.name1)) {
        throw new Error(`class ${decl.name1} exists in ${index.get(decl.name1)} and ${decl.namespace}`);
      }
      index.set(decl.name1, decl.namespace);
    }
  }
  return index;
}

const HEADER = (source: string) =>
  `// AUTOGENERATED by scripts/generate-protocols.ts from ddl/${source}. Do not edit.\n`;

class Imports {
  private readonly local = new Set<string>();
  private readonly foreign = new Map<string, Set<string>>();

  constructor(
    private readonly namespace: Namespace,
    private readonly index: Map<string, string>,
    private readonly fromTypesFile: boolean,
  ) {}

  add(classes: string[]) {
    for (const name of classes) {
      const local = this.namespace.classes.some((c) => c.name1 === name);
      const owner = local ? this.namespace.name : this.index.get(name);
      if (!owner) {
        throw new Error(`unknown class ${name} referenced in ${this.namespace.name}`);
      }
      if (owner === this.namespace.name) {
        this.local.add(name);
      } else {
        const set = this.foreign.get(owner) ?? new Set();
        set.add(name);
        this.foreign.set(owner, set);
      }
    }
  }

  render() {
    const lines: string[] = [];
    if (!this.fromTypesFile && this.local.size) {
      lines.push(`import { ${[...this.local].sort().join(", ")} } from "./types";`);
    }
    for (const [owner, names] of [...this.foreign].sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`import { ${[...names].sort().join(", ")} } from "../${kebab(owner)}/types";`);
    }
    return lines.join("\n");
  }
}

/** Orders classes so that every class is declared after the classes it references. */
function sortClasses(namespace: Namespace) {
  const byName = new Map(namespace.classes.map((c) => [c.name1, c]));
  const sorted: ClassDeclaration[] = [];
  const state = new Map<string, "visiting" | "done">();
  const visit = (decl: ClassDeclaration) => {
    if (state.get(decl.name1) === "done") {
      return;
    }
    if (state.get(decl.name1) === "visiting") {
      throw new Error(`cyclic class reference involving ${decl.name1}`);
    }
    state.set(decl.name1, "visiting");
    for (const field of classFields(decl)) {
      for (const dep of field.type.classes) {
        const local = byName.get(dep);
        if (local && local !== decl) {
          visit(local);
        }
      }
    }
    state.set(decl.name1, "done");
    sorted.push(decl);
  };
  namespace.classes.forEach(visit);
  return sorted;
}

function renderModule(source: string, runtime: ("codec" | "protocol")[], classImports: string, body: string) {
  const lines = [`import * as c from "../../quazal/codec";`];
  if (runtime.includes("protocol")) {
    lines.push(`import { defineProtocol } from "../../quazal/rmc/protocol";`);
  }
  if (body.includes("q.")) {
    lines.push(`import * as q from "../../quazal/types";`);
  }
  if (classImports) {
    lines.push(classImports);
  }
  return `${HEADER(source)}${lines.join("\n")}\n\n${body}`;
}

function generateTypes(namespace: Namespace, index: Map<string, string>) {
  const imports = new Imports(namespace, index, true);
  const body = sortClasses(namespace)
    .map((decl) => {
      const fields = classFields(decl);
      fields.forEach((f) => imports.add(f.type.classes));
      return emitStruct(decl.name1, fields);
    })
    .join("\n");
  return renderModule(namespace.file, ["codec"], imports.render(), body);
}

function generateProtocol(
  namespace: Namespace,
  protocol: Namespace["protocols"][number],
  id: number | undefined,
  index: Map<string, string>,
) {
  const imports = new Imports(namespace, index, false);
  const types: string[] = [];
  const methods: string[] = [];

  protocol.methods.forEach((method, i) => {
    const typeName = pascal(method.name1);
    const params = method.elements1.filter((e) => e.__class__ === "Parameter");
    const retval = method.elements1.find((e) => e.__class__ === "ReturnValue");

    const request = params
      .filter((p) => p.type === 1)
      .map((p) => ({ name: camel(p.name1), type: mapType(p.dtype1.type) }));
    const response = [
      ...(retval ? [{ name: "returnValue", type: mapType(retval.dtype1.type) }] : []),
      ...params.filter((p) => p.type !== 1).map((p) => ({ name: camel(p.name1), type: mapType(p.dtype1.type) })),
    ];
    [...request, ...response].forEach((f) => imports.add(f.type.classes));

    types.push(emitStruct(`${typeName}Request`, request), emitStruct(`${typeName}Response`, response));
    methods.push(
      `    ${camel(method.name1)}: { id: ${i + 1}, name: "${method.name1}", request: ${typeName}Request, response: ${typeName}Response },`,
    );
  });

  const body =
    types.join("\n") +
    "\n" +
    `export const ${protocol.name1} = defineProtocol({\n` +
    `  id: ${id ?? "undefined"},\n` +
    `  name: "${protocol.name1}",\n` +
    `  methods: {\n${methods.join("\n")}\n  },\n` +
    `});\n`;
  return renderModule(namespace.file, ["codec", "protocol"], imports.render(), body);
}

function main() {
  const { namespaces, mapping } = loadDdl(join(ROOT, "ddl"));
  const index = buildClassIndex(namespaces);

  rmSync(OUT, { recursive: true, force: true });
  const exports: string[] = [];
  for (const namespace of namespaces) {
    if (namespace.classes.length === 0 && namespace.protocols.length === 0) {
      continue;
    }
    const dir = join(OUT, kebab(namespace.name));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "types.ts"), generateTypes(namespace, index));
    for (const protocol of namespace.protocols) {
      const id = protocolId(protocol, mapping);
      const file = kebab(protocol.name1);
      writeFileSync(join(dir, `${file}.ts`), generateProtocol(namespace, protocol, id, index));
      exports.push(`export { ${protocol.name1} } from "./${kebab(namespace.name)}/${file}";`);
      console.log(`${protocol.name1.padEnd(36)} id=${String(id).padEnd(9)} ${protocol.methods.length} methods`);
    }
  }
  writeFileSync(join(OUT, "index.ts"), HEADER("*.json") + exports.sort().join("\n") + "\n");
}

main();
