/**
 * Cross-checks the generated protocols in `src/protocols` against the Rust code generated by
 * 5th-echelon (`dedicated_server/sc_bl_protocols/src/protocols`): protocol ids, method ids and
 * the wire layout (field order and types) of every class, request and response.
 *
 * Usage: bun run scripts/verify-against-rust.ts <path to 5th-echelon checkout>
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

type Struct = { fields: [name: string, type: string][] };

interface Module {
  structs: Map<string, Struct>;
  protocolId?: string;
  methods: Map<string, number>;
}

/** Lowercase without separators, so `register_ur_ls`, `RegisterUrLs` and `registerUrls` compare equal. */
const norm = (name: string) => name.toLowerCase().replaceAll("_", "").replace(/^typ$/, "type");

function splitArgs(args: string) {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const ch of args) {
    if ("<(".includes(ch)) depth++;
    if (">)".includes(ch)) depth--;
    if (ch === "," && depth === 0) {
      parts.push(current.trim());
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim()) parts.push(current.trim());
  return parts;
}

function canonicalRust(type: string): string {
  type = type.trim().replace(/^(quazal::rmc::types::|std::collections::)/, "");
  const generic = /^(\w+)<(.*)>$/.exec(type);
  if (generic) {
    const [, name, args] = generic;
    const params = splitArgs(args).map(canonicalRust);
    if (name === "QList" || name === "Vec") return `list<${params[0]}>`;
    if (name === "HashMap") return `map<${params[0]},${params[1]}>`;
    if (name === "Any") return "any";
    throw new Error(`unknown rust generic ${type}`);
  }
  const simple: Record<string, string> = {
    String: "string",
    QResult: "u32",
    DateTime: "u64",
    StationURL: "stationurl",
    Variant: "variant",
    QBuffer: "qbuffer",
    BufferTail: "buffertail",
  };
  return simple[type] ?? type;
}

function canonicalTs(expr: string): string {
  expr = expr.trim();
  const call = /^c\.(list|map)\((.*)\)$/.exec(expr);
  if (call) {
    const params = splitArgs(call[2]).map(canonicalTs);
    return call[1] === "list" ? `list<${params[0]}>` : `map<${params[0]},${params[1]}>`;
  }
  const simple: Record<string, string> = {
    "c.buffer": "list<u8>",
    "c.qBuffer": "qbuffer",
    "c.bufferTail": "buffertail",
    "c.bool": "bool",
    "c.string": "string",
    "q.qresult": "u32",
    "q.dateTime": "u64",
    "q.stationUrl": "stationurl",
    "q.variant": "variant",
    "q.anyData": "any",
    "q.Property": "Property",
    "q.PropertyVariant": "PropertyVariant",
    "q.ResultRange": "ResultRange",
  };
  if (simple[expr]) return simple[expr];
  const primitive = /^c\.([ui](8|16|32|64)|f32|f64)$/.exec(expr);
  return primitive ? primitive[1] : expr;
}

function parseRust(source: string): Module {
  const module: Module = { structs: new Map(), methods: new Map() };
  for (const m of source.matchAll(/pub struct (\w+)(;|\s*\{([^}]*)\})/g)) {
    if (m[1].endsWith("Server") || m[1].endsWith("Client")) continue;
    const fields = [...(m[3] ?? "").matchAll(/pub (\w+): ([^\n]+?),?\n/g)]
      .map((f): [string, string] => [norm(f[1]), canonicalRust(f[2].replace(/,$/, ""))])
      // `Data` has no wire representation, the TypeScript generator leaves it out.
      .filter(([, type]) => type !== "Data");
    module.structs.set(norm(m[1]), { fields });
  }
  module.protocolId = /pub const \w+_ID: u16 = (\w+)u16;/.exec(source)?.[1] ?? (/_ID: u16 = todo!\(\)/.test(source) ? "undefined" : undefined);
  const methods = /pub enum \w+Method \{([^}]*)\}/.exec(source);
  for (const m of methods?.[1].matchAll(/(\w+) = (\d+)u32/g) ?? []) {
    module.methods.set(norm(m[1]), Number(m[2]));
  }
  return module;
}

function parseTs(source: string): Module {
  const module: Module = { structs: new Map(), methods: new Map() };
  for (const m of source.matchAll(/export const (\w+): c\.Codec<\w+> = c\.struct\(\{([^}]*)\}\);/g)) {
    const fields = [...m[2].matchAll(/^\s+(\w+): (.+),$/gm)].map((f): [string, string] => [norm(f[1]), canonicalTs(f[2])]);
    module.structs.set(norm(m[1]), { fields });
  }
  module.protocolId = /^\s+id: (\w+),$/m.exec(source)?.[1];
  for (const m of source.matchAll(/^\s+\w+: \{ id: (\d+), name: "(\w+)"/gm)) {
    module.methods.set(norm(m[2]), Number(m[1]));
  }
  return module;
}

function walk(dir: string, ext: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    return statSync(path).isDirectory() ? walk(path, ext) : path.endsWith(ext) ? [path] : [];
  });
}

/** `game_session_service/types.rs` and `game-session-service/types.ts` share the key `gamesessionservice/types`. */
const moduleKey = (path: string, root: string) =>
  path.slice(root.length + 1).replace(/\.(rs|ts)$/, "").replaceAll("_", "").replaceAll("-", "").toLowerCase();

function main() {
  const upstream = process.argv[2] ?? process.env.FIFTH_ECHELON_DIR;
  if (!upstream) {
    console.error("usage: bun run scripts/verify-against-rust.ts <path to 5th-echelon checkout>");
    process.exit(2);
  }
  const rustRoot = join(upstream, "dedicated_server", "sc_bl_protocols", "src", "protocols");
  const tsRoot = join(import.meta.dir, "..", "src", "protocols");

  const rust = new Map(
    walk(rustRoot, ".rs")
      .filter((p) => !p.endsWith("mod.rs"))
      .map((p) => [moduleKey(p, rustRoot), parseRust(readFileSync(p, "utf8"))]),
  );
  const ts = new Map(
    walk(tsRoot, ".ts")
      .filter((p) => !p.endsWith("index.ts"))
      .map((p) => [moduleKey(p, tsRoot), parseTs(readFileSync(p, "utf8"))]),
  );

  const problems: string[] = [];
  let structs = 0;
  let methods = 0;
  for (const [key, r] of rust) {
    const t = ts.get(key);
    if (!t) {
      problems.push(`${key}: missing TypeScript module`);
      continue;
    }
    if (r.protocolId !== t.protocolId) {
      problems.push(`${key}: protocol id ${t.protocolId} != rust ${r.protocolId}`);
    }
    for (const [name, id] of r.methods) {
      methods++;
      if (t.methods.get(name) !== id) {
        problems.push(`${key}: method ${name} has id ${t.methods.get(name)} != rust ${id}`);
      }
    }
    if (t.methods.size !== r.methods.size) {
      problems.push(`${key}: ${t.methods.size} methods != rust ${r.methods.size}`);
    }
    for (const [name, struct] of r.structs) {
      structs++;
      const other = t.structs.get(name);
      if (!other) {
        problems.push(`${key}: missing struct ${name}`);
      } else if (JSON.stringify(other.fields) !== JSON.stringify(struct.fields)) {
        problems.push(`${key}: ${name} differs\n    ts:   ${JSON.stringify(other.fields)}\n    rust: ${JSON.stringify(struct.fields)}`);
      }
    }
    if (t.structs.size !== r.structs.size) {
      problems.push(`${key}: ${t.structs.size} structs != rust ${r.structs.size}`);
    }
  }
  for (const key of ts.keys()) {
    if (!rust.has(key)) problems.push(`${key}: not present in the Rust code`);
  }

  console.log(`Compared ${rust.size} modules, ${structs} structs and ${methods} methods.`);
  if (problems.length) {
    console.log(problems.join("\n"));
    process.exit(1);
  }
  console.log("Generated protocols match the Rust implementation.");
}

main();
