// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UserStorage.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface ContentProperty {
  id: number;
  value: q.Variant;
}
export const ContentProperty: c.Codec<ContentProperty> = c.struct({
  id: c.u32,
  value: q.variant,
});

export interface UserContentKey {
  typeId: number;
  contentId: bigint;
}
export const UserContentKey: c.Codec<UserContentKey> = c.struct({
  typeId: c.u32,
  contentId: c.u64,
});

export interface UserContent {
  key: UserContentKey;
  pid: number;
  properties: ContentProperty[];
}
export const UserContent: c.Codec<UserContent> = c.struct({
  key: UserContentKey,
  pid: c.u32,
  properties: c.list(ContentProperty),
});

export interface UserStorageQuery {
  typeId: number;
  queryId: number;
  resultRange: q.ResultRange;
  parameters: ContentProperty[];
}
export const UserStorageQuery: c.Codec<UserStorageQuery> = c.struct({
  typeId: c.u32,
  queryId: c.u32,
  resultRange: q.ResultRange,
  parameters: c.list(ContentProperty),
});

export interface UserSlotCount {
  pid: number;
  typeId: number;
  usedSlots: number;
  totalSlots: number;
}
export const UserSlotCount: c.Codec<UserSlotCount> = c.struct({
  pid: c.u32,
  typeId: c.u32,
  usedSlots: c.u32,
  totalSlots: c.u32,
});

export interface UserContentURL {
  protocol: string;
  host: string;
  path: string;
}
export const UserContentURL: c.Codec<UserContentURL> = c.struct({
  protocol: c.string,
  host: c.string,
  path: c.string,
});

export interface WeightedTag {
  id: number;
  numberOfOccurences: number;
}
export const WeightedTag: c.Codec<WeightedTag> = c.struct({
  id: c.u32,
  numberOfOccurences: c.u32,
});
