// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UserStorage.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { ContentProperty, UserContent, UserContentKey, UserContentURL, UserSlotCount, UserStorageQuery, WeightedTag } from "./types";

export interface SearchContentsRequest {
  query: UserStorageQuery;
}
export const SearchContentsRequest: c.Codec<SearchContentsRequest> = c.struct({
  query: UserStorageQuery,
});

export interface SearchContentsResponse {
  searchResults: UserContent[];
}
export const SearchContentsResponse: c.Codec<SearchContentsResponse> = c.struct({
  searchResults: c.list(UserContent),
});

export interface SearchContentsWithTotalRequest {
  query: UserStorageQuery;
}
export const SearchContentsWithTotalRequest: c.Codec<SearchContentsWithTotalRequest> = c.struct({
  query: UserStorageQuery,
});

export interface SearchContentsWithTotalResponse {
  searchResults: UserContent[];
  totalResults: number;
}
export const SearchContentsWithTotalResponse: c.Codec<SearchContentsWithTotalResponse> = c.struct({
  searchResults: c.list(UserContent),
  totalResults: c.u32,
});

export interface DeleteContentRequest {
  contentKey: UserContentKey;
}
export const DeleteContentRequest: c.Codec<DeleteContentRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface DeleteContentResponse {}
export const DeleteContentResponse: c.Codec<DeleteContentResponse> = c.struct({});

export interface SaveMetaDataRequest {
  properties: ContentProperty[];
}
export const SaveMetaDataRequest: c.Codec<SaveMetaDataRequest> = c.struct({
  properties: c.list(ContentProperty),
});

export interface SaveMetaDataResponse {
  contentKey: UserContentKey;
}
export const SaveMetaDataResponse: c.Codec<SaveMetaDataResponse> = c.struct({
  contentKey: UserContentKey,
});

export interface SaveContentDbRequest {
  properties: ContentProperty[];
  data: Buffer;
}
export const SaveContentDbRequest: c.Codec<SaveContentDbRequest> = c.struct({
  properties: c.list(ContentProperty),
  data: c.buffer,
});

export interface SaveContentDbResponse {
  contentKey: UserContentKey;
}
export const SaveContentDbResponse: c.Codec<SaveContentDbResponse> = c.struct({
  contentKey: UserContentKey,
});

export interface SaveContentAndGetUploadInfoRequest {
  properties: ContentProperty[];
  size: number;
  contentKey: UserContentKey;
}
export const SaveContentAndGetUploadInfoRequest: c.Codec<SaveContentAndGetUploadInfoRequest> = c.struct({
  properties: c.list(ContentProperty),
  size: c.u32,
  contentKey: UserContentKey,
});

export interface SaveContentAndGetUploadInfoResponse {
  uploadInfo: UserContentURL;
  pendingId: bigint;
  headers: string[];
}
export const SaveContentAndGetUploadInfoResponse: c.Codec<SaveContentAndGetUploadInfoResponse> = c.struct({
  uploadInfo: UserContentURL,
  pendingId: c.u64,
  headers: c.list(c.string),
});

export interface UploadEndRequest {
  pendingId: bigint;
  result: boolean;
}
export const UploadEndRequest: c.Codec<UploadEndRequest> = c.struct({
  pendingId: c.u64,
  result: c.bool,
});

export interface UploadEndResponse {
  contentKey: UserContentKey;
}
export const UploadEndResponse: c.Codec<UploadEndResponse> = c.struct({
  contentKey: UserContentKey,
});

export interface GetContentDbRequest {
  contentKey: UserContentKey;
}
export const GetContentDbRequest: c.Codec<GetContentDbRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface GetContentDbResponse {
  data: Buffer;
}
export const GetContentDbResponse: c.Codec<GetContentDbResponse> = c.struct({
  data: c.buffer,
});

export interface GetContentUrlRequest {
  contentKey: UserContentKey;
}
export const GetContentUrlRequest: c.Codec<GetContentUrlRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface GetContentUrlResponse {
  downloadInfo: UserContentURL;
}
export const GetContentUrlResponse: c.Codec<GetContentUrlResponse> = c.struct({
  downloadInfo: UserContentURL,
});

export interface GetSlotCountRequest {
  typeId: number;
}
export const GetSlotCountRequest: c.Codec<GetSlotCountRequest> = c.struct({
  typeId: c.u32,
});

export interface GetSlotCountResponse {
  slotCount: UserSlotCount;
}
export const GetSlotCountResponse: c.Codec<GetSlotCountResponse> = c.struct({
  slotCount: UserSlotCount,
});

export interface GetMetaDataRequest {
  contentKey: UserContentKey;
}
export const GetMetaDataRequest: c.Codec<GetMetaDataRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface GetMetaDataResponse {
  content: UserContent;
}
export const GetMetaDataResponse: c.Codec<GetMetaDataResponse> = c.struct({
  content: UserContent,
});

export interface LikeRequest {
  contentKey: UserContentKey;
}
export const LikeRequest: c.Codec<LikeRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface LikeResponse {}
export const LikeResponse: c.Codec<LikeResponse> = c.struct({});

export interface UnlikeRequest {
  contentKey: UserContentKey;
}
export const UnlikeRequest: c.Codec<UnlikeRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface UnlikeResponse {}
export const UnlikeResponse: c.Codec<UnlikeResponse> = c.struct({});

export interface IsLikedRequest {
  contentKey: UserContentKey;
}
export const IsLikedRequest: c.Codec<IsLikedRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface IsLikedResponse {
  liked: boolean;
}
export const IsLikedResponse: c.Codec<IsLikedResponse> = c.struct({
  liked: c.bool,
});

export interface GetFavouritesRequest {
  contentTypes: number[];
}
export const GetFavouritesRequest: c.Codec<GetFavouritesRequest> = c.struct({
  contentTypes: c.list(c.u32),
});

export interface GetFavouritesResponse {
  favourites: UserContent[];
}
export const GetFavouritesResponse: c.Codec<GetFavouritesResponse> = c.struct({
  favourites: c.list(UserContent),
});

export interface MakeFavouriteRequest {
  contentKey: UserContentKey;
}
export const MakeFavouriteRequest: c.Codec<MakeFavouriteRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface MakeFavouriteResponse {}
export const MakeFavouriteResponse: c.Codec<MakeFavouriteResponse> = c.struct({});

export interface RemoveFromFavouritesRequest {
  contentKey: UserContentKey;
}
export const RemoveFromFavouritesRequest: c.Codec<RemoveFromFavouritesRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface RemoveFromFavouritesResponse {}
export const RemoveFromFavouritesResponse: c.Codec<RemoveFromFavouritesResponse> = c.struct({});

export interface ReportInappropriateRequest {
  contentKey: UserContentKey;
  reason: string;
}
export const ReportInappropriateRequest: c.Codec<ReportInappropriateRequest> = c.struct({
  contentKey: UserContentKey,
  reason: c.string,
});

export interface ReportInappropriateResponse {}
export const ReportInappropriateResponse: c.Codec<ReportInappropriateResponse> = c.struct({});

export interface IncrementPlayCountRequest {
  contentKey: UserContentKey;
}
export const IncrementPlayCountRequest: c.Codec<IncrementPlayCountRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface IncrementPlayCountResponse {}
export const IncrementPlayCountResponse: c.Codec<IncrementPlayCountResponse> = c.struct({});

export interface UpdateCustomStatRequest {
  contentKey: UserContentKey;
  statId: number;
  incValue: bigint;
}
export const UpdateCustomStatRequest: c.Codec<UpdateCustomStatRequest> = c.struct({
  contentKey: UserContentKey,
  statId: c.u16,
  incValue: c.i64,
});

export interface UpdateCustomStatResponse {}
export const UpdateCustomStatResponse: c.Codec<UpdateCustomStatResponse> = c.struct({});

export interface GetOwnContentsRequest {
  typeId: number;
}
export const GetOwnContentsRequest: c.Codec<GetOwnContentsRequest> = c.struct({
  typeId: c.u32,
});

export interface GetOwnContentsResponse {
  results: UserContent[];
}
export const GetOwnContentsResponse: c.Codec<GetOwnContentsResponse> = c.struct({
  results: c.list(UserContent),
});

export interface GetMostPopularTagsRequest {
  contentKey: UserContentKey;
}
export const GetMostPopularTagsRequest: c.Codec<GetMostPopularTagsRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface GetMostPopularTagsResponse {
  tags: WeightedTag[];
  totalNumberOfTaggings: number;
}
export const GetMostPopularTagsResponse: c.Codec<GetMostPopularTagsResponse> = c.struct({
  tags: c.list(WeightedTag),
  totalNumberOfTaggings: c.u32,
});

export interface GetTagsRequest {
  contentKey: UserContentKey;
}
export const GetTagsRequest: c.Codec<GetTagsRequest> = c.struct({
  contentKey: UserContentKey,
});

export interface GetTagsResponse {
  tagIds: number[];
}
export const GetTagsResponse: c.Codec<GetTagsResponse> = c.struct({
  tagIds: c.list(c.u32),
});

export interface TagContentRequest {
  contentKey: UserContentKey;
  newTagIds: number[];
}
export const TagContentRequest: c.Codec<TagContentRequest> = c.struct({
  contentKey: UserContentKey,
  newTagIds: c.list(c.u32),
});

export interface TagContentResponse {}
export const TagContentResponse: c.Codec<TagContentResponse> = c.struct({});

export interface SearchContentsByPlayersRequest {
  pids: number[];
  query: UserStorageQuery;
}
export const SearchContentsByPlayersRequest: c.Codec<SearchContentsByPlayersRequest> = c.struct({
  pids: c.list(c.u32),
  query: UserStorageQuery,
});

export interface SearchContentsByPlayersResponse {
  searchResults: UserContent[];
}
export const SearchContentsByPlayersResponse: c.Codec<SearchContentsByPlayersResponse> = c.struct({
  searchResults: c.list(UserContent),
});

export interface SearchContentsByPlayersWithTotalRequest {
  pids: number[];
  query: UserStorageQuery;
}
export const SearchContentsByPlayersWithTotalRequest: c.Codec<SearchContentsByPlayersWithTotalRequest> = c.struct({
  pids: c.list(c.u32),
  query: UserStorageQuery,
});

export interface SearchContentsByPlayersWithTotalResponse {
  searchResults: UserContent[];
  totalResults: number;
}
export const SearchContentsByPlayersWithTotalResponse: c.Codec<SearchContentsByPlayersWithTotalResponse> = c.struct({
  searchResults: c.list(UserContent),
  totalResults: c.u32,
});

export const UserStorageProtocol = defineProtocol({
  id: 53,
  name: "UserStorageProtocol",
  methods: {
    searchContents: { id: 1, name: "SearchContents", request: SearchContentsRequest, response: SearchContentsResponse },
    searchContentsWithTotal: { id: 2, name: "SearchContentsWithTotal", request: SearchContentsWithTotalRequest, response: SearchContentsWithTotalResponse },
    deleteContent: { id: 3, name: "DeleteContent", request: DeleteContentRequest, response: DeleteContentResponse },
    saveMetaData: { id: 4, name: "SaveMetaData", request: SaveMetaDataRequest, response: SaveMetaDataResponse },
    saveContentDb: { id: 5, name: "SaveContentDB", request: SaveContentDbRequest, response: SaveContentDbResponse },
    saveContentAndGetUploadInfo: { id: 6, name: "SaveContentAndGetUploadInfo", request: SaveContentAndGetUploadInfoRequest, response: SaveContentAndGetUploadInfoResponse },
    uploadEnd: { id: 7, name: "UploadEnd", request: UploadEndRequest, response: UploadEndResponse },
    getContentDb: { id: 8, name: "GetContentDB", request: GetContentDbRequest, response: GetContentDbResponse },
    getContentUrl: { id: 9, name: "GetContentURL", request: GetContentUrlRequest, response: GetContentUrlResponse },
    getSlotCount: { id: 10, name: "GetSlotCount", request: GetSlotCountRequest, response: GetSlotCountResponse },
    getMetaData: { id: 11, name: "GetMetaData", request: GetMetaDataRequest, response: GetMetaDataResponse },
    like: { id: 12, name: "Like", request: LikeRequest, response: LikeResponse },
    unlike: { id: 13, name: "Unlike", request: UnlikeRequest, response: UnlikeResponse },
    isLiked: { id: 14, name: "IsLiked", request: IsLikedRequest, response: IsLikedResponse },
    getFavourites: { id: 15, name: "GetFavourites", request: GetFavouritesRequest, response: GetFavouritesResponse },
    makeFavourite: { id: 16, name: "MakeFavourite", request: MakeFavouriteRequest, response: MakeFavouriteResponse },
    removeFromFavourites: { id: 17, name: "RemoveFromFavourites", request: RemoveFromFavouritesRequest, response: RemoveFromFavouritesResponse },
    reportInappropriate: { id: 18, name: "ReportInappropriate", request: ReportInappropriateRequest, response: ReportInappropriateResponse },
    incrementPlayCount: { id: 19, name: "IncrementPlayCount", request: IncrementPlayCountRequest, response: IncrementPlayCountResponse },
    updateCustomStat: { id: 20, name: "UpdateCustomStat", request: UpdateCustomStatRequest, response: UpdateCustomStatResponse },
    getOwnContents: { id: 21, name: "GetOwnContents", request: GetOwnContentsRequest, response: GetOwnContentsResponse },
    getMostPopularTags: { id: 22, name: "GetMostPopularTags", request: GetMostPopularTagsRequest, response: GetMostPopularTagsResponse },
    getTags: { id: 23, name: "GetTags", request: GetTagsRequest, response: GetTagsResponse },
    tagContent: { id: 24, name: "TagContent", request: TagContentRequest, response: TagContentResponse },
    searchContentsByPlayers: { id: 25, name: "SearchContentsByPlayers", request: SearchContentsByPlayersRequest, response: SearchContentsByPlayersResponse },
    searchContentsByPlayersWithTotal: { id: 26, name: "SearchContentsByPlayersWithTotal", request: SearchContentsByPlayersWithTotalRequest, response: SearchContentsByPlayersWithTotalResponse },
  },
});
