// AUTOGENERATED by scripts/generate-protocols.ts from ddl/NATTraversal.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";

export interface RequestProbeInitiationRequest {
  urlTargetList: q.StationURL[];
}
export const RequestProbeInitiationRequest: c.Codec<RequestProbeInitiationRequest> = c.struct({
  urlTargetList: c.list(q.stationUrl),
});

export interface RequestProbeInitiationResponse {}
export const RequestProbeInitiationResponse: c.Codec<RequestProbeInitiationResponse> = c.struct({});

export interface InitiateProbeRequest {
  urlStationToProbe: q.StationURL;
}
export const InitiateProbeRequest: c.Codec<InitiateProbeRequest> = c.struct({
  urlStationToProbe: q.stationUrl,
});

export interface InitiateProbeResponse {}
export const InitiateProbeResponse: c.Codec<InitiateProbeResponse> = c.struct({});

export interface RequestProbeInitiationExtRequest {
  urlTargetList: q.StationURL[];
  urlStationToProbe: q.StationURL;
}
export const RequestProbeInitiationExtRequest: c.Codec<RequestProbeInitiationExtRequest> = c.struct({
  urlTargetList: c.list(q.stationUrl),
  urlStationToProbe: q.stationUrl,
});

export interface RequestProbeInitiationExtResponse {}
export const RequestProbeInitiationExtResponse: c.Codec<RequestProbeInitiationExtResponse> = c.struct({});

export const NATTraversalProtocol = defineProtocol({
  id: 3,
  name: "NATTraversalProtocol",
  methods: {
    requestProbeInitiation: { id: 1, name: "RequestProbeInitiation", request: RequestProbeInitiationRequest, response: RequestProbeInitiationResponse },
    initiateProbe: { id: 2, name: "InitiateProbe", request: InitiateProbeRequest, response: InitiateProbeResponse },
    requestProbeInitiationExt: { id: 3, name: "RequestProbeInitiationExt", request: RequestProbeInitiationExtRequest, response: RequestProbeInitiationExtResponse },
  },
});
