// AUTOGENERATED by scripts/generate-protocols.ts from ddl/OfflineGameNotificationsService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { TimedNotification } from "./types";
import { NotificationEvent } from "../protocol-foundation/types";

export interface PollNotificationsRequest {}
export const PollNotificationsRequest: c.Codec<PollNotificationsRequest> = c.struct({});

export interface PollNotificationsResponse {
  listNotifications: NotificationEvent[];
  nbRemainingNotifs: number;
}
export const PollNotificationsResponse: c.Codec<PollNotificationsResponse> = c.struct({
  listNotifications: c.list(NotificationEvent),
  nbRemainingNotifs: c.u32,
});

export interface PollSpecificOfflineNotificationsRequest {
  majortype: number[];
}
export const PollSpecificOfflineNotificationsRequest: c.Codec<PollSpecificOfflineNotificationsRequest> = c.struct({
  majortype: c.list(c.u32),
});

export interface PollSpecificOfflineNotificationsResponse {
  listTimedNotification: TimedNotification[];
  ret: number;
}
export const PollSpecificOfflineNotificationsResponse: c.Codec<PollSpecificOfflineNotificationsResponse> = c.struct({
  listTimedNotification: c.list(TimedNotification),
  ret: c.u32,
});

export interface PollAnyOfflineNotificationsRequest {}
export const PollAnyOfflineNotificationsRequest: c.Codec<PollAnyOfflineNotificationsRequest> = c.struct({});

export interface PollAnyOfflineNotificationsResponse {
  listTimedNotification: TimedNotification[];
  nbRemainingNotifs: number;
}
export const PollAnyOfflineNotificationsResponse: c.Codec<PollAnyOfflineNotificationsResponse> = c.struct({
  listTimedNotification: c.list(TimedNotification),
  nbRemainingNotifs: c.u32,
});

export const OfflineGameNotificationsProtocol = defineProtocol({
  id: 71,
  name: "OfflineGameNotificationsProtocol",
  methods: {
    pollNotifications: { id: 1, name: "PollNotifications", request: PollNotificationsRequest, response: PollNotificationsResponse },
    pollSpecificOfflineNotifications: { id: 2, name: "PollSpecificOfflineNotifications", request: PollSpecificOfflineNotificationsRequest, response: PollSpecificOfflineNotificationsResponse },
    pollAnyOfflineNotifications: { id: 3, name: "PollAnyOfflineNotifications", request: PollAnyOfflineNotificationsRequest, response: PollAnyOfflineNotificationsResponse },
  },
});
