// AUTOGENERATED by scripts/generate-protocols.ts from ddl/OfflineGameNotificationsService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";
import { NotificationEvent } from "../protocol-foundation/types";

export interface TimedNotification {
  timestamp: bigint;
  notification: NotificationEvent;
}
export const TimedNotification: c.Codec<TimedNotification> = c.struct({
  timestamp: q.dateTime,
  notification: NotificationEvent,
});
