// AUTOGENERATED by scripts/generate-protocols.ts from ddl/GameSessionService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import * as q from "../../quazal/types";
import { GameSession, GameSessionInvitation, GameSessionInvitationReceived, GameSessionInvitationSent, GameSessionKey, GameSessionMessage, GameSessionParticipant, GameSessionQuery, GameSessionSearchResult, GameSessionSearchWithParticipantsResult, GameSessionSocialQuery, GameSessionUnsuccessfulJoinSession, GameSessionUpdate } from "./types";

export interface CreateSessionRequest {
  gameSession: GameSession;
}
export const CreateSessionRequest: c.Codec<CreateSessionRequest> = c.struct({
  gameSession: GameSession,
});

export interface CreateSessionResponse {
  gameSessionKey: GameSessionKey;
}
export const CreateSessionResponse: c.Codec<CreateSessionResponse> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface UpdateSessionRequest {
  gameSessionUpdate: GameSessionUpdate;
}
export const UpdateSessionRequest: c.Codec<UpdateSessionRequest> = c.struct({
  gameSessionUpdate: GameSessionUpdate,
});

export interface UpdateSessionResponse {}
export const UpdateSessionResponse: c.Codec<UpdateSessionResponse> = c.struct({});

export interface DeleteSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const DeleteSessionRequest: c.Codec<DeleteSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface DeleteSessionResponse {}
export const DeleteSessionResponse: c.Codec<DeleteSessionResponse> = c.struct({});

export interface MigrateSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const MigrateSessionRequest: c.Codec<MigrateSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface MigrateSessionResponse {
  gameSessionKeyMigrated: GameSessionKey;
}
export const MigrateSessionResponse: c.Codec<MigrateSessionResponse> = c.struct({
  gameSessionKeyMigrated: GameSessionKey,
});

export interface LeaveSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const LeaveSessionRequest: c.Codec<LeaveSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface LeaveSessionResponse {}
export const LeaveSessionResponse: c.Codec<LeaveSessionResponse> = c.struct({});

export interface GetSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const GetSessionRequest: c.Codec<GetSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface GetSessionResponse {
  searchResult: GameSessionSearchResult;
}
export const GetSessionResponse: c.Codec<GetSessionResponse> = c.struct({
  searchResult: GameSessionSearchResult,
});

export interface SearchSessionsRequest {
  gameSessionQuery: GameSessionQuery;
}
export const SearchSessionsRequest: c.Codec<SearchSessionsRequest> = c.struct({
  gameSessionQuery: GameSessionQuery,
});

export interface SearchSessionsResponse {
  searchResults: GameSessionSearchResult[];
}
export const SearchSessionsResponse: c.Codec<SearchSessionsResponse> = c.struct({
  searchResults: c.list(GameSessionSearchResult),
});

export interface AddParticipantsRequest {
  gameSessionKey: GameSessionKey;
  publicParticipantIds: number[];
  privateParticipantIds: number[];
}
export const AddParticipantsRequest: c.Codec<AddParticipantsRequest> = c.struct({
  gameSessionKey: GameSessionKey,
  publicParticipantIds: c.list(c.u32),
  privateParticipantIds: c.list(c.u32),
});

export interface AddParticipantsResponse {}
export const AddParticipantsResponse: c.Codec<AddParticipantsResponse> = c.struct({});

export interface RemoveParticipantsRequest {
  gameSessionKey: GameSessionKey;
  participantIds: number[];
}
export const RemoveParticipantsRequest: c.Codec<RemoveParticipantsRequest> = c.struct({
  gameSessionKey: GameSessionKey,
  participantIds: c.list(c.u32),
});

export interface RemoveParticipantsResponse {}
export const RemoveParticipantsResponse: c.Codec<RemoveParticipantsResponse> = c.struct({});

export interface GetParticipantCountRequest {
  gameSessionKey: GameSessionKey;
}
export const GetParticipantCountRequest: c.Codec<GetParticipantCountRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface GetParticipantCountResponse {
  count: number;
}
export const GetParticipantCountResponse: c.Codec<GetParticipantCountResponse> = c.struct({
  count: c.u32,
});

export interface GetParticipantsRequest {
  gameSessionKey: GameSessionKey;
  resultRange: q.ResultRange;
}
export const GetParticipantsRequest: c.Codec<GetParticipantsRequest> = c.struct({
  gameSessionKey: GameSessionKey,
  resultRange: q.ResultRange,
});

export interface GetParticipantsResponse {
  participants: GameSessionParticipant[];
}
export const GetParticipantsResponse: c.Codec<GetParticipantsResponse> = c.struct({
  participants: c.list(GameSessionParticipant),
});

export interface SendInvitationRequest {
  invitation: GameSessionInvitation;
}
export const SendInvitationRequest: c.Codec<SendInvitationRequest> = c.struct({
  invitation: GameSessionInvitation,
});

export interface SendInvitationResponse {}
export const SendInvitationResponse: c.Codec<SendInvitationResponse> = c.struct({});

export interface GetInvitationReceivedCountRequest {
  gameSessionTypeId: number;
}
export const GetInvitationReceivedCountRequest: c.Codec<GetInvitationReceivedCountRequest> = c.struct({
  gameSessionTypeId: c.u32,
});

export interface GetInvitationReceivedCountResponse {
  count: number;
}
export const GetInvitationReceivedCountResponse: c.Codec<GetInvitationReceivedCountResponse> = c.struct({
  count: c.u32,
});

export interface GetInvitationsReceivedRequest {
  gameSessionTypeId: number;
  resultRange: q.ResultRange;
}
export const GetInvitationsReceivedRequest: c.Codec<GetInvitationsReceivedRequest> = c.struct({
  gameSessionTypeId: c.u32,
  resultRange: q.ResultRange,
});

export interface GetInvitationsReceivedResponse {
  invitations: GameSessionInvitationReceived[];
}
export const GetInvitationsReceivedResponse: c.Codec<GetInvitationsReceivedResponse> = c.struct({
  invitations: c.list(GameSessionInvitationReceived),
});

export interface GetInvitationSentCountRequest {
  gameSessionTypeId: number;
}
export const GetInvitationSentCountRequest: c.Codec<GetInvitationSentCountRequest> = c.struct({
  gameSessionTypeId: c.u32,
});

export interface GetInvitationSentCountResponse {
  count: number;
}
export const GetInvitationSentCountResponse: c.Codec<GetInvitationSentCountResponse> = c.struct({
  count: c.u32,
});

export interface GetInvitationsSentRequest {
  gameSessionTypeId: number;
  resultRange: q.ResultRange;
}
export const GetInvitationsSentRequest: c.Codec<GetInvitationsSentRequest> = c.struct({
  gameSessionTypeId: c.u32,
  resultRange: q.ResultRange,
});

export interface GetInvitationsSentResponse {
  invitations: GameSessionInvitationSent[];
}
export const GetInvitationsSentResponse: c.Codec<GetInvitationsSentResponse> = c.struct({
  invitations: c.list(GameSessionInvitationSent),
});

export interface AcceptInvitationRequest {
  gameSessionInvitation: GameSessionInvitationReceived;
}
export const AcceptInvitationRequest: c.Codec<AcceptInvitationRequest> = c.struct({
  gameSessionInvitation: GameSessionInvitationReceived,
});

export interface AcceptInvitationResponse {}
export const AcceptInvitationResponse: c.Codec<AcceptInvitationResponse> = c.struct({});

export interface DeclineInvitationRequest {
  gameSessionInvitation: GameSessionInvitationReceived;
}
export const DeclineInvitationRequest: c.Codec<DeclineInvitationRequest> = c.struct({
  gameSessionInvitation: GameSessionInvitationReceived,
});

export interface DeclineInvitationResponse {}
export const DeclineInvitationResponse: c.Codec<DeclineInvitationResponse> = c.struct({});

export interface CancelInvitationRequest {
  gameSessionInvitation: GameSessionInvitationSent;
}
export const CancelInvitationRequest: c.Codec<CancelInvitationRequest> = c.struct({
  gameSessionInvitation: GameSessionInvitationSent,
});

export interface CancelInvitationResponse {}
export const CancelInvitationResponse: c.Codec<CancelInvitationResponse> = c.struct({});

export interface SendTextMessageRequest {
  gameSessionMessage: GameSessionMessage;
}
export const SendTextMessageRequest: c.Codec<SendTextMessageRequest> = c.struct({
  gameSessionMessage: GameSessionMessage,
});

export interface SendTextMessageResponse {}
export const SendTextMessageResponse: c.Codec<SendTextMessageResponse> = c.struct({});

export interface RegisterUrlsRequest {
  stationUrls: q.StationURL[];
}
export const RegisterUrlsRequest: c.Codec<RegisterUrlsRequest> = c.struct({
  stationUrls: c.list(q.stationUrl),
});

export interface RegisterUrlsResponse {}
export const RegisterUrlsResponse: c.Codec<RegisterUrlsResponse> = c.struct({});

export interface JoinSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const JoinSessionRequest: c.Codec<JoinSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface JoinSessionResponse {}
export const JoinSessionResponse: c.Codec<JoinSessionResponse> = c.struct({});

export interface AbandonSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const AbandonSessionRequest: c.Codec<AbandonSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface AbandonSessionResponse {}
export const AbandonSessionResponse: c.Codec<AbandonSessionResponse> = c.struct({});

export interface SearchSessionsWithParticipantsRequest {
  gameSessionTypeId: number;
  participantIds: number[];
}
export const SearchSessionsWithParticipantsRequest: c.Codec<SearchSessionsWithParticipantsRequest> = c.struct({
  gameSessionTypeId: c.u32,
  participantIds: c.list(c.u32),
});

export interface SearchSessionsWithParticipantsResponse {
  searchResults: GameSessionSearchWithParticipantsResult[];
}
export const SearchSessionsWithParticipantsResponse: c.Codec<SearchSessionsWithParticipantsResponse> = c.struct({
  searchResults: c.list(GameSessionSearchWithParticipantsResult),
});

export interface GetSessionsRequest {
  gameSessionKeys: GameSessionKey[];
}
export const GetSessionsRequest: c.Codec<GetSessionsRequest> = c.struct({
  gameSessionKeys: c.list(GameSessionKey),
});

export interface GetSessionsResponse {
  searchResults: GameSessionSearchResult[];
}
export const GetSessionsResponse: c.Codec<GetSessionsResponse> = c.struct({
  searchResults: c.list(GameSessionSearchResult),
});

export interface GetParticipantsUrlsRequest {
  gameSessionKey: GameSessionKey;
  participantIds: number[];
}
export const GetParticipantsUrlsRequest: c.Codec<GetParticipantsUrlsRequest> = c.struct({
  gameSessionKey: GameSessionKey,
  participantIds: c.list(c.u32),
});

export interface GetParticipantsUrlsResponse {
  participants: GameSessionParticipant[];
}
export const GetParticipantsUrlsResponse: c.Codec<GetParticipantsUrlsResponse> = c.struct({
  participants: c.list(GameSessionParticipant),
});

export interface MigrateSessionHostRequest {
  gameSessionKey: GameSessionKey;
}
export const MigrateSessionHostRequest: c.Codec<MigrateSessionHostRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface MigrateSessionHostResponse {}
export const MigrateSessionHostResponse: c.Codec<MigrateSessionHostResponse> = c.struct({});

export interface SplitSessionRequest {
  gameSessionKey: GameSessionKey;
}
export const SplitSessionRequest: c.Codec<SplitSessionRequest> = c.struct({
  gameSessionKey: GameSessionKey,
});

export interface SplitSessionResponse {
  gameSessionKeyMigrated: GameSessionKey;
}
export const SplitSessionResponse: c.Codec<SplitSessionResponse> = c.struct({
  gameSessionKeyMigrated: GameSessionKey,
});

export interface SearchSocialSessionsRequest {
  gameSessionSocialQuery: GameSessionSocialQuery;
}
export const SearchSocialSessionsRequest: c.Codec<SearchSocialSessionsRequest> = c.struct({
  gameSessionSocialQuery: GameSessionSocialQuery,
});

export interface SearchSocialSessionsResponse {
  searchResults: GameSessionSearchWithParticipantsResult[];
}
export const SearchSocialSessionsResponse: c.Codec<SearchSocialSessionsResponse> = c.struct({
  searchResults: c.list(GameSessionSearchWithParticipantsResult),
});

export interface ReportUnsuccessfulJoinSessionsRequest {
  unsuccessfulJoinSessions: GameSessionUnsuccessfulJoinSession[];
}
export const ReportUnsuccessfulJoinSessionsRequest: c.Codec<ReportUnsuccessfulJoinSessionsRequest> = c.struct({
  unsuccessfulJoinSessions: c.list(GameSessionUnsuccessfulJoinSession),
});

export interface ReportUnsuccessfulJoinSessionsResponse {}
export const ReportUnsuccessfulJoinSessionsResponse: c.Codec<ReportUnsuccessfulJoinSessionsResponse> = c.struct({});

export const GameSessionProtocol = defineProtocol({
  id: 42,
  name: "GameSessionProtocol",
  methods: {
    createSession: { id: 1, name: "CreateSession", request: CreateSessionRequest, response: CreateSessionResponse },
    updateSession: { id: 2, name: "UpdateSession", request: UpdateSessionRequest, response: UpdateSessionResponse },
    deleteSession: { id: 3, name: "DeleteSession", request: DeleteSessionRequest, response: DeleteSessionResponse },
    migrateSession: { id: 4, name: "MigrateSession", request: MigrateSessionRequest, response: MigrateSessionResponse },
    leaveSession: { id: 5, name: "LeaveSession", request: LeaveSessionRequest, response: LeaveSessionResponse },
    getSession: { id: 6, name: "GetSession", request: GetSessionRequest, response: GetSessionResponse },
    searchSessions: { id: 7, name: "SearchSessions", request: SearchSessionsRequest, response: SearchSessionsResponse },
    addParticipants: { id: 8, name: "AddParticipants", request: AddParticipantsRequest, response: AddParticipantsResponse },
    removeParticipants: { id: 9, name: "RemoveParticipants", request: RemoveParticipantsRequest, response: RemoveParticipantsResponse },
    getParticipantCount: { id: 10, name: "GetParticipantCount", request: GetParticipantCountRequest, response: GetParticipantCountResponse },
    getParticipants: { id: 11, name: "GetParticipants", request: GetParticipantsRequest, response: GetParticipantsResponse },
    sendInvitation: { id: 12, name: "SendInvitation", request: SendInvitationRequest, response: SendInvitationResponse },
    getInvitationReceivedCount: { id: 13, name: "GetInvitationReceivedCount", request: GetInvitationReceivedCountRequest, response: GetInvitationReceivedCountResponse },
    getInvitationsReceived: { id: 14, name: "GetInvitationsReceived", request: GetInvitationsReceivedRequest, response: GetInvitationsReceivedResponse },
    getInvitationSentCount: { id: 15, name: "GetInvitationSentCount", request: GetInvitationSentCountRequest, response: GetInvitationSentCountResponse },
    getInvitationsSent: { id: 16, name: "GetInvitationsSent", request: GetInvitationsSentRequest, response: GetInvitationsSentResponse },
    acceptInvitation: { id: 17, name: "AcceptInvitation", request: AcceptInvitationRequest, response: AcceptInvitationResponse },
    declineInvitation: { id: 18, name: "DeclineInvitation", request: DeclineInvitationRequest, response: DeclineInvitationResponse },
    cancelInvitation: { id: 19, name: "CancelInvitation", request: CancelInvitationRequest, response: CancelInvitationResponse },
    sendTextMessage: { id: 20, name: "SendTextMessage", request: SendTextMessageRequest, response: SendTextMessageResponse },
    registerUrls: { id: 21, name: "RegisterURLs", request: RegisterUrlsRequest, response: RegisterUrlsResponse },
    joinSession: { id: 22, name: "JoinSession", request: JoinSessionRequest, response: JoinSessionResponse },
    abandonSession: { id: 23, name: "AbandonSession", request: AbandonSessionRequest, response: AbandonSessionResponse },
    searchSessionsWithParticipants: { id: 24, name: "SearchSessionsWithParticipants", request: SearchSessionsWithParticipantsRequest, response: SearchSessionsWithParticipantsResponse },
    getSessions: { id: 25, name: "GetSessions", request: GetSessionsRequest, response: GetSessionsResponse },
    getParticipantsUrls: { id: 26, name: "GetParticipantsURLs", request: GetParticipantsUrlsRequest, response: GetParticipantsUrlsResponse },
    migrateSessionHost: { id: 27, name: "MigrateSessionHost", request: MigrateSessionHostRequest, response: MigrateSessionHostResponse },
    splitSession: { id: 28, name: "SplitSession", request: SplitSessionRequest, response: SplitSessionResponse },
    searchSocialSessions: { id: 29, name: "SearchSocialSessions", request: SearchSocialSessionsRequest, response: SearchSocialSessionsResponse },
    reportUnsuccessfulJoinSessions: { id: 30, name: "ReportUnsuccessfulJoinSessions", request: ReportUnsuccessfulJoinSessionsRequest, response: ReportUnsuccessfulJoinSessionsResponse },
  },
});
