// AUTOGENERATED by scripts/generate-protocols.ts from ddl/GameSessionService.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface GameSessionKey {
  typeId: number;
  sessionId: number;
}
export const GameSessionKey: c.Codec<GameSessionKey> = c.struct({
  typeId: c.u32,
  sessionId: c.u32,
});

export interface GameSession {
  typeId: number;
  attributes: q.Property[];
}
export const GameSession: c.Codec<GameSession> = c.struct({
  typeId: c.u32,
  attributes: c.list(q.Property),
});

export interface GameSessionSearchResult {
  sessionKey: GameSessionKey;
  hostPid: number;
  hostUrls: q.StationURL[];
  attributes: q.Property[];
}
export const GameSessionSearchResult: c.Codec<GameSessionSearchResult> = c.struct({
  sessionKey: GameSessionKey,
  hostPid: c.u32,
  hostUrls: c.list(q.stationUrl),
  attributes: c.list(q.Property),
});

export interface GameSessionUpdate {
  sessionKey: GameSessionKey;
  attributes: q.Property[];
}
export const GameSessionUpdate: c.Codec<GameSessionUpdate> = c.struct({
  sessionKey: GameSessionKey,
  attributes: c.list(q.Property),
});

export interface GameSessionParticipant {
  pid: number;
  name: string;
  stationUrls: q.StationURL[];
}
export const GameSessionParticipant: c.Codec<GameSessionParticipant> = c.struct({
  pid: c.u32,
  name: c.string,
  stationUrls: c.list(q.stationUrl),
});

export interface GameSessionInvitation {
  sessionKey: GameSessionKey;
  recipientPids: number[];
  message: string;
}
export const GameSessionInvitation: c.Codec<GameSessionInvitation> = c.struct({
  sessionKey: GameSessionKey,
  recipientPids: c.list(c.u32),
  message: c.string,
});

export interface GameSessionInvitationSent {
  sessionKey: GameSessionKey;
  recipientPid: number;
  message: string;
  creationTime: bigint;
}
export const GameSessionInvitationSent: c.Codec<GameSessionInvitationSent> = c.struct({
  sessionKey: GameSessionKey,
  recipientPid: c.u32,
  message: c.string,
  creationTime: q.dateTime,
});

export interface GameSessionInvitationReceived {
  sessionKey: GameSessionKey;
  senderPid: number;
  message: string;
  creationTime: bigint;
}
export const GameSessionInvitationReceived: c.Codec<GameSessionInvitationReceived> = c.struct({
  sessionKey: GameSessionKey,
  senderPid: c.u32,
  message: c.string,
  creationTime: q.dateTime,
});

export interface GameSessionQuery {
  typeId: number;
  queryId: number;
  parameters: q.Property[];
}
export const GameSessionQuery: c.Codec<GameSessionQuery> = c.struct({
  typeId: c.u32,
  queryId: c.u32,
  parameters: c.list(q.Property),
});

export interface GameSessionSocialQuery {
  typeId: number;
  queryId: number;
  parameters: q.Property[];
  participantIds: number[];
}
export const GameSessionSocialQuery: c.Codec<GameSessionSocialQuery> = c.struct({
  typeId: c.u32,
  queryId: c.u32,
  parameters: c.list(q.Property),
  participantIds: c.list(c.u32),
});

export interface GameSessionMessage {
  sessionKey: GameSessionKey;
  message: string;
}
export const GameSessionMessage: c.Codec<GameSessionMessage> = c.struct({
  sessionKey: GameSessionKey,
  message: c.string,
});

export interface GameSessionSearchWithParticipantsResult {
  gameSessionSearchResult: GameSessionSearchResult;
  participantIds: number[];
}
export const GameSessionSearchWithParticipantsResult: c.Codec<GameSessionSearchWithParticipantsResult> = c.struct({
  gameSessionSearchResult: GameSessionSearchResult,
  participantIds: c.list(c.u32),
});

export interface GameSessionUnsuccessfulJoinSession {
  sessionKey: GameSessionKey;
  errorCategory: number;
  errorCode: number;
}
export const GameSessionUnsuccessfulJoinSession: c.Codec<GameSessionUnsuccessfulJoinSession> = c.struct({
  sessionKey: GameSessionKey,
  errorCategory: c.u32,
  errorCode: c.i32,
});
