/**
 * RMC protocol dispatch (port of `quazal::rmc::{Protocol, RVSecHandler}` and the
 * server half of the protocol code generated by quazal-tools).
 */
import type { Logger } from "../../logger";
import { decode, encode, type Codec, type Infer } from "../codec";
import type { StreamCall, StreamHandler } from "../prudp/server";
import { StreamError } from "../stream";
import { RmcError, RmcErrorKind } from "./error";
import { encodeRmcResponse, parseRmcPacket, type RmcRequest, type RmcResult } from "./message";

/** A registered RMC protocol. */
export interface Protocol {
  readonly id: number;
  readonly name: string;
  readonly numMethods: number;
  methodName(methodId: number): string | undefined;
  /** Returns the serialized response data, or throws an `RmcError`. */
  handle(call: StreamCall, request: RmcRequest): Buffer;
}

export interface MethodDefinition<Req = any, Res = any> {
  readonly id: number;
  readonly name: string;
  readonly request: Codec<Req>;
  readonly response: Codec<Res>;
}

/** Protocol description generated from the DDL (see `scripts/generate-protocols.ts`). */
export interface ProtocolDefinition<M extends Record<string, MethodDefinition> = Record<string, MethodDefinition>> {
  /** `undefined` for protocols without a known id. */
  readonly id: number | undefined;
  readonly name: string;
  readonly methods: M;
}

export function defineProtocol<const Id extends number | undefined, const M extends Record<string, MethodDefinition>>(
  definition: ProtocolDefinition<M> & { readonly id: Id },
) {
  return definition;
}

export type MethodRequest<M> = M extends MethodDefinition<infer Req, any> ? Req : never;
export type MethodResponse<M> = M extends MethodDefinition<any, infer Res> ? Res : never;

/** Method handlers of a protocol. Missing methods answer with `UnimplementedMethod`. */
export type ProtocolImplementation<P extends ProtocolDefinition> = {
  [K in keyof P["methods"]]?: (
    request: MethodRequest<P["methods"][K]>,
    call: StreamCall,
  ) => MethodResponse<P["methods"][K]>;
};

export function implementProtocol<P extends ProtocolDefinition>(
  definition: P,
  implementation: ProtocolImplementation<P>,
): Protocol {
  const { id, name } = definition;
  if (id === undefined) {
    throw new Error(`protocol ${name} has no known id`);
  }
  const methods = new Map<number, [string, MethodDefinition]>(
    Object.entries(definition.methods).map(([key, method]) => [method.id, [key, method]]),
  );
  const handlers = implementation as Record<string, ((request: unknown, call: StreamCall) => unknown) | undefined>;

  return {
    id,
    name,
    numMethods: methods.size,
    methodName: (methodId) => methods.get(methodId)?.[1].name,
    handle(call, request) {
      const entry = methods.get(request.methodId);
      if (!entry) {
        throw new RmcError(RmcErrorKind.UnknownMethod);
      }
      const [key, method] = entry;
      const params = decodeParameters(method.request, request.parameters);
      call.logger.debug("Request", { request: params });
      const handler = handlers[key];
      if (!handler) {
        call.logger.warn(`Method ${name}.${method.name} not implemented`);
        throw new RmcError(RmcErrorKind.UnimplementedMethod);
      }
      const response = handler.call(implementation, params, call);
      call.logger.debug("Response", { response });
      return encode(method.response, response);
    },
  };
}

/** Decodes request parameters, turning malformed data into a `ParsingError`. */
export function decodeParameters<T>(codec: Codec<T>, parameters: Buffer): T {
  try {
    return decode(codec, parameters);
  } catch (e) {
    if (e instanceof StreamError || e instanceof RangeError) {
      throw new RmcError(RmcErrorKind.ParsingError, e.message);
    }
    throw e;
  }
}

/** Throws `AccessDenied` unless the client authenticated, and returns its user id. */
export function loginRequired(call: StreamCall) {
  const { userId } = call.client;
  if (userId === undefined) {
    throw new RmcError(RmcErrorKind.AccessDenied);
  }
  return userId;
}

/** Stream handler that dispatches RMC requests to protocols (port of `RVSecHandler`). */
export class RmcDispatcher implements StreamHandler {
  private readonly protocols = new Map<number, Protocol>();

  constructor(private readonly logger: Logger) {}

  register(protocol: Protocol) {
    this.logger.debug(`Registering handler for protocol ${protocol.id} (${protocol.name})`);
    this.protocols.set(protocol.id, protocol);
  }

  handle(call: StreamCall, data: Buffer): Buffer {
    let packet;
    try {
      packet = parseRmcPacket(data);
    } catch (e) {
      call.logger.error("Parsing RMC packet failed", { error: (e as Error).message });
      throw e;
    }
    if (packet.type === "response") {
      call.logger.error(`RMC response not supported here. Data: ${data.toString("hex")}`);
      throw new RmcError(RmcErrorKind.InvalidPacketType, "unexpected RMC response");
    }
    const { request } = packet;
    call.logger.info(`Looking for protocol ${request.protocolId}, method ${request.methodId}`);
    const logger = call.logger.child({
      protocol_id: request.protocolId,
      method_id: request.methodId,
      call: request.callId,
    });

    let result: RmcResult;
    try {
      const protocol = this.protocols.get(request.protocolId);
      if (!protocol) {
        logger.warn("no handler available");
        throw new RmcError(RmcErrorKind.UnknownProtocol);
      }
      logger.info(`Calling ${protocol.name}.${protocol.methodName(request.methodId) ?? ""}`);
      const data = protocol.handle({ ...call, logger }, request);
      result = { ok: true, callId: request.callId, methodId: request.methodId, data };
    } catch (e) {
      const error = e instanceof RmcError ? e : new RmcError(RmcErrorKind.InternalError, (e as Error)?.message);
      logger.error("handling request failed", { error: e instanceof RmcError ? e.message : e });
      result = { ok: false, errorCode: error.errorCode, callId: request.callId };
    }
    const response = { protocolId: request.protocolId, result };
    logger.trace("<- RMC response", { response });
    return encodeRmcResponse(response);
  }
}

/** Response type of a method, handy for implementations. */
export type ResponseOf<P extends ProtocolDefinition, K extends keyof P["methods"]> = MethodResponse<P["methods"][K]>;
export type RequestOf<P extends ProtocolDefinition, K extends keyof P["methods"]> = MethodRequest<P["methods"][K]>;
export type { Infer };
