// AUTOGENERATED by scripts/generate-protocols.ts from ddl/UserAccountManagementService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface LookupSceNpIdsRequest {
  pids: number[];
}
export const LookupSceNpIdsRequest: c.Codec<LookupSceNpIdsRequest> = c.struct({
  pids: c.list(c.u32),
});

export interface LookupSceNpIdsResponse {
  npids: Map<number, Buffer>;
}
export const LookupSceNpIdsResponse: c.Codec<LookupSceNpIdsResponse> = c.struct({
  npids: c.map(c.u32, c.qBuffer),
});

export interface LookupPrincipalIdsRequest {
  firstPartyIds: string[];
  platformId: number;
}
export const LookupPrincipalIdsRequest: c.Codec<LookupPrincipalIdsRequest> = c.struct({
  firstPartyIds: c.list(c.string),
  platformId: c.u32,
});

export interface LookupPrincipalIdsResponse {
  pids: Map<string, number>;
}
export const LookupPrincipalIdsResponse: c.Codec<LookupPrincipalIdsResponse> = c.struct({
  pids: c.map(c.string, c.u32),
});

export interface LookupFirstPartyIdsRequest {
  pids: number[];
  platformId: number;
}
export const LookupFirstPartyIdsRequest: c.Codec<LookupFirstPartyIdsRequest> = c.struct({
  pids: c.list(c.u32),
  platformId: c.u32,
});

export interface LookupFirstPartyIdsResponse {
  firstPartyIds: Map<number, string>;
}
export const LookupFirstPartyIdsResponse: c.Codec<LookupFirstPartyIdsResponse> = c.struct({
  firstPartyIds: c.map(c.u32, c.string),
});

export interface UserHasPlayedRequest {
  firstPartyIds: string[];
  platformId: number;
}
export const UserHasPlayedRequest: c.Codec<UserHasPlayedRequest> = c.struct({
  firstPartyIds: c.list(c.string),
  platformId: c.u32,
});

export interface UserHasPlayedResponse {
  userPresence: Map<string, boolean>;
}
export const UserHasPlayedResponse: c.Codec<UserHasPlayedResponse> = c.struct({
  userPresence: c.map(c.string, c.bool),
});

export interface IsUserPlayingRequest {
  firstPartyIds: string[];
  platformId: number;
}
export const IsUserPlayingRequest: c.Codec<IsUserPlayingRequest> = c.struct({
  firstPartyIds: c.list(c.string),
  platformId: c.u32,
});

export interface IsUserPlayingResponse {
  userPresence: Map<string, boolean>;
}
export const IsUserPlayingResponse: c.Codec<IsUserPlayingResponse> = c.struct({
  userPresence: c.map(c.string, c.bool),
});

export interface UpdateSonyAccountInfoRequest {
  ticketData: Buffer;
  ticketSize: number;
}
export const UpdateSonyAccountInfoRequest: c.Codec<UpdateSonyAccountInfoRequest> = c.struct({
  ticketData: c.qBuffer,
  ticketSize: c.u32,
});

export interface UpdateSonyAccountInfoResponse {}
export const UpdateSonyAccountInfoResponse: c.Codec<UpdateSonyAccountInfoResponse> = c.struct({});

export interface LookupUsernamesRequest {
  pids: number[];
  platformId: number;
}
export const LookupUsernamesRequest: c.Codec<LookupUsernamesRequest> = c.struct({
  pids: c.list(c.u32),
  platformId: c.u32,
});

export interface LookupUsernamesResponse {
  userNames: Map<number, string>;
}
export const LookupUsernamesResponse: c.Codec<LookupUsernamesResponse> = c.struct({
  userNames: c.map(c.u32, c.string),
});

export const UserAccountManagementProtocol = defineProtocol({
  id: undefined,
  name: "UserAccountManagementProtocol",
  methods: {
    lookupSceNpIds: { id: 1, name: "LookupSceNpIds", request: LookupSceNpIdsRequest, response: LookupSceNpIdsResponse },
    lookupPrincipalIds: { id: 2, name: "LookupPrincipalIDs", request: LookupPrincipalIdsRequest, response: LookupPrincipalIdsResponse },
    lookupFirstPartyIds: { id: 3, name: "LookupFirstPartyIds", request: LookupFirstPartyIdsRequest, response: LookupFirstPartyIdsResponse },
    userHasPlayed: { id: 4, name: "UserHasPlayed", request: UserHasPlayedRequest, response: UserHasPlayedResponse },
    isUserPlaying: { id: 5, name: "IsUserPlaying", request: IsUserPlayingRequest, response: IsUserPlayingResponse },
    updateSonyAccountInfo: { id: 6, name: "updateSonyAccountInfo", request: UpdateSonyAccountInfoRequest, response: UpdateSonyAccountInfoResponse },
    lookupUsernames: { id: 7, name: "LookupUsernames", request: LookupUsernamesRequest, response: LookupUsernamesResponse },
  },
});
