// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ProtocolFoundation.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { NotificationEvent } from "./types";

export interface ProcessNotificationEventRequest {
  oEvent: NotificationEvent;
}
export const ProcessNotificationEventRequest: c.Codec<ProcessNotificationEventRequest> = c.struct({
  oEvent: NotificationEvent,
});

export interface ProcessNotificationEventResponse {}
export const ProcessNotificationEventResponse: c.Codec<ProcessNotificationEventResponse> = c.struct({});

export const NotificationProtocol = defineProtocol({
  id: undefined,
  name: "NotificationProtocol",
  methods: {
    processNotificationEvent: { id: 1, name: "ProcessNotificationEvent", request: ProcessNotificationEventRequest, response: ProcessNotificationEventResponse },
  },
});
