// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ProtocolFoundation.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";

export interface LogRequest {
  strLine: string;
}
export const LogRequest: c.Codec<LogRequest> = c.struct({
  strLine: c.string,
});

export interface LogResponse {}
export const LogResponse: c.Codec<LogResponse> = c.struct({});

export const RemoteLogDeviceProtocol = defineProtocol({
  id: undefined,
  name: "RemoteLogDeviceProtocol",
  methods: {
    log: { id: 1, name: "Log", request: LogRequest, response: LogResponse },
  },
});
