// AUTOGENERATED by scripts/generate-protocols.ts from ddl/ProtocolFoundation.json. Do not edit.
import * as c from "../../quazal/codec";
import * as q from "../../quazal/types";

export interface MessageRecipient {
  idRecipient: number;
  uiRecipientType: number;
}
export const MessageRecipient: c.Codec<MessageRecipient> = c.struct({
  idRecipient: c.u32,
  uiRecipientType: c.u32,
});

export interface NotificationEvent {
  pidSource: number;
  uiType: number;
  uiParam1: number;
  uiParam2: number;
  strParam: string;
  uiParam3: number;
}
export const NotificationEvent: c.Codec<NotificationEvent> = c.struct({
  pidSource: c.u32,
  uiType: c.u32,
  uiParam1: c.u32,
  uiParam2: c.u32,
  strParam: c.string,
  uiParam3: c.u32,
});

export interface Data {}
export const Data: c.Codec<Data> = c.struct({});

export interface DynamicData {
  bufTail: Buffer;
}
export const DynamicData: c.Codec<DynamicData> = c.struct({
  bufTail: c.bufferTail,
});

export interface UserMessage {
  uiId: number;
  idRecipient: number;
  uiRecipientType: number;
  uiParentId: number;
  pidSender: number;
  receptiontime: bigint;
  uiLifeTime: number;
  uiFlags: number;
  strSubject: string;
  strSender: string;
}
export const UserMessage: c.Codec<UserMessage> = c.struct({
  uiId: c.u32,
  idRecipient: c.u32,
  uiRecipientType: c.u32,
  uiParentId: c.u32,
  pidSender: c.u32,
  receptiontime: q.dateTime,
  uiLifeTime: c.u32,
  uiFlags: c.u32,
  strSubject: c.string,
  strSender: c.string,
});

export interface ResultRange {
  uiOffset: number;
  uiSize: number;
}
export const ResultRange: c.Codec<ResultRange> = c.struct({
  uiOffset: c.u32,
  uiSize: c.u32,
});

export interface Property {
  id: number;
  value: number;
}
export const Property: c.Codec<Property> = c.struct({
  id: c.u32,
  value: c.i32,
});

export interface PropertyVariant {
  id: number;
  value: q.Variant;
}
export const PropertyVariant: c.Codec<PropertyVariant> = c.struct({
  id: c.u32,
  value: q.variant,
});
