// AUTOGENERATED by scripts/generate-protocols.ts from ddl/TrackingService.json. Do not edit.
import * as c from "../../quazal/codec";
import { defineProtocol } from "../../quazal/rmc/protocol";
import { TrackingInformation, TrackingTag } from "./types";

export interface SendTagRequest {
  trackingId: number;
  tag: string;
  attributes: string;
  deltaTime: number;
}
export const SendTagRequest: c.Codec<SendTagRequest> = c.struct({
  trackingId: c.u32,
  tag: c.string,
  attributes: c.string,
  deltaTime: c.u32,
});

export interface SendTagResponse {}
export const SendTagResponse: c.Codec<SendTagResponse> = c.struct({});

export interface SendTagAndUpdateUserInfoRequest {
  trackingId: number;
  tag: string;
  attributes: string;
  deltaTime: number;
  userId: string;
}
export const SendTagAndUpdateUserInfoRequest: c.Codec<SendTagAndUpdateUserInfoRequest> = c.struct({
  trackingId: c.u32,
  tag: c.string,
  attributes: c.string,
  deltaTime: c.u32,
  userId: c.string,
});

export interface SendTagAndUpdateUserInfoResponse {}
export const SendTagAndUpdateUserInfoResponse: c.Codec<SendTagAndUpdateUserInfoResponse> = c.struct({});

export interface SendUserInfoRequest {
  deltaTime: number;
}
export const SendUserInfoRequest: c.Codec<SendUserInfoRequest> = c.struct({
  deltaTime: c.u32,
});

export interface SendUserInfoResponse {
  userInfo: TrackingInformation;
  trackingId: number;
}
export const SendUserInfoResponse: c.Codec<SendUserInfoResponse> = c.struct({
  userInfo: TrackingInformation,
  trackingId: c.u32,
});

export interface GetConfigurationRequest {}
export const GetConfigurationRequest: c.Codec<GetConfigurationRequest> = c.struct({});

export interface GetConfigurationResponse {
  tags: string[];
}
export const GetConfigurationResponse: c.Codec<GetConfigurationResponse> = c.struct({
  tags: c.list(c.string),
});

export interface SendTagsRequest {
  tagData: TrackingTag[];
}
export const SendTagsRequest: c.Codec<SendTagsRequest> = c.struct({
  tagData: c.list(TrackingTag),
});

export interface SendTagsResponse {}
export const SendTagsResponse: c.Codec<SendTagsResponse> = c.struct({});

export const TrackingProtocol3 = defineProtocol({
  id: 36,
  name: "TrackingProtocol3",
  methods: {
    sendTag: { id: 1, name: "SendTag", request: SendTagRequest, response: SendTagResponse },
    sendTagAndUpdateUserInfo: { id: 2, name: "SendTagAndUpdateUserInfo", request: SendTagAndUpdateUserInfoRequest, response: SendTagAndUpdateUserInfoResponse },
    sendUserInfo: { id: 3, name: "SendUserInfo", request: SendUserInfoRequest, response: SendUserInfoResponse },
    getConfiguration: { id: 4, name: "GetConfiguration", request: GetConfigurationRequest, response: GetConfigurationResponse },
    sendTags: { id: 5, name: "SendTags", request: SendTagsRequest, response: SendTagsResponse },
  },
});
