// AUTOGENERATED by scripts/generate-protocols.ts from ddl/TrackingService.json. Do not edit.
import * as c from "../../quazal/codec";

export interface TrackingInformation {
  ipn: number;
  userId: string;
  machineId: string;
  visitorId: string;
  utsVersion: string;
}
export const TrackingInformation: c.Codec<TrackingInformation> = c.struct({
  ipn: c.u32,
  userId: c.string,
  machineId: c.string,
  visitorId: c.string,
  utsVersion: c.string,
});

export interface TrackingTag {
  trackingId: number;
  tag: string;
  attributes: string;
  deltaTime: number;
  newUserId: string;
}
export const TrackingTag: c.Codec<TrackingTag> = c.struct({
  trackingId: c.u32,
  tag: c.string,
  attributes: c.string,
  deltaTime: c.u32,
  newUserId: c.string,
});
